# Process and Save top NER keyword

        Count top keywords for each NE 
        Name	Description
        CARDINAL	數字
        DATE	日期
        EVENT	事件
        FAC	設施
        GPE	行政區
        LANGUAGE	語言
        LAW	法律
        LOC	地理區
        MONEY	金錢
        NORP	民族、宗教、政治團體
        ORDINAL	序數
        ORG	組織
        PERCENT	百分比率
        PERSON	人物
        PRODUCT	產品
        QUANTITY	數量
        TIME	時間
        WORK_OF_ART	作品

        The popular keywords for each NE and Category.
        This table is what we want to get. 
                ne_name	top_keys
        0	CARDINAL[(政治, [('2000', 7), ('4000', 2), ('13', 2), ('...
        1	DATE	[(政治, [('今天', 35), ('12天', 2), ('5月', 2), ('同年...
        2	EVENT	[(政治, [('COVID-19（2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭',...
        3	FAC	[(政治, [('台東志航基地', 8), ('台東馬偕醫院', 5), ('新竹空軍基地'...
        4	GPE	[(政治, [('台灣', 25), ('台東', 10), ('法國', 8), ('烏克...
        5	LANGUAGE	[(政治, [('英文', 1)]), (科技, []), (運動, [('中文', 1)]...
        6	LAW	[(政治, []), (科技, [('LINE', 1)]), (運動, []), (證卷,...
        7	LOC	[(政治, [('台灣西南防空識別區', 1), ('北美', 1), ('屯稜線', 1)...
        8	MONEY	[(政治, [('新台幣6億元', 1), ('3萬5703美元', 1), ('約101萬...
        9	NORP	[(政治, [('烏克蘭', 6), ('德商', 2), ('歐商', 1), ('美商'...
        10	ORDINAL	[(政治, [('第四', 2), ('第1', 1), ('第206', 1), ('第8...
        11	ORG	[(政治, [('外交部', 16), ('立法院', 13), ('監察院', 9), (...
        12	PERCENT	[(政治, [('5%', 1), ('45%', 1)]), (科技, [('100%',...
        13	PERSON	[(政治, [('黃重凱', 24), ('柳惠千', 13), ('喬建中', 12), ...
        14	PRODUCT	[(政治, [('2000', 3), ('殲16戰機', 2), ('2017', 1),...
        15	QUANTITY	[(政治, [('2000呎', 6), ('10浬', 5), ('80公頃', 2), ...
        16	TIME	[(政治, [('下午', 10), ('上午', 10), ('11時26分', 5), ...
        17	WORK_OF_ART	[(政治, []), (科技, []), (運動, []), (證卷, []), (產經, ...

# Put them together

In [1]:
import pandas as pd
from collections import Counter

# Read data
df = pd.read_csv('cna_news_preprocessed.csv',sep='|')

# NerToken(word='烏克蘭', ner='GPE', idx=(4, 7))  # call function NerToken with three parameters: word, ner, and idx
# We need the name and keyword
def NerToken(word, ner, idx):
    # print(ner,word)
    return ner,word

# Count top-200 hot keywords for each NER name
# 統計各NER的熱門關鍵字
# word count for a piece of news
def ne_word_frequency( a_news_ne ):
    filtered_words =[]
    for ner,word in a_news_ne:
        if (len(word) >= 2) & (ner in allowedNE):
            filtered_words.append(word)
    counter = Counter( filtered_words )
    return counter.most_common( 20 )

## Count top 200 word frequency for each category given a certain NE, e.g., "PERSON"
'''
    {'政治': [('黃重凱', 24),
    ('柳惠千', 13),
    ('喬建中', 12),
    ('徐國勇', 11),
    ('季欽', 8),
    ('許舒博', 7),
    ('游錫堃', 6),

'''
news_links =['aipl', 'ait', 'aspt', 'asc', 'aie', 'amov','ahel','aopl','asoc','acul','acn']
news_categories=['政治','科技','運動','證卷','產經','娛樂','生活','國際','社會','文化','兩岸']

## To conveniently save data using pandas, we should convert dict to list.
# All-in-one function
def get_top_ner_words():
    top_cate_ner_words={}
    words_all=[]
    for category in news_categories:
        df_group = df[df.category == category]
        words_group = []

        # concatenate terms in a category
        for row in df_group.entities:
            words_group += eval(row)

        # concatenate all terms
        words_all += words_group

        # Get top words by calling ne_word_frequency() function
        topwords = ne_word_frequency( words_group )
        top_cate_ner_words[category] = topwords

    topwords_all = ne_word_frequency(words_all)
    top_cate_ner_words['全部'] = topwords_all
    
    return list(top_cate_ner_words.items()) # convert to list
    # return top_cate_ne_words

# (1) 熱門人物
## Save top-200 hot persons for future usage
# We already have done this in our previous app.
## The most popular products
#allowedNE=['PRODUCT']
allowedNE=['PERSON']
hotPersons = get_top_ner_words()
df_hotPersons = pd.DataFrame(hotPersons, columns = ['category','top_keys'])
df_hotPersons.to_csv('news_top_person_by_category_via_ner.csv', sep=',', index=False) # 與上周的任務相同


# (2) 熱門關鍵字
## We can get top 200 word frequecy for each news categroy by using "entities" column.
allowedNE=['EVENT','FAC','GPE','LANGUAGE','LAW','LOC','NORP','ORG','PERSON','PRODUCT','WORK_OF_ART']
top_group_ner_words = get_top_ner_words()
df_top_group_ner_words = pd.DataFrame(top_group_ner_words, columns = ['category','top_keys'])
df_top_group_ner_words.to_csv('news_topkey_with_category_via_ner.csv', sep=',', index=False) # 與第一次的Django任務相同

# (3) 每個NER的熱門關鍵字
# Count top-200 hot keywords for each NE name
# NER詞性
NE_Name=['CARDINAL','DATE','EVENT','FAC','GPE','LANGUAGE','LAW','LOC','MONEY','NORP','ORDINAL','ORG','PERCENT','PERSON','PRODUCT','QUANTITY','TIME','WORK_OF_ART']
# It takes time, at least 2 minitues.
top_word_NE=[]
for ne_name in NE_Name:
    allowedNE= [ne_name]
    topwords = get_top_ner_words()
    top_word_NE.append([ne_name, topwords])
## Save each ne's top 200 category word frequency
df_top_word_NE = pd.DataFrame(top_word_NE, columns = ['ne_name','top_keys'])
df_top_word_NE.to_csv('news_topkey_by_ner_and_category.csv', sep=',', index=False) # 本次的NER任務

# Step by step demonstration

# Read data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cna_news_preprocessed.csv',sep='|')

In [3]:
df.head(1)

,item_id,date,category,title,content,sentiment,summary,top_key_freq,tokens,tokens_v2,entities,token_pos,link,photo_link
0,aipl_20220314_1,2022/03/14 21:38,政治,外交部援烏物資已募4000箱 吳釗燮感謝捐贈民眾,民眾捐贈烏克蘭的愛心物資持續湧入外交部，截至今天傍晚累計已收到約4000箱，外交部長吳釗燮中...,0.01,"['外交部除感謝熱心民眾踴躍捐贈援助烏克蘭人道物資外', '親赴外交部捐贈物資的民眾約173...","[('外交部', 14), ('民眾', 7), ('物資', 7), ('烏克蘭', 5)...","['民眾', '捐贈', '烏克蘭', '的', '愛心', '物資', '持續', '湧入...","['民眾', '烏克蘭', '愛心', '物資', '外交部', '收到', '外交部長',...","[NerToken(word='烏克蘭', ner='GPE', idx=(4, 7)), ...","[('民眾', 'Na'), ('捐贈', 'VD'), ('烏克蘭', 'Nc'), ('...",https://www.cna.com.tw/news/aipl/202203140364....,https://imgcdn.cna.com.tw/www/WebPhotos/200/20...

# Take a look at the named entities

In [4]:
df.entities[0]

"[NerToken(word='烏克蘭', ner='GPE', idx=(4, 7)), NerToken(word='外交部', ner='ORG', idx=(16, 19)), NerToken(word='傍晚', ner='TIME', idx=(24, 26)), NerToken(word='4000', ner='CARDINAL', idx=(32, 36)), NerToken(word='外交部長', ner='ORG', idx=(38, 42)), NerToken(word='吳釗燮', ner='PERSON', idx=(42, 45)), NerToken(word='中午', ner='TIME', idx=(45, 47)), NerToken(word='外交部', ner='ORG', idx=(76, 79)), NerToken(word='晚間', ner='TIME', idx=(79, 81)), NerToken(word='外交部', ner='ORG', idx=(89, 92)), NerToken(word='7日', ner='DATE', idx=(93, 95)), NerToken(word='烏克蘭', ner='NORP', idx=(104, 107)), NerToken(word='外交部', ner='ORG', idx=(122, 125)), NerToken(word='1730', ner='CARDINAL', idx=(133, 137)), NerToken(word='4000', ner='CARDINAL', idx=(152, 156)), NerToken(word='18日', ner='DATE', idx=(195, 198)), NerToken(word='外交部', ner='ORG', idx=(199, 202)), NerToken(word='外交部', ner='ORG', idx=(228, 231)), NerToken(word='吳釗燮', ner='PERSON', idx=(234, 237)), NerToken(word='今天', ner='DATE', idx=(237, 239)), NerToken(word='中午', ner='TIME', idx=(239, 241)), NerToken(word='外交部', ner='ORG', idx=(245, 248)), NerToken(word='吳釗燮', ner='PERSON', idx=(259, 262)), NerToken(word='慈濟', ner='ORG', idx=(266, 268)), NerToken(word='烏克蘭', ner='NORP', idx=(302, 305)), NerToken(word='吳釗燮', ner='PERSON', idx=(321, 324)), NerToken(word='外交部', ner='ORG', idx=(333, 336)), NerToken(word='烏克蘭', ner='NORP', idx=(347, 350)), NerToken(word='外交部', ner='ORG', idx=(367, 370)), NerToken(word='外交部', ner='ORG', idx=(391, 394)), NerToken(word='外交部', ner='ORG', idx=(422, 425)), NerToken(word='6個月', ner='DATE', idx=(449, 452)), NerToken(word='3月18日', ner='DATE', idx=(479, 484)), NerToken(word='下午', ner='TIME', idx=(484, 486)), NerToken(word='5時', ner='TIME', idx=(486, 488)), NerToken(word='20', ner='CARDINAL', idx=(506, 508)), NerToken(word='外交部', ner='ORG', idx=(520, 523)), NerToken(word='外交部', ner='ORG', idx=(524, 527)), NerToken(word='烏克蘭', ner='NORP', idx=(540, 543)), NerToken(word='外交部', ner='ORG', idx=(566, 569))]"

In [5]:
# NerToken(word='烏克蘭', ner='GPE', idx=(4, 7))  # call function NerToken with three parameters: word, ner, and idx
def NerToken(word, ner, idx):
    # print(ner,word)
    return ner,word

In [6]:
# call function NerToken with three parameters: word, ner, and idx
NerToken(word='烏克蘭', ner='GPE', idx=(4, 7))

('GPE', '烏克蘭')

In [7]:
eval(df.entities[0])

[('GPE', '烏克蘭'),
 ('ORG', '外交部'),
 ('TIME', '傍晚'),
 ('CARDINAL', '4000'),
 ('ORG', '外交部長'),
 ('PERSON', '吳釗燮'),
 ('TIME', '中午'),
 ('ORG', '外交部'),
 ('TIME', '晚間'),
 ('ORG', '外交部'),
 ('DATE', '7日'),
 ('NORP', '烏克蘭'),
 ('ORG', '外交部'),
 ('CARDINAL', '1730'),
 ('CARDINAL', '4000'),
 ('DATE', '18日'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('PERSON', '吳釗燮'),
 ('DATE', '今天'),
 ('TIME', '中午'),
 ('ORG', '外交部'),
 ('PERSON', '吳釗燮'),
 ('ORG', '慈濟'),
 ('NORP', '烏克蘭'),
 ('PERSON', '吳釗燮'),
 ('ORG', '外交部'),
 ('NORP', '烏克蘭'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('DATE', '6個月'),
 ('DATE', '3月18日'),
 ('TIME', '下午'),
 ('TIME', '5時'),
 ('CARDINAL', '20'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('NORP', '烏克蘭'),
 ('ORG', '外交部')]

In [9]:
# We need the name and keyword
for ner,key in eval(df.entities[0]):
    print(ner,key)

GPE 烏克蘭
ORG 外交部
TIME 傍晚
CARDINAL 4000
ORG 外交部長
PERSON 吳釗燮
TIME 中午
ORG 外交部
TIME 晚間
ORG 外交部
DATE 7日
NORP 烏克蘭
ORG 外交部
CARDINAL 1730
CARDINAL 4000
DATE 18日
ORG 外交部
ORG 外交部
PERSON 吳釗燮
DATE 今天
TIME 中午
ORG 外交部
PERSON 吳釗燮
ORG 慈濟
NORP 烏克蘭
PERSON 吳釗燮
ORG 外交部
NORP 烏克蘭
ORG 外交部
ORG 外交部
ORG 外交部
DATE 6個月
DATE 3月18日
TIME 下午
TIME 5時
CARDINAL 20
ORG 外交部
ORG 外交部
NORP 烏克蘭
ORG 外交部

# Count top-200 hot keywords for each NER name

統計各NER的熱門關鍵字

In [8]:
from collections import Counter

CARDINAL	數字
DATE	日期
EVENT	事件
FAC	設施
GPE	行政區
LANGUAGE	語言
LAW	法律
LOC	地理區
MONEY	金錢
NORP	民族、宗教、政治團體
ORDINAL	序數
ORG	組織
PERCENT	百分比率
PERSON	人物
PRODUCT	產品
QUANTITY	數量
TIME	時間
WORK_OF_ART	作品

In [9]:
# Filter condition: two words and specified NER
# allowedNE=['EVENT','FAC','GPE','LANGUAGE','LAW','LOC','NORP','ORG','PERSON','PRODUCT','WORK_OF_ART']
allowedNE=['PERSON']

In [10]:
filtered_words =[]
for ner,word in eval(df.entities[0]):
    if (len(word) >= 2) & (ner in allowedNE):
        filtered_words.append(word)
counter = Counter( filtered_words )
counter.most_common( 50 )

[('吳釗燮', 4)]

In [11]:
# word count for a piece of news
def ne_word_frequency( a_news_ne ):
    filtered_words =[]
    for ner,word in a_news_ne:
        if (len(word) >= 2) & (ner in allowedNE):
            filtered_words.append(word)
    counter = Counter( filtered_words )
    return counter.most_common( 20 )

In [12]:
ne_word_frequency(eval(df.entities[0]))

[('吳釗燮', 4)]

In [13]:
ne_word_frequency(eval(df.entities[1]))

[('許邁德', 2), ('黃重凱', 1), ('柳惠千', 1), ('朱冠甍', 1)]

### Concatenate two lists

In [14]:
a=[]
a += eval(df.entities[0])

In [15]:
a

[('GPE', '烏克蘭'),
 ('ORG', '外交部'),
 ('TIME', '傍晚'),
 ('CARDINAL', '4000'),
 ('ORG', '外交部長'),
 ('PERSON', '吳釗燮'),
 ('TIME', '中午'),
 ('ORG', '外交部'),
 ('TIME', '晚間'),
 ('ORG', '外交部'),
 ('DATE', '7日'),
 ('NORP', '烏克蘭'),
 ('ORG', '外交部'),
 ('CARDINAL', '1730'),
 ('CARDINAL', '4000'),
 ('DATE', '18日'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('PERSON', '吳釗燮'),
 ('DATE', '今天'),
 ('TIME', '中午'),
 ('ORG', '外交部'),
 ('PERSON', '吳釗燮'),
 ('ORG', '慈濟'),
 ('NORP', '烏克蘭'),
 ('PERSON', '吳釗燮'),
 ('ORG', '外交部'),
 ('NORP', '烏克蘭'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('DATE', '6個月'),
 ('DATE', '3月18日'),
 ('TIME', '下午'),
 ('TIME', '5時'),
 ('CARDINAL', '20'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('NORP', '烏克蘭'),
 ('ORG', '外交部')]

In [16]:
a += eval(df.entities[1])

In [17]:
a

[('GPE', '烏克蘭'),
 ('ORG', '外交部'),
 ('TIME', '傍晚'),
 ('CARDINAL', '4000'),
 ('ORG', '外交部長'),
 ('PERSON', '吳釗燮'),
 ('TIME', '中午'),
 ('ORG', '外交部'),
 ('TIME', '晚間'),
 ('ORG', '外交部'),
 ('DATE', '7日'),
 ('NORP', '烏克蘭'),
 ('ORG', '外交部'),
 ('CARDINAL', '1730'),
 ('CARDINAL', '4000'),
 ('DATE', '18日'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('PERSON', '吳釗燮'),
 ('DATE', '今天'),
 ('TIME', '中午'),
 ('ORG', '外交部'),
 ('PERSON', '吳釗燮'),
 ('ORG', '慈濟'),
 ('NORP', '烏克蘭'),
 ('PERSON', '吳釗燮'),
 ('ORG', '外交部'),
 ('NORP', '烏克蘭'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('DATE', '6個月'),
 ('DATE', '3月18日'),
 ('TIME', '下午'),
 ('TIME', '5時'),
 ('CARDINAL', '20'),
 ('ORG', '外交部'),
 ('ORG', '外交部'),
 ('NORP', '烏克蘭'),
 ('ORG', '外交部'),
 ('DATE', '今天'),
 ('QUANTITY', '2000呎'),
 ('FAC', '新竹空軍基地'),
 ('CARDINAL', '2000'),
 ('TIME', '上午'),
 ('GPE', '台東'),
 ('PERSON', '黃重凱'),
 ('PERSON', '柳惠千'),
 ('TIME', '下午'),
 ('QUANTITY', '2000呎'),
 ('QUANTITY', '2000呎'),
 ('PERSON', '朱冠甍'),
 ('DATE', '民國109年'),
 ('PERSON', '許邁德'),
 ('GPE', '英國'),
 ('GPE', '美國'),
 ('PERSON', '許邁德'),
 ('QUANTITY', '1500呎'),
 ('QUANTITY', '150浬')]

## Count top 200 word frequency for each category given a certain NE, e.g., "PERSON"

    {'政治': [('黃重凱', 24),
    ('柳惠千', 13),
    ('喬建中', 12),
    ('徐國勇', 11),
    ('季欽', 8),
    ('許舒博', 7),
    ('游錫堃', 6),

In [18]:
news_links =['aipl', 'ait', 'aspt', 'asc', 'aie', 'amov','ahel','aopl','asoc','acul','acn']
news_categories=['政治','科技','運動','證卷','產經','娛樂','生活','國際','社會','文化','兩岸']

In [19]:
allowedNE=['PERSON']

In [20]:
top_cate_ne_words={} # result we want to get
ne_all=[]
for category in news_categories:
    df_group = df[df.category == category]  # 20 pieces
    ne_group = []

    # concatenate terms in a category
    for ne in df_group.entities:
        ne_group += eval(ne)

    # concatenate all terms
    ne_all += ne_group

    # Get top words by calling ne_word_frequency() function
    topwords = ne_word_frequency( ne_group )
    top_cate_ne_words[category]=topwords

# Process category '全部'
top_ne_all = ne_word_frequency(ne_all)
top_cate_ne_words['全部']=top_ne_all

In [21]:
top_cate_ne_words

{'政治': [('黃重凱', 24),
  ('柳惠千', 13),
  ('喬建中', 12),
  ('徐國勇', 11),
  ('季欽', 8),
  ('許舒博', 7),
  ('游錫堃', 6),
  ('侯富議', 6),
  ('蘇貞昌', 5),
  ('吳釗燮', 4),
  ('許佑格', 4),
  ('范惠君', 4),
  ('歐布萊恩', 4),
  ('陳其邁', 3),
  ('柯文哲', 3),
  ('陳智菡', 3),
  ('黃鼎翔', 3),
  ('王同義', 3),
  ('王美惠', 3),
  ('許邁德', 2)],
 '科技': [('林柏亨', 6),
  ('吳偉仁', 5),
  ('包淳偉', 4),
  ('黃晨瑋', 4),
  ('廖俊智', 4),
  ('波博', 3),
  ('黃文山', 3),
  ('艾偉', 3),
  ('王金燦', 2),
  ('庫克', 2),
  ('曾信超', 2),
  ('波皮斯庫', 2),
  ('王兆璋', 1),
  ('希塔拉姆', 1),
  ('吳宗信', 1),
  ('葉均蔚', 1),
  ('楊勇', 1),
  ('陳信安', 1),
  ('Tim哥', 1),
  ('夏哈', 1)],
 '運動': [('林昀儒', 24),
  ('鄭怡靜', 24),
  ('莊智淵', 17),
  ('陳將双', 12),
  ('潘武雄', 10),
  ('陳建安', 8),
  ('布雷迪', 7),
  ('布魯娜', 6),
  ('賈奈特', 6),
  ('艾倫', 6),
  ('塞爾蒂克', 5),
  ('李恩芯', 5),
  ('王志庭', 4),
  ('施冠宇', 4),
  ('加奇尼', 4),
  ('樂天', 3),
  ('安宰賢', 3),
  ('巴特瑞', 3),
  ('梁家榮', 3),
  ('黃子鵬', 3)],
 '證卷': [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)],
 '產經': [('陳耀祥', 17),
  ('朱澤民', 9),
  ('曾博昇', 6),
  ('杜書全', 5),
  ('蘇松輝', 4),
  ('趙正宇', 3),
  ('林崇燾', 3),
  ('童振源', 3),
  ('郭幸容', 2),
  ('林德福', 2),
  ('吳秉叡', 2),
  ('李昆澤', 2),
  ('丁予嘉', 1),
  ('魏啟林', 1),
  ('佛里奇', 1),
  ('史屈特', 1),
  ('Susannah Streeter）', 1),
  ('林楚茵', 1),
  ('許智傑', 1),
  ('林俊憲', 1)],
 '娛樂': [('唐川', 20),
  ('歸亞蕾', 18),
  ('炎亞綸', 11),
  ('威廉赫特', 10),
  ('莊凱勛', 8),
  ('楊藜', 8),
  ('林暉閔', 7),
  ('納豆', 7),
  ('黃新皓', 6),
  ('珍康萍', 6),
  ('曹格', 6),
  ('侯友宜', 5),
  ('黃子佼', 5),
  ('百白', 4),
  ('孟耿如', 4),
  ('吳慷仁', 4),
  ('林心如', 4),
  ('郭宇宸', 3),
  ('茶金', 3),
  ('温昇豪', 3)],
 '生活': [('陳時中', 13),
  ('彭佳偉', 13),
  ('黃恩鴻', 5),
  ('李宗宏', 3),
  ('江文全', 2),
  ('邱基旭', 2),
  ('蔡佩君', 2),
  ('王力宏', 1),
  ('王惠美', 1),
  ('柯文哲', 1)],
 '國際': [('蘇利文', 5),
  ('楊潔篪', 4),
  ('阿布拉莫維奇', 3),
  ('蒲亭', 3),
  ('米佐塔基斯', 3),
  ('羅傑斯', 3),
  ('波多利雅科', 3),
  ('切爾西', 2),
  ('潘恩', 2),
  ('拉夫羅夫', 2),
  ('阿布杜拉希安', 2),
  ('哈蒂柏札德', 2),
  ('奧德洛', 2),
  ('霍恩', 2),
  ('蕭茲', 2),
  ('布魯塞爾', 1),
  ('Marise Payne）', 1),
  ('米勒', 1),
  ('Alexey Miller）', 1),
  ('穆罕穆德', 1)],
 '社會': [('戴寧', 8),
  ('孫道存', 7),
  ('鄭文燦', 6),
  ('孫芸芸', 4),
  ('孫瑩瑩', 3),
  ('孫智宏', 3),
  ('張女', 2),
  ('陳澤嘉', 2),
  ('吳逸萍', 2),
  ('莊英壽', 2),
  ('李作宏', 2),
  ('馬男', 1),
  ('洪裕翔', 1),
  ('何念慈育', 1),
  ('廖偉志', 1),
  ('廖鎮漢', 1),
  ('王國材', 1),
  ('蘇男', 1),
  ('劉育麟', 1),
  ('陳依芳', 1)],
 '文化': [('吳密察', 15),
  ('平珩', 10),
  ('吳蠻', 7),
  ('潘孟安', 6),
  ('吳思瑤', 5),
  ('楊書涵', 5),
  ('李其叡', 5),
  ('張徐展', 5),
  ('蔡采崴', 4),
  ('陳悅宜', 3),
  ('孫翠鳳', 3),
  ('朱天文', 3),
  ('顏伯駿', 3),
  ('鄭志偉', 3),
  ('朱安麗', 3),
  ('柳美', 3),
  ('大衛．胡斯', 3),
  ('李安', 2),
  ('譚盾', 2),
  ('阿儒瓦苡．篙瑪竿', 2)],
 '兩岸': [('薛達', 6),
  ('林鄭月娥', 5),
  ('劉兆佳', 5),
  ('雷正龍', 3),
  ('趙立堅', 3),
  ('李希', 3),
  ('希魯阿諾夫', 3),
  ('王晟', 3),
  ('布吉敏', 2),
  ('蒲亭', 2),
  ('余永定', 2),
  ('張文宏', 2),
  ('林柏偉', 1),
  ('林伯偉', 1),
  ('黃守應', 1),
  ('王長青', 1),
  ('崔靜麟', 1),
  ('張竹君', 1),
  ('梁萬年', 1),
  ('高拔陞', 1)],
 '全部': [('黃重凱', 24),
  ('林昀儒', 24),
  ('鄭怡靜', 24),
  ('唐川', 20),
  ('歸亞蕾', 18),
  ('莊智淵', 17),
  ('陳耀祥', 17),
  ('吳密察', 15),
  ('柳惠千', 13),
  ('陳時中', 13),
  ('彭佳偉', 13),
  ('喬建中', 12),
  ('陳將双', 12),
  ('徐國勇', 11),
  ('炎亞綸', 11),
  ('潘武雄', 10),
  ('威廉赫特', 10),
  ('平珩', 10),
  ('朱澤民', 9),
  ('季欽', 8)]}

In [22]:
## To conveniently save data using pandas, we should convert dict to list.
list(top_cate_ne_words.items())

[('政治',
  [('黃重凱', 24),
   ('柳惠千', 13),
   ('喬建中', 12),
   ('徐國勇', 11),
   ('季欽', 8),
   ('許舒博', 7),
   ('游錫堃', 6),
   ('侯富議', 6),
   ('蘇貞昌', 5),
   ('吳釗燮', 4),
   ('許佑格', 4),
   ('范惠君', 4),
   ('歐布萊恩', 4),
   ('陳其邁', 3),
   ('柯文哲', 3),
   ('陳智菡', 3),
   ('黃鼎翔', 3),
   ('王同義', 3),
   ('王美惠', 3),
   ('許邁德', 2)]),
 ('科技',
  [('林柏亨', 6),
   ('吳偉仁', 5),
   ('包淳偉', 4),
   ('黃晨瑋', 4),
   ('廖俊智', 4),
   ('波博', 3),
   ('黃文山', 3),
   ('艾偉', 3),
   ('王金燦', 2),
   ('庫克', 2),
   ('曾信超', 2),
   ('波皮斯庫', 2),
   ('王兆璋', 1),
   ('希塔拉姆', 1),
   ('吳宗信', 1),
   ('葉均蔚', 1),
   ('楊勇', 1),
   ('陳信安', 1),
   ('Tim哥', 1),
   ('夏哈', 1)]),
 ('運動',
  [('林昀儒', 24),
   ('鄭怡靜', 24),
   ('莊智淵', 17),
   ('陳將双', 12),
   ('潘武雄', 10),
   ('陳建安', 8),
   ('布雷迪', 7),
   ('布魯娜', 6),
   ('賈奈特', 6),
   ('艾倫', 6),
   ('塞爾蒂克', 5),
   ('李恩芯', 5),
   ('王志庭', 4),
   ('施冠宇', 4),
   ('加奇尼', 4),
   ('樂天', 3),
   ('安宰賢', 3),
   ('巴特瑞', 3),
   ('梁家榮', 3),
   ('黃子鵬', 3)]),
 ('證卷', [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)]),
 ('產經',
  [('陳耀祥', 17),
   ('朱澤民', 9),
   ('曾博昇', 6),
   ('杜書全', 5),
   ('蘇松輝', 4),
   ('趙正宇', 3),
   ('林崇燾', 3),
   ('童振源', 3),
   ('郭幸容', 2),
   ('林德福', 2),
   ('吳秉叡', 2),
   ('李昆澤', 2),
   ('丁予嘉', 1),
   ('魏啟林', 1),
   ('佛里奇', 1),
   ('史屈特', 1),
   ('Susannah Streeter）', 1),
   ('林楚茵', 1),
   ('許智傑', 1),
   ('林俊憲', 1)]),
 ('娛樂',
  [('唐川', 20),
   ('歸亞蕾', 18),
   ('炎亞綸', 11),
   ('威廉赫特', 10),
   ('莊凱勛', 8),
   ('楊藜', 8),
   ('林暉閔', 7),
   ('納豆', 7),
   ('黃新皓', 6),
   ('珍康萍', 6),
   ('曹格', 6),
   ('侯友宜', 5),
   ('黃子佼', 5),
   ('百白', 4),
   ('孟耿如', 4),
   ('吳慷仁', 4),
   ('林心如', 4),
   ('郭宇宸', 3),
   ('茶金', 3),
   ('温昇豪', 3)]),
 ('生活',
  [('陳時中', 13),
   ('彭佳偉', 13),
   ('黃恩鴻', 5),
   ('李宗宏', 3),
   ('江文全', 2),
   ('邱基旭', 2),
   ('蔡佩君', 2),
   ('王力宏', 1),
   ('王惠美', 1),
   ('柯文哲', 1)]),
 ('國際',
  [('蘇利文', 5),
   ('楊潔篪', 4),
   ('阿布拉莫維奇', 3),
   ('蒲亭', 3),
   ('米佐塔基斯', 3),
   ('羅傑斯', 3),
   ('波多利雅科', 3),
   ('切爾西', 2),
   ('潘恩', 2),
   ('拉夫羅夫', 2),
   ('阿布杜拉希安', 2),
   ('哈蒂柏札德', 2),
   ('奧德洛', 2),
   ('霍恩', 2),
   ('蕭茲', 2),
   ('布魯塞爾', 1),
   ('Marise Payne）', 1),
   ('米勒', 1),
   ('Alexey Miller）', 1),
   ('穆罕穆德', 1)]),
 ('社會',
  [('戴寧', 8),
   ('孫道存', 7),
   ('鄭文燦', 6),
   ('孫芸芸', 4),
   ('孫瑩瑩', 3),
   ('孫智宏', 3),
   ('張女', 2),
   ('陳澤嘉', 2),
   ('吳逸萍', 2),
   ('莊英壽', 2),
   ('李作宏', 2),
   ('馬男', 1),
   ('洪裕翔', 1),
   ('何念慈育', 1),
   ('廖偉志', 1),
   ('廖鎮漢', 1),
   ('王國材', 1),
   ('蘇男', 1),
   ('劉育麟', 1),
   ('陳依芳', 1)]),
 ('文化',
  [('吳密察', 15),
   ('平珩', 10),
   ('吳蠻', 7),
   ('潘孟安', 6),
   ('吳思瑤', 5),
   ('楊書涵', 5),
   ('李其叡', 5),
   ('張徐展', 5),
   ('蔡采崴', 4),
   ('陳悅宜', 3),
   ('孫翠鳳', 3),
   ('朱天文', 3),
   ('顏伯駿', 3),
   ('鄭志偉', 3),
   ('朱安麗', 3),
   ('柳美', 3),
   ('大衛．胡斯', 3),
   ('李安', 2),
   ('譚盾', 2),
   ('阿儒瓦苡．篙瑪竿', 2)]),
 ('兩岸',
  [('薛達', 6),
   ('林鄭月娥', 5),
   ('劉兆佳', 5),
   ('雷正龍', 3),
   ('趙立堅', 3),
   ('李希', 3),
   ('希魯阿諾夫', 3),
   ('王晟', 3),
   ('布吉敏', 2),
   ('蒲亭', 2),
   ('余永定', 2),
   ('張文宏', 2),
   ('林柏偉', 1),
   ('林伯偉', 1),
   ('黃守應', 1),
   ('王長青', 1),
   ('崔靜麟', 1),
   ('張竹君', 1),
   ('梁萬年', 1),
   ('高拔陞', 1)]),
 ('全部',
  [('黃重凱', 24),
   ('林昀儒', 24),
   ('鄭怡靜', 24),
   ('唐川', 20),
   ('歸亞蕾', 18),
   ('莊智淵', 17),
   ('陳耀祥', 17),
   ('吳密察', 15),
   ('柳惠千', 13),
   ('陳時中', 13),
   ('彭佳偉', 13),
   ('喬建中', 12),
   ('陳將双', 12),
   ('徐國勇', 11),
   ('炎亞綸', 11),
   ('潘武雄', 10),
   ('威廉赫特', 10),
   ('平珩', 10),
   ('朱澤民', 9),
   ('季欽', 8)])]

## All-in-one function

In [25]:
# All-in-one function
def get_top_ner_words():
    top_cate_ner_words={}
    words_all=[]
    for category in news_categories:
        df_group = df[df.category == category]
        words_group = []

        # concatenate terms in a category
        for row in df_group.entities:
            words_group += eval(row)

        # concatenate all terms
        words_all += words_group

        # Get top words by calling ne_word_frequency() function
        topwords = ne_word_frequency( words_group )
        top_cate_ner_words[category] = topwords

    topwords_all = ne_word_frequency(words_all)
    top_cate_ner_words['全部'] = topwords_all
    
    return list(top_cate_ner_words.items()) # convert to list
    # return top_cate_ne_words

In [26]:
allowedNE=['PERSON']
result = get_top_ner_words()

In [27]:
result

[('政治',
  [('黃重凱', 24),
   ('柳惠千', 13),
   ('喬建中', 12),
   ('徐國勇', 11),
   ('季欽', 8),
   ('許舒博', 7),
   ('游錫堃', 6),
   ('侯富議', 6),
   ('蘇貞昌', 5),
   ('吳釗燮', 4),
   ('許佑格', 4),
   ('范惠君', 4),
   ('歐布萊恩', 4),
   ('陳其邁', 3),
   ('柯文哲', 3),
   ('陳智菡', 3),
   ('黃鼎翔', 3),
   ('王同義', 3),
   ('王美惠', 3),
   ('許邁德', 2)]),
 ('科技',
  [('林柏亨', 6),
   ('吳偉仁', 5),
   ('包淳偉', 4),
   ('黃晨瑋', 4),
   ('廖俊智', 4),
   ('波博', 3),
   ('黃文山', 3),
   ('艾偉', 3),
   ('王金燦', 2),
   ('庫克', 2),
   ('曾信超', 2),
   ('波皮斯庫', 2),
   ('王兆璋', 1),
   ('希塔拉姆', 1),
   ('吳宗信', 1),
   ('葉均蔚', 1),
   ('楊勇', 1),
   ('陳信安', 1),
   ('Tim哥', 1),
   ('夏哈', 1)]),
 ('運動',
  [('林昀儒', 24),
   ('鄭怡靜', 24),
   ('莊智淵', 17),
   ('陳將双', 12),
   ('潘武雄', 10),
   ('陳建安', 8),
   ('布雷迪', 7),
   ('布魯娜', 6),
   ('賈奈特', 6),
   ('艾倫', 6),
   ('塞爾蒂克', 5),
   ('李恩芯', 5),
   ('王志庭', 4),
   ('施冠宇', 4),
   ('加奇尼', 4),
   ('樂天', 3),
   ('安宰賢', 3),
   ('巴特瑞', 3),
   ('梁家榮', 3),
   ('黃子鵬', 3)]),
 ('證卷', [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)]),
 ('產經',
  [('陳耀祥', 17),
   ('朱澤民', 9),
   ('曾博昇', 6),
   ('杜書全', 5),
   ('蘇松輝', 4),
   ('趙正宇', 3),
   ('林崇燾', 3),
   ('童振源', 3),
   ('郭幸容', 2),
   ('林德福', 2),
   ('吳秉叡', 2),
   ('李昆澤', 2),
   ('丁予嘉', 1),
   ('魏啟林', 1),
   ('佛里奇', 1),
   ('史屈特', 1),
   ('Susannah Streeter）', 1),
   ('林楚茵', 1),
   ('許智傑', 1),
   ('林俊憲', 1)]),
 ('娛樂',
  [('唐川', 20),
   ('歸亞蕾', 18),
   ('炎亞綸', 11),
   ('威廉赫特', 10),
   ('莊凱勛', 8),
   ('楊藜', 8),
   ('林暉閔', 7),
   ('納豆', 7),
   ('黃新皓', 6),
   ('珍康萍', 6),
   ('曹格', 6),
   ('侯友宜', 5),
   ('黃子佼', 5),
   ('百白', 4),
   ('孟耿如', 4),
   ('吳慷仁', 4),
   ('林心如', 4),
   ('郭宇宸', 3),
   ('茶金', 3),
   ('温昇豪', 3)]),
 ('生活',
  [('陳時中', 13),
   ('彭佳偉', 13),
   ('黃恩鴻', 5),
   ('李宗宏', 3),
   ('江文全', 2),
   ('邱基旭', 2),
   ('蔡佩君', 2),
   ('王力宏', 1),
   ('王惠美', 1),
   ('柯文哲', 1)]),
 ('國際',
  [('蘇利文', 5),
   ('楊潔篪', 4),
   ('阿布拉莫維奇', 3),
   ('蒲亭', 3),
   ('米佐塔基斯', 3),
   ('羅傑斯', 3),
   ('波多利雅科', 3),
   ('切爾西', 2),
   ('潘恩', 2),
   ('拉夫羅夫', 2),
   ('阿布杜拉希安', 2),
   ('哈蒂柏札德', 2),
   ('奧德洛', 2),
   ('霍恩', 2),
   ('蕭茲', 2),
   ('布魯塞爾', 1),
   ('Marise Payne）', 1),
   ('米勒', 1),
   ('Alexey Miller）', 1),
   ('穆罕穆德', 1)]),
 ('社會',
  [('戴寧', 8),
   ('孫道存', 7),
   ('鄭文燦', 6),
   ('孫芸芸', 4),
   ('孫瑩瑩', 3),
   ('孫智宏', 3),
   ('張女', 2),
   ('陳澤嘉', 2),
   ('吳逸萍', 2),
   ('莊英壽', 2),
   ('李作宏', 2),
   ('馬男', 1),
   ('洪裕翔', 1),
   ('何念慈育', 1),
   ('廖偉志', 1),
   ('廖鎮漢', 1),
   ('王國材', 1),
   ('蘇男', 1),
   ('劉育麟', 1),
   ('陳依芳', 1)]),
 ('文化',
  [('吳密察', 15),
   ('平珩', 10),
   ('吳蠻', 7),
   ('潘孟安', 6),
   ('吳思瑤', 5),
   ('楊書涵', 5),
   ('李其叡', 5),
   ('張徐展', 5),
   ('蔡采崴', 4),
   ('陳悅宜', 3),
   ('孫翠鳳', 3),
   ('朱天文', 3),
   ('顏伯駿', 3),
   ('鄭志偉', 3),
   ('朱安麗', 3),
   ('柳美', 3),
   ('大衛．胡斯', 3),
   ('李安', 2),
   ('譚盾', 2),
   ('阿儒瓦苡．篙瑪竿', 2)]),
 ('兩岸',
  [('薛達', 6),
   ('林鄭月娥', 5),
   ('劉兆佳', 5),
   ('雷正龍', 3),
   ('趙立堅', 3),
   ('李希', 3),
   ('希魯阿諾夫', 3),
   ('王晟', 3),
   ('布吉敏', 2),
   ('蒲亭', 2),
   ('余永定', 2),
   ('張文宏', 2),
   ('林柏偉', 1),
   ('林伯偉', 1),
   ('黃守應', 1),
   ('王長青', 1),
   ('崔靜麟', 1),
   ('張竹君', 1),
   ('梁萬年', 1),
   ('高拔陞', 1)]),
 ('全部',
  [('黃重凱', 24),
   ('林昀儒', 24),
   ('鄭怡靜', 24),
   ('唐川', 20),
   ('歸亞蕾', 18),
   ('莊智淵', 17),
   ('陳耀祥', 17),
   ('吳密察', 15),
   ('柳惠千', 13),
   ('陳時中', 13),
   ('彭佳偉', 13),
   ('喬建中', 12),
   ('陳將双', 12),
   ('徐國勇', 11),
   ('炎亞綸', 11),
   ('潘武雄', 10),
   ('威廉赫特', 10),
   ('平珩', 10),
   ('朱澤民', 9),
   ('季欽', 8)])]

## Popular person

In [28]:
allowedNE=['PERSON']
get_top_ner_words()

[('政治',
  [('黃重凱', 24),
   ('柳惠千', 13),
   ('喬建中', 12),
   ('徐國勇', 11),
   ('季欽', 8),
   ('許舒博', 7),
   ('游錫堃', 6),
   ('侯富議', 6),
   ('蘇貞昌', 5),
   ('吳釗燮', 4),
   ('許佑格', 4),
   ('范惠君', 4),
   ('歐布萊恩', 4),
   ('陳其邁', 3),
   ('柯文哲', 3),
   ('陳智菡', 3),
   ('黃鼎翔', 3),
   ('王同義', 3),
   ('王美惠', 3),
   ('許邁德', 2)]),
 ('科技',
  [('林柏亨', 6),
   ('吳偉仁', 5),
   ('包淳偉', 4),
   ('黃晨瑋', 4),
   ('廖俊智', 4),
   ('波博', 3),
   ('黃文山', 3),
   ('艾偉', 3),
   ('王金燦', 2),
   ('庫克', 2),
   ('曾信超', 2),
   ('波皮斯庫', 2),
   ('王兆璋', 1),
   ('希塔拉姆', 1),
   ('吳宗信', 1),
   ('葉均蔚', 1),
   ('楊勇', 1),
   ('陳信安', 1),
   ('Tim哥', 1),
   ('夏哈', 1)]),
 ('運動',
  [('林昀儒', 24),
   ('鄭怡靜', 24),
   ('莊智淵', 17),
   ('陳將双', 12),
   ('潘武雄', 10),
   ('陳建安', 8),
   ('布雷迪', 7),
   ('布魯娜', 6),
   ('賈奈特', 6),
   ('艾倫', 6),
   ('塞爾蒂克', 5),
   ('李恩芯', 5),
   ('王志庭', 4),
   ('施冠宇', 4),
   ('加奇尼', 4),
   ('樂天', 3),
   ('安宰賢', 3),
   ('巴特瑞', 3),
   ('梁家榮', 3),
   ('黃子鵬', 3)]),
 ('證卷', [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)]),
 ('產經',
  [('陳耀祥', 17),
   ('朱澤民', 9),
   ('曾博昇', 6),
   ('杜書全', 5),
   ('蘇松輝', 4),
   ('趙正宇', 3),
   ('林崇燾', 3),
   ('童振源', 3),
   ('郭幸容', 2),
   ('林德福', 2),
   ('吳秉叡', 2),
   ('李昆澤', 2),
   ('丁予嘉', 1),
   ('魏啟林', 1),
   ('佛里奇', 1),
   ('史屈特', 1),
   ('Susannah Streeter）', 1),
   ('林楚茵', 1),
   ('許智傑', 1),
   ('林俊憲', 1)]),
 ('娛樂',
  [('唐川', 20),
   ('歸亞蕾', 18),
   ('炎亞綸', 11),
   ('威廉赫特', 10),
   ('莊凱勛', 8),
   ('楊藜', 8),
   ('林暉閔', 7),
   ('納豆', 7),
   ('黃新皓', 6),
   ('珍康萍', 6),
   ('曹格', 6),
   ('侯友宜', 5),
   ('黃子佼', 5),
   ('百白', 4),
   ('孟耿如', 4),
   ('吳慷仁', 4),
   ('林心如', 4),
   ('郭宇宸', 3),
   ('茶金', 3),
   ('温昇豪', 3)]),
 ('生活',
  [('陳時中', 13),
   ('彭佳偉', 13),
   ('黃恩鴻', 5),
   ('李宗宏', 3),
   ('江文全', 2),
   ('邱基旭', 2),
   ('蔡佩君', 2),
   ('王力宏', 1),
   ('王惠美', 1),
   ('柯文哲', 1)]),
 ('國際',
  [('蘇利文', 5),
   ('楊潔篪', 4),
   ('阿布拉莫維奇', 3),
   ('蒲亭', 3),
   ('米佐塔基斯', 3),
   ('羅傑斯', 3),
   ('波多利雅科', 3),
   ('切爾西', 2),
   ('潘恩', 2),
   ('拉夫羅夫', 2),
   ('阿布杜拉希安', 2),
   ('哈蒂柏札德', 2),
   ('奧德洛', 2),
   ('霍恩', 2),
   ('蕭茲', 2),
   ('布魯塞爾', 1),
   ('Marise Payne）', 1),
   ('米勒', 1),
   ('Alexey Miller）', 1),
   ('穆罕穆德', 1)]),
 ('社會',
  [('戴寧', 8),
   ('孫道存', 7),
   ('鄭文燦', 6),
   ('孫芸芸', 4),
   ('孫瑩瑩', 3),
   ('孫智宏', 3),
   ('張女', 2),
   ('陳澤嘉', 2),
   ('吳逸萍', 2),
   ('莊英壽', 2),
   ('李作宏', 2),
   ('馬男', 1),
   ('洪裕翔', 1),
   ('何念慈育', 1),
   ('廖偉志', 1),
   ('廖鎮漢', 1),
   ('王國材', 1),
   ('蘇男', 1),
   ('劉育麟', 1),
   ('陳依芳', 1)]),
 ('文化',
  [('吳密察', 15),
   ('平珩', 10),
   ('吳蠻', 7),
   ('潘孟安', 6),
   ('吳思瑤', 5),
   ('楊書涵', 5),
   ('李其叡', 5),
   ('張徐展', 5),
   ('蔡采崴', 4),
   ('陳悅宜', 3),
   ('孫翠鳳', 3),
   ('朱天文', 3),
   ('顏伯駿', 3),
   ('鄭志偉', 3),
   ('朱安麗', 3),
   ('柳美', 3),
   ('大衛．胡斯', 3),
   ('李安', 2),
   ('譚盾', 2),
   ('阿儒瓦苡．篙瑪竿', 2)]),
 ('兩岸',
  [('薛達', 6),
   ('林鄭月娥', 5),
   ('劉兆佳', 5),
   ('雷正龍', 3),
   ('趙立堅', 3),
   ('李希', 3),
   ('希魯阿諾夫', 3),
   ('王晟', 3),
   ('布吉敏', 2),
   ('蒲亭', 2),
   ('余永定', 2),
   ('張文宏', 2),
   ('林柏偉', 1),
   ('林伯偉', 1),
   ('黃守應', 1),
   ('王長青', 1),
   ('崔靜麟', 1),
   ('張竹君', 1),
   ('梁萬年', 1),
   ('高拔陞', 1)]),
 ('全部',
  [('黃重凱', 24),
   ('林昀儒', 24),
   ('鄭怡靜', 24),
   ('唐川', 20),
   ('歸亞蕾', 18),
   ('莊智淵', 17),
   ('陳耀祥', 17),
   ('吳密察', 15),
   ('柳惠千', 13),
   ('陳時中', 13),
   ('彭佳偉', 13),
   ('喬建中', 12),
   ('陳將双', 12),
   ('徐國勇', 11),
   ('炎亞綸', 11),
   ('潘武雄', 10),
   ('威廉赫特', 10),
   ('平珩', 10),
   ('朱澤民', 9),
   ('季欽', 8)])]

## Save top-200 hot persons for future usage

We have already done this in our previous app.

In [29]:
import pandas as pd

In [30]:
allowedNE=['PERSON']
hotPersons = get_top_ner_words()

In [31]:
hotPersons

[('政治',
  [('黃重凱', 24),
   ('柳惠千', 13),
   ('喬建中', 12),
   ('徐國勇', 11),
   ('季欽', 8),
   ('許舒博', 7),
   ('游錫堃', 6),
   ('侯富議', 6),
   ('蘇貞昌', 5),
   ('吳釗燮', 4),
   ('許佑格', 4),
   ('范惠君', 4),
   ('歐布萊恩', 4),
   ('陳其邁', 3),
   ('柯文哲', 3),
   ('陳智菡', 3),
   ('黃鼎翔', 3),
   ('王同義', 3),
   ('王美惠', 3),
   ('許邁德', 2)]),
 ('科技',
  [('林柏亨', 6),
   ('吳偉仁', 5),
   ('包淳偉', 4),
   ('黃晨瑋', 4),
   ('廖俊智', 4),
   ('波博', 3),
   ('黃文山', 3),
   ('艾偉', 3),
   ('王金燦', 2),
   ('庫克', 2),
   ('曾信超', 2),
   ('波皮斯庫', 2),
   ('王兆璋', 1),
   ('希塔拉姆', 1),
   ('吳宗信', 1),
   ('葉均蔚', 1),
   ('楊勇', 1),
   ('陳信安', 1),
   ('Tim哥', 1),
   ('夏哈', 1)]),
 ('運動',
  [('林昀儒', 24),
   ('鄭怡靜', 24),
   ('莊智淵', 17),
   ('陳將双', 12),
   ('潘武雄', 10),
   ('陳建安', 8),
   ('布雷迪', 7),
   ('布魯娜', 6),
   ('賈奈特', 6),
   ('艾倫', 6),
   ('塞爾蒂克', 5),
   ('李恩芯', 5),
   ('王志庭', 4),
   ('施冠宇', 4),
   ('加奇尼', 4),
   ('樂天', 3),
   ('安宰賢', 3),
   ('巴特瑞', 3),
   ('梁家榮', 3),
   ('黃子鵬', 3)]),
 ('證卷', [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)]),
 ('產經',
  [('陳耀祥', 17),
   ('朱澤民', 9),
   ('曾博昇', 6),
   ('杜書全', 5),
   ('蘇松輝', 4),
   ('趙正宇', 3),
   ('林崇燾', 3),
   ('童振源', 3),
   ('郭幸容', 2),
   ('林德福', 2),
   ('吳秉叡', 2),
   ('李昆澤', 2),
   ('丁予嘉', 1),
   ('魏啟林', 1),
   ('佛里奇', 1),
   ('史屈特', 1),
   ('Susannah Streeter）', 1),
   ('林楚茵', 1),
   ('許智傑', 1),
   ('林俊憲', 1)]),
 ('娛樂',
  [('唐川', 20),
   ('歸亞蕾', 18),
   ('炎亞綸', 11),
   ('威廉赫特', 10),
   ('莊凱勛', 8),
   ('楊藜', 8),
   ('林暉閔', 7),
   ('納豆', 7),
   ('黃新皓', 6),
   ('珍康萍', 6),
   ('曹格', 6),
   ('侯友宜', 5),
   ('黃子佼', 5),
   ('百白', 4),
   ('孟耿如', 4),
   ('吳慷仁', 4),
   ('林心如', 4),
   ('郭宇宸', 3),
   ('茶金', 3),
   ('温昇豪', 3)]),
 ('生活',
  [('陳時中', 13),
   ('彭佳偉', 13),
   ('黃恩鴻', 5),
   ('李宗宏', 3),
   ('江文全', 2),
   ('邱基旭', 2),
   ('蔡佩君', 2),
   ('王力宏', 1),
   ('王惠美', 1),
   ('柯文哲', 1)]),
 ('國際',
  [('蘇利文', 5),
   ('楊潔篪', 4),
   ('阿布拉莫維奇', 3),
   ('蒲亭', 3),
   ('米佐塔基斯', 3),
   ('羅傑斯', 3),
   ('波多利雅科', 3),
   ('切爾西', 2),
   ('潘恩', 2),
   ('拉夫羅夫', 2),
   ('阿布杜拉希安', 2),
   ('哈蒂柏札德', 2),
   ('奧德洛', 2),
   ('霍恩', 2),
   ('蕭茲', 2),
   ('布魯塞爾', 1),
   ('Marise Payne）', 1),
   ('米勒', 1),
   ('Alexey Miller）', 1),
   ('穆罕穆德', 1)]),
 ('社會',
  [('戴寧', 8),
   ('孫道存', 7),
   ('鄭文燦', 6),
   ('孫芸芸', 4),
   ('孫瑩瑩', 3),
   ('孫智宏', 3),
   ('張女', 2),
   ('陳澤嘉', 2),
   ('吳逸萍', 2),
   ('莊英壽', 2),
   ('李作宏', 2),
   ('馬男', 1),
   ('洪裕翔', 1),
   ('何念慈育', 1),
   ('廖偉志', 1),
   ('廖鎮漢', 1),
   ('王國材', 1),
   ('蘇男', 1),
   ('劉育麟', 1),
   ('陳依芳', 1)]),
 ('文化',
  [('吳密察', 15),
   ('平珩', 10),
   ('吳蠻', 7),
   ('潘孟安', 6),
   ('吳思瑤', 5),
   ('楊書涵', 5),
   ('李其叡', 5),
   ('張徐展', 5),
   ('蔡采崴', 4),
   ('陳悅宜', 3),
   ('孫翠鳳', 3),
   ('朱天文', 3),
   ('顏伯駿', 3),
   ('鄭志偉', 3),
   ('朱安麗', 3),
   ('柳美', 3),
   ('大衛．胡斯', 3),
   ('李安', 2),
   ('譚盾', 2),
   ('阿儒瓦苡．篙瑪竿', 2)]),
 ('兩岸',
  [('薛達', 6),
   ('林鄭月娥', 5),
   ('劉兆佳', 5),
   ('雷正龍', 3),
   ('趙立堅', 3),
   ('李希', 3),
   ('希魯阿諾夫', 3),
   ('王晟', 3),
   ('布吉敏', 2),
   ('蒲亭', 2),
   ('余永定', 2),
   ('張文宏', 2),
   ('林柏偉', 1),
   ('林伯偉', 1),
   ('黃守應', 1),
   ('王長青', 1),
   ('崔靜麟', 1),
   ('張竹君', 1),
   ('梁萬年', 1),
   ('高拔陞', 1)]),
 ('全部',
  [('黃重凱', 24),
   ('林昀儒', 24),
   ('鄭怡靜', 24),
   ('唐川', 20),
   ('歸亞蕾', 18),
   ('莊智淵', 17),
   ('陳耀祥', 17),
   ('吳密察', 15),
   ('柳惠千', 13),
   ('陳時中', 13),
   ('彭佳偉', 13),
   ('喬建中', 12),
   ('陳將双', 12),
   ('徐國勇', 11),
   ('炎亞綸', 11),
   ('潘武雄', 10),
   ('威廉赫特', 10),
   ('平珩', 10),
   ('朱澤民', 9),
   ('季欽', 8)])]

In [32]:
df_hotPersons = pd.DataFrame(hotPersons, columns = ['category','top_keys'])

In [33]:
df_hotPersons

   category                                           top_keys
0        政治  [(黃重凱, 24), (柳惠千, 13), (喬建中, 12), (徐國勇, 11), (...
1        科技  [(林柏亨, 6), (吳偉仁, 5), (包淳偉, 4), (黃晨瑋, 4), (廖俊智,...
2        運動  [(林昀儒, 24), (鄭怡靜, 24), (莊智淵, 17), (陳將双, 12), (...
3        證卷           [(林耕億, 3), (葉獻文, 2), (李昌鴻, 2), (黃水可, 1)]
4        產經  [(陳耀祥, 17), (朱澤民, 9), (曾博昇, 6), (杜書全, 5), (蘇松輝...
5        娛樂  [(唐川, 20), (歸亞蕾, 18), (炎亞綸, 11), (威廉赫特, 10), (...
6        生活  [(陳時中, 13), (彭佳偉, 13), (黃恩鴻, 5), (李宗宏, 3), (江文...
7        國際  [(蘇利文, 5), (楊潔篪, 4), (阿布拉莫維奇, 3), (蒲亭, 3), (米佐...
8        社會  [(戴寧, 8), (孫道存, 7), (鄭文燦, 6), (孫芸芸, 4), (孫瑩瑩, ...
9        文化  [(吳密察, 15), (平珩, 10), (吳蠻, 7), (潘孟安, 6), (吳思瑤,...
10       兩岸  [(薛達, 6), (林鄭月娥, 5), (劉兆佳, 5), (雷正龍, 3), (趙立堅,...
11       全部  [(黃重凱, 24), (林昀儒, 24), (鄭怡靜, 24), (唐川, 20), (歸...

In [35]:
# df_hotPersons.to_csv('news_top_person_by_category_via_ner.csv', sep=',', index=False) # 與上周的任務相同

## Popular products

In [34]:
allowedNE=['PRODUCT']
get_top_ner_words()

[('政治',
  [('2000', 3),
   ('殲16戰機', 2),
   ('2017', 1),
   ('殲10戰機', 1),
   ('ADIZ', 1),
   ('GBU-10', 1),
   ('GBU-12', 1),
   ('Mk 82', 1),
   ('F-16', 1),
   ('2058', 1)]),
 ('科技',
  [('iPhone SE', 8),
   ('iPad Air', 8),
   ('M1 Ultra', 6),
   ('iPhone', 5),
   ('Mac Studio', 5),
   ('LINE', 5),
   ('SXSW 2022', 4),
   ('M1 Max', 4),
   ('Touch ID', 4),
   ('iPhone 13', 4),
   ('5G', 3),
   ('新iPad Air', 3),
   ('iOS 15.4', 3),
   ('Face ID', 3),
   ('A15', 3),
   ('Google', 3),
   ('HTC VIVE', 2),
   ('MyndVR', 2),
   ('Daisy', 2),
   ('Studio Display', 2)]),
 ('運動', []),
 ('證卷',
  [('波音777-300ER客機', 1), ('777F貨機', 1), ('777-300ER', 1), ('COVID-19', 1)]),
 ('產經', [('COVID-19', 2)]),
 ('娛樂', [('KKTV', 1)]),
 ('生活', []),
 ('國際',
  [('F-35', 3),
   ('F-18', 2),
   ('Lockh', 1),
   ('Tornado）', 1),
   ('Annegr', 1),
   ('波音', 1),
   ('龍捲風戰機', 1),
   ('龍捲風', 1)]),
 ('社會', []),
 ('文化', []),
 ('兩岸', [('COVID-19', 1)]),
 ('全部',
  [('iPhone SE', 8),
   ('iPad Air', 8),
   ('M1 Ultra', 6),
   ('iPhone', 5),
   ('Mac Studio', 5),
   ('LINE', 5),
   ('SXSW 2022', 4),
   ('M1 Max', 4),
   ('Touch ID', 4),
   ('iPhone 13', 4),
   ('COVID-19', 4),
   ('2000', 3),
   ('5G', 3),
   ('新iPad Air', 3),
   ('iOS 15.4', 3),
   ('Face ID', 3),
   ('A15', 3),
   ('Google', 3),
   ('F-35', 3),
   ('殲16戰機', 2)])]

In [35]:
allowedNE=['LAW']
get_top_ner_words()

[('政治', []),
 ('科技', [('LINE', 1)]),
 ('運動', []),
 ('證卷', []),
 ('產經', []),
 ('娛樂', []),
 ('生活', []),
 ('國際', [('國安法', 2), ('北約憲章第5條', 1)]),
 ('社會', []),
 ('文化', []),
 ('兩岸', [('香港國安法', 1), ('外國公司問責法', 1)]),
 ('全部',
  [('國安法', 2), ('LINE', 1), ('北約憲章第5條', 1), ('香港國安法', 1), ('外國公司問責法', 1)])]

## Geting your popular X

## We can get top 200 word frequecy for each news categroy by using "entities" column.

We can get top 200 word frequency for each category, if we includes all NEs.

We have done the same task in the app_top_keyword. We count the top keywords from "pos" column.

In [36]:
allowedNE=['EVENT','FAC','GPE','LANGUAGE','LAW','LOC','NORP','ORG','PERSON','PRODUCT','WORK_OF_ART']
top_group_ner_words = get_top_ner_words()

In [37]:
top_group_ner_words

[('政治',
  [('台灣', 25),
   ('黃重凱', 24),
   ('外交部', 16),
   ('柳惠千', 13),
   ('立法院', 13),
   ('喬建中', 12),
   ('烏克蘭', 11),
   ('徐國勇', 11),
   ('台東', 10),
   ('監察院', 9),
   ('法國', 8),
   ('行政院', 8),
   ('季欽', 8),
   ('台東志航基地', 8),
   ('國防部', 7),
   ('許舒博', 7),
   ('游錫堃', 6),
   ('台東馬偕醫院', 6),
   ('侯富議', 6),
   ('內政部', 6)]),
 ('科技',
  [('台灣', 24),
   ('蘋果', 20),
   ('俄羅斯', 13),
   ('iPhone SE', 8),
   ('iPad Air', 8),
   ('LINE', 8),
   ('烏克蘭', 7),
   ('南極', 7),
   ('中研院', 6),
   ('M1 Ultra', 6),
   ('林柏亨', 6),
   ('印度', 5),
   ('中國', 5),
   ('iPhone', 5),
   ('吳偉仁', 5),
   ('月球', 5),
   ('Mac Studio', 5),
   ('德國', 5),
   ('SXSW 2022', 4),
   ('美國', 4)]),
 ('運動',
  [('林昀儒', 24),
   ('鄭怡靜', 24),
   ('莊智淵', 17),
   ('台灣', 13),
   ('陳將双', 12),
   ('獅隊', 11),
   ('新加坡', 10),
   ('潘武雄', 10),
   ('桃猿隊', 9),
   ('陳建安', 8),
   ('布雷迪', 7),
   ('巴西', 6),
   ('布魯娜', 6),
   ('兄弟', 6),
   ('賈奈特', 6),
   ('艾倫', 6),
   ('中央社', 5),
   ('印度', 5),
   ('桃猿', 5),
   ('施冠宇', 5)]),
 ('證卷',
  [('台灣', 18),
   ('台股', 15),
   ('陽明', 9),
   ('揚弈科技', 8),
   ('友通', 7),
   ('長榮航空', 6),
   ('祥碩', 6),
   ('中環', 6),
   ('陽明海運', 5),
   ('長榮航', 5),
   ('華研', 5),
   ('敬鵬', 5),
   ('長榮', 4),
   ('台北', 4),
   ('台積電', 4),
   ('友達', 4),
   ('元晶', 4),
   ('林耕億', 3),
   ('聯電', 3),
   ('群創', 3)]),
 ('產經',
  [('台灣', 22),
   ('陳耀祥', 17),
   ('中國', 12),
   ('歐盟', 12),
   ('歐洲', 12),
   ('台銀', 10),
   ('國票金', 9),
   ('金管會', 9),
   ('朱澤民', 9),
   ('華碩', 8),
   ('偉詮電', 8),
   ('俄羅斯', 7),
   ('烏克蘭', 6),
   ('曾博昇', 6),
   ('杜書全', 5),
   ('俄烏戰爭', 5),
   ('民進黨', 5),
   ('永裕', 5),
   ('台商', 5),
   ('蘇松輝', 4)]),
 ('娛樂',
  [('唐川', 20),
   ('歸亞蕾', 20),
   ('台灣', 11),
   ('美國', 11),
   ('炎亞綸', 11),
   ('英國', 10),
   ('威廉赫特', 10),
   ('莊凱勛', 8),
   ('楊藜', 8),
   ('林暉閔', 7),
   ('納豆', 7),
   ('黃新皓', 6),
   ('珍康萍', 6),
   ('香港', 6),
   ('曹格', 6),
   ('侯友宜', 5),
   ('犬山記', 5),
   ('黃子佼', 5),
   ('多曼尼製作公司', 5),
   ('多曼尼', 5)]),
 ('生活',
  [('陳時中', 13),
   ('彭佳偉', 13),
   ('台電', 9),
   ('台中一中', 6),
   ('黃恩鴻', 5),
   ('台灣', 4),
   ('台彩', 3),
   ('桃機公司', 3),
   ('中央社', 3),
   ('台北', 3),
   ('農委會', 3),
   ('北捷', 3),
   ('恭醫院', 3),
   ('李宗宏', 3),
   ('雲頂集團', 3),
   ('中央流行疫情指揮中心', 2),
   ('威力彩', 2),
   ('中央氣象局', 2),
   ('彰化縣', 2),
   ('中一中', 2)]),
 ('國際',
  [('俄國', 24),
   ('俄羅斯', 23),
   ('烏克蘭', 16),
   ('香港', 14),
   ('印度', 12),
   ('台灣', 12),
   ('美國', 10),
   ('德國', 10),
   ('伊朗', 9),
   ('莫斯科', 9),
   ('中國', 9),
   ('香港觀察', 8),
   ('路透社', 7),
   ('挪威', 7),
   ('日本', 7),
   ('歐盟', 6),
   ('蘇利文', 5),
   ('澳洲', 4),
   ('法新社', 4),
   ('楊潔篪', 4)]),
 ('社會',
  [('消防局', 9),
   ('戴寧', 8),
   ('環保局', 8),
   ('孫道存', 7),
   ('台南高分院', 6),
   ('桃機公司', 6),
   ('鄭文燦', 6),
   ('嘉義地院', 5),
   ('家樂福', 5),
   ('台灣', 5),
   ('中央社', 4),
   ('孫芸芸', 4),
   ('國稅局', 4),
   ('新北分署', 4),
   ('高雄市區監理所', 4),
   ('孫瑩瑩', 3),
   ('孫智宏', 3),
   ('花蓮分署', 3),
   ('台電', 3),
   ('義大利', 3)]),
 ('文化',
  [('台灣', 36),
   ('故宮', 20),
   ('吳密察', 15),
   ('高雄', 14),
   ('平珩', 10),
   ('烏克蘭', 7),
   ('德國', 7),
   ('吳蠻', 7),
   ('巴雀弦樂團', 7),
   ('文化部', 6),
   ('明華園', 6),
   ('潘孟安', 6),
   ('屏東', 6),
   ('吳思瑤', 5),
   ('美國', 5),
   ('楊書涵', 5),
   ('柏林', 5),
   ('李其叡', 5),
   ('張徐展', 5),
   ('雪梨雙年展', 4)]),
 ('兩岸',
  [('中國', 91),
   ('香港', 69),
   ('俄羅斯', 22),
   ('北京', 19),
   ('深圳', 18),
   ('東莞', 16),
   ('港府', 15),
   ('美國', 13),
   ('台灣', 10),
   ('東莞市', 8),
   ('美方', 7),
   ('薛達', 6),
   ('林鄭月娥', 5),
   ('劉兆佳', 5),
   ('廣東', 3),
   ('雷正龍', 3),
   ('上海', 3),
   ('中國外交部', 3),
   ('趙立堅', 3),
   ('廣東省', 3)]),
 ('全部',
  [('台灣', 180),
   ('中國', 132),
   ('香港', 90),
   ('俄羅斯', 70),
   ('烏克蘭', 55),
   ('美國', 49),
   ('中央社', 30),
   ('俄國', 28),
   ('德國', 27),
   ('黃重凱', 24),
   ('林昀儒', 24),
   ('鄭怡靜', 24),
   ('深圳', 24),
   ('北京', 23),
   ('印度', 22),
   ('高雄', 21),
   ('蘋果', 20),
   ('唐川', 20),
   ('歸亞蕾', 20),
   ('故宮', 20)])]

In [38]:
df_top_group_ner_words = pd.DataFrame(top_group_ner_words, columns = ['category','top_keys'])

In [39]:
df_top_group_ner_words

   category                                           top_keys
0        政治  [(台灣, 25), (黃重凱, 24), (外交部, 16), (柳惠千, 13), (立...
1        科技  [(台灣, 24), (蘋果, 20), (俄羅斯, 13), (iPhone SE, 8)...
2        運動  [(林昀儒, 24), (鄭怡靜, 24), (莊智淵, 17), (台灣, 13), (陳...
3        證卷  [(台灣, 18), (台股, 15), (陽明, 9), (揚弈科技, 8), (友通, ...
4        產經  [(台灣, 22), (陳耀祥, 17), (中國, 12), (歐盟, 12), (歐洲,...
5        娛樂  [(唐川, 20), (歸亞蕾, 20), (台灣, 11), (美國, 11), (炎亞綸...
6        生活  [(陳時中, 13), (彭佳偉, 13), (台電, 9), (台中一中, 6), (黃恩...
7        國際  [(俄國, 24), (俄羅斯, 23), (烏克蘭, 16), (香港, 14), (印度...
8        社會  [(消防局, 9), (戴寧, 8), (環保局, 8), (孫道存, 7), (台南高分院...
9        文化  [(台灣, 36), (故宮, 20), (吳密察, 15), (高雄, 14), (平珩,...
10       兩岸  [(中國, 91), (香港, 69), (俄羅斯, 22), (北京, 19), (深圳,...
11       全部  [(台灣, 180), (中國, 132), (香港, 90), (俄羅斯, 70), (烏...

In [42]:
# df_top_group_ner_words.to_csv('news_topkey_with_category_via_ner.csv', sep=',', index=False) # 與第一次的Django任務相同

# Count top-200 hot keywords for each NE name

count keywords for each NE name

Name	Description
CARDINAL	數字
DATE	日期
EVENT	事件
FAC	設施
GPE	行政區
LANGUAGE	語言
LAW	法律
LOC	地理區
MONEY	金錢
NORP	民族、宗教、政治團體
ORDINAL	序數
ORG	組織
PERCENT	百分比率
PERSON	人物
PRODUCT	產品
QUANTITY	數量
TIME	時間
WORK_OF_ART	作品

In [40]:
# NER詞性
NE_Name=['CARDINAL','DATE','EVENT','FAC','GPE','LANGUAGE','LAW','LOC','MONEY','NORP','ORDINAL','ORG','PERCENT','PERSON','PRODUCT','QUANTITY','TIME','WORK_OF_ART']

In [41]:
%%time
# It takes time, at least 2 minitues.
top_word_NE=[]
for ne_name in NE_Name:
    allowedNE= [ne_name]
    topwords = get_top_ner_words()
    top_word_NE.append([ne_name, topwords])

CPU times: total: 2.16 s
Wall time: 2.4 s

In [42]:
top_word_NE

[['CARDINAL',
  [('政治',
    [('2000', 7),
     ('4000', 2),
     ('13', 2),
     ('54', 2),
     ('1730', 1),
     ('20', 1),
     ('38', 1),
     ('16', 1),
     ('39', 1),
     ('30', 1),
     ('90', 1),
     ('10萬', 1),
     ('12', 1),
     ('11', 1),
     ('41', 1),
     ('2017', 1),
     ('2036', 1)]),
   ('科技',
    [('4.0', 4),
     ('1200萬', 3),
     ('23', 2),
     ('120萬', 2),
     ('之一', 2),
     ('64', 2),
     ('25', 1),
     ('200', 1),
     ('15', 1),
     ('1萬', 1),
     ('2.5', 1),
     ('4000', 1),
     ('20', 1),
     ('60', 1),
     ('5G', 1),
     ('30', 1),
     ('33', 1),
     ('1176', 1),
     ('一半', 1),
     ('19', 1)]),
   ('運動',
    [('16', 19),
     ('11', 19),
     ('10', 5),
     ('32', 3),
     ('22', 2),
     ('57', 2),
     ('12', 2),
     ('7萬', 1),
     ('103萬', 1),
     ('31', 1),
     ('91', 1),
     ('128', 1),
     ('84', 1),
     ('92', 1),
     ('95', 1),
     ('四分', 1),
     ('20', 1),
     ('48', 1),
     ('18', 1),
     ('21', 1)]),
   ('證卷',
    [('50', 6),
     ('10', 4),
     ('十名', 2),
     ('505', 1),
     ('1287', 1),
     ('一半', 1),
     ('11', 1),
     ('29', 1),
     ('2名', 1),
     ('6.32倍', 1),
     ('1.85', 1),
     ('12.7倍', 1),
     ('13倍', 1),
     ('1.9倍', 1),
     ('1452萬4527', 1),
     ('633萬7576', 1),
     ('486', 1),
     ('367', 1),
     ('130', 1),
     ('5名', 1)]),
   ('產經',
    [('上億', 2),
     ('24', 1),
     ('2.0', 1),
     ('21', 1),
     ('2400萬', 1),
     ('60多', 1),
     ('66', 1),
     ('50萬顆', 1),
     ('147', 1),
     ('4萬多', 1),
     ('2600', 1),
     ('4000', 1)]),
   ('娛樂', [('200多', 2), ('2000萬', 1), ('三百', 1), ('10幾', 1)]),
   ('生活',
    [('17', 6),
     ('14', 5),
     ('23', 4),
     ('04', 4),
     ('13', 3),
     ('12', 3),
     ('2400', 3),
     ('2019', 2),
     ('19', 2),
     ('10', 2),
     ('16', 2),
     ('663', 2),
     ('20', 2),
     ('18', 2),
     ('07', 2),
     ('06', 2),
     ('11', 2),
     ('02', 2),
     ('08', 2),
     ('15', 2)]),
   ('國際',
    [('3萬', 1),
     ('200', 1),
     ('50', 1),
     ('之一', 1),
     ('4836', 1),
     ('5000', 1),
     ('500', 1),
     ('8631.9', 1),
     ('64', 1),
     ('17', 1),
     ('35', 1)]),
   ('社會',
    [('360萬', 2),
     ('68', 2),
     ('17', 1),
     ('50', 1),
     ('10', 1),
     ('200餘', 1),
     ('千萬', 1),
     ('一半', 1),
     ('44', 1),
     ('百餘', 1),
     ('317', 1),
     ('18', 1),
     ('43', 1)]),
   ('文化',
    [('10', 3),
     ('130', 1),
     ('30', 1),
     ('上萬', 1),
     ('15', 1),
     ('之一', 1),
     ('25', 1),
     ('100', 1),
     ('20', 1),
     ('1億', 1),
     ('70萬', 1),
     ('1萬多', 1),
     ('69萬多', 1),
     ('一半', 1),
     ('200多', 1),
     ('500', 1)]),
   ('兩岸',
    [('2019', 3),
     ('75', 3),
     ('300', 3),
     ('4000', 2),
     ('10', 2),
     ('100萬', 2),
     ('119', 2),
     ('約1000', 2),
     ('3.2萬', 2),
     ('1萬', 2),
     ('3993', 2),
     ('1337', 2),
     ('895', 2),
     ('2266', 2),
     ('1萬餘', 1),
     ('27', 1),
     ('31個', 1),
     ('19', 1),
     ('1萬4868', 1),
     ('72萬', 1)]),
   ('全部',
    [('16', 23),
     ('11', 23),
     ('10', 17),
     ('2000', 8),
     ('50', 8),
     ('17', 8),
     ('4000', 6),
     ('20', 6),
     ('12', 6),
     ('23', 6),
     ('13', 5),
     ('之一', 5),
     ('2019', 5),
     ('14', 5),
     ('30', 4),
     ('15', 4),
     ('1萬', 4),
     ('一半', 4),
     ('19', 4),
     ('4.0', 4)])]],
 ['DATE',
  [('政治',
    [('今天', 35),
     ('12天', 2),
     ('5月', 2),
     ('同年12月', 2),
     ('4個月', 2),
     ('一年', 2),
     ('7日', 1),
     ('18日', 1),
     ('6個月', 1),
     ('3月18日', 1),
     ('民國109年', 1),
     ('11日', 1),
     ('近年', 1),
     ('20年', 1),
     ('當年', 1),
     ('民國109年9月17日', 1),
     ('110年10月1日', 1),
     ('同年10月2日', 1),
     ('10月3日', 1),
     ('10月4日', 1)]),
   ('科技',
    [('今天', 27),
     ('18日', 6),
     ('1月', 4),
     ('11日', 4),
     ('春季', 4),
     ('去年4月', 2),
     ('2016年', 2),
     ('去年10月', 2),
     ('2030年', 2),
     ('2023年底', 2),
     ('今年', 2),
     ('下週', 2),
     ('多年來', 2),
     ('1年', 2),
     ('3月23日', 2),
     ('2020年12月', 1),
     ('過去一年', 1),
     ('上個月', 1),
     ('9日', 1),
     ('2018年4月', 1)]),
   ('運動',
    [('今天', 47),
     ('今年', 9),
     ('昨天', 8),
     ('去年', 4),
     ('2年', 4),
     ('7日至20日', 4),
     ('一年', 4),
     ('40歲', 3),
     ('上個月', 2),
     ('一日', 2),
     ('2008年', 2),
     ('冬季', 2),
     ('11日', 1),
     ('27日', 1),
     ('105年', 1),
     ('10年', 1),
     ('109年', 1),
     ('去年11月底', 1),
     ('近4個月', 1),
     ('年底', 1)]),
   ('證卷',
    [('今天', 36),
     ('去年', 24),
     ('今年', 12),
     ('2021年', 11),
     ('3月', 11),
     ('2020年', 7),
     ('2月', 6),
     ('前2月', 4),
     ('4月', 4),
     ('10年', 3),
     ('本週', 3),
     ('2022年', 3),
     ('12個月', 2),
     ('去年10月', 2),
     ('14日', 2),
     ('今年前2月', 2),
     ('2019年', 2),
     ('2021年度', 2),
     ('2個月', 2),
     ('明天', 1)]),
   ('產經',
    [('今天', 30),
     ('今年', 23),
     ('去年', 16),
     ('前年', 4),
     ('上週', 2),
     ('3月15日', 2),
     ('3月底', 2),
     ('2021年', 2),
     ('第1季', 2),
     ('農曆年', 2),
     ('全年', 1),
     ('這2年', 1),
     ('去年12月', 1),
     ('今年3月1日', 1),
     ('7個', 1),
     ('2017年至今', 1),
     ('2019年', 1),
     ('2019', 1),
     ('11日', 1),
     ('今年一月', 1)]),
   ('娛樂',
    [('今天', 26),
     ('昨天', 7),
     ('去年', 5),
     ('2月', 4),
     ('5月', 3),
     ('今年', 3),
     ('13日', 3),
     ('38歲', 3),
     ('34歲', 3),
     ('41歲', 2),
     ('69歲', 2),
     ('近年', 2),
     ('1983年', 2),
     ('50多年', 2),
     ('1月', 1),
     ('今年1月24日', 1),
     ('一年', 1),
     ('半世紀', 1),
     ('10年', 1),
     ('前幾天', 1)]),
   ('生活',
    [('今天', 22),
     ('7天', 6),
     ('10天', 4),
     ('3月7日', 4),
     ('5天', 3),
     ('5月', 3),
     ('近年', 3),
     ('2012年', 3),
     ('去年', 3),
     ('11日', 3),
     ('17日', 3),
     ('3天', 2),
     ('未來一個多月', 2),
     ('2019年', 2),
     ('18日', 2),
     ('4月', 2),
     ('2019', 2),
     ('3月', 1),
     ('7月', 1),
     ('1110314', 1)]),
   ('國際',
    [('今天', 28),
     ('昨天', 5),
     ('2015年', 3),
     ('上週', 3),
     ('14日', 2),
     ('2014年', 1),
     ('15日', 1),
     ('明天', 1),
     ('2018年', 1),
     ('10個多月', 1),
     ('5日', 1),
     ('11日', 1),
     ('2022年', 1),
     ('2年', 1),
     ('3月14日至4月1日', 1),
     ('今年', 1),
     ('4月', 1),
     ('本週', 1),
     ('16日', 1),
     ('數年', 1)]),
   ('社會',
    [('今天', 33),
     ('昨天', 4),
     ('3年', 4),
     ('10日', 3),
     ('日前', 2),
     ('明天', 2),
     ('3月', 2),
     ('30日', 2),
     ('9日', 2),
     ('12日', 2),
     ('去年11月', 2),
     ('1年6月', 2),
     ('2023年', 2),
     ('108年', 2),
     ('8歲', 2),
     ('40歲', 1),
     ('5年', 1),
     ('108年5月18日', 1),
     ('40日', 1),
     ('108年9月', 1)]),
   ('文化',
    [('今天', 20),
     ('今年', 11),
     ('7月', 3),
     ('6日', 3),
     ('去年', 2),
     ('26日', 2),
     ('21世紀', 2),
     ('2019年', 2),
     ('3個月', 2),
     ('未來3個月', 2),
     ('2021年', 2),
     ('百年', 2),
     ('日治時期', 2),
     ('40年', 1),
     ('2020年', 1),
     ('1980年', 1),
     ('年度', 1),
     ('近年', 1),
     ('3月15日', 1),
     ('11日', 1)]),
   ('兩岸',
    [('今天', 28),
     ('13日', 9),
     ('7天', 6),
     ('昨天', 4),
     ('今日', 3),
     ('14天', 3),
     ('2020年5月', 2),
     ('11日', 2),
     ('近日', 2),
     ('14日', 2),
     ('2019年', 2),
     ('近年', 2),
     ('本週', 2),
     ('今年', 2),
     ('2至3週', 2),
     ('10幾年', 1),
     ('1日', 1),
     ('3月1日至13日', 1),
     ('6年', 1),
     ('2019年底', 1)]),
   ('全部',
    [('今天', 332),
     ('今年', 66),
     ('去年', 57),
     ('昨天', 28),
     ('2021年', 19),
     ('11日', 15),
     ('2月', 15),
     ('3月', 14),
     ('13日', 13),
     ('18日', 12),
     ('7天', 12),
     ('4月', 11),
     ('2020年', 11),
     ('2019年', 11),
     ('近年', 10),
     ('5月', 9),
     ('2年', 8),
     ('14日', 8),
     ('一年', 7),
     ('1月', 7)])]],
 ['EVENT',
  [('政治', [('COVID-19（2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭', 1)]),
   ('科技', []),
   ('運動',
    [('帕運會', 3),
     ('奧運', 2),
     ('東京奧運', 1),
     ('超級盃', 1),
     ('去年東京奧運', 1),
     ('帕運', 1)]),
   ('證卷', []),
   ('產經', [('俄烏戰爭', 5), ('俄烏戰事', 1)]),
   ('娛樂', []),
   ('生活', [('COVID-19', 1)]),
   ('國際', [('烏克蘭戰爭', 2), ('COVID-19', 1), ('2019', 1)]),
   ('社會', []),
   ('文化',
    [('雪梨雙年展', 4),
     ('第23屆雪梨雙年展', 2),
     ('2019', 1),
     ('百老匯', 1),
     ('高雄春天藝術節', 1),
     ('2022年高雄春天藝術節', 1),
     ('2019冠狀病毒疾病', 1),
     ('百週年慶', 1)]),
   ('兩岸', [('東莞市疫情防控指揮辦', 1), ('2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭', 1)]),
   ('全部',
    [('俄烏戰爭', 7),
     ('雪梨雙年展', 4),
     ('帕運會', 3),
     ('奧運', 2),
     ('COVID-19', 2),
     ('烏克蘭戰爭', 2),
     ('2019', 2),
     ('第23屆雪梨雙年展', 2),
     ('COVID-19（2019冠狀病毒疾病）疫情', 1),
     ('東京奧運', 1),
     ('超級盃', 1),
     ('去年東京奧運', 1),
     ('帕運', 1),
     ('俄烏戰事', 1),
     ('百老匯', 1),
     ('高雄春天藝術節', 1),
     ('2022年高雄春天藝術節', 1),
     ('2019冠狀病毒疾病', 1),
     ('百週年慶', 1),
     ('東莞市疫情防控指揮辦', 1)])]],
 ['FAC',
  [('政治',
    [('台東志航基地', 8),
     ('台東馬偕醫院', 5),
     ('新竹空軍基地', 4),
     ('新竹基地', 4),
     ('志航基地', 3),
     ('玉山國家公園', 2),
     ('君悅酒店', 1),
     ('台南空軍基地', 1),
     ('盧賽基地', 1)]),
   ('科技', [('科博館', 3), ('國立自然科學博物館', 1)]),
   ('運動',
    [('新加坡華僑銀行室內體育館', 3),
     ('台南市立棒球場', 2),
     ('嘉義縣立棒球場體驗球場', 1),
     ('斗六棒球場', 1),
     ('立棒球場', 1),
     ('OCBC Arena', 1),
     ('國家體育場', 1),
     ('鳥巢', 1)]),
   ('證卷', []),
   ('產經', [('長春廠', 1)]),
   ('娛樂', [('鶯歌後村堰遙控飛機場', 1), ('台灣會館', 1)]),
   ('生活', []),
   ('國際', []),
   ('社會',
    [('家樂福', 2),
     ('楊梅物流中心', 2),
     ('竹東火車站', 1),
     ('永明派出所', 1),
     ('桃機東變電站', 1),
     ('桃機西變電站', 1),
     ('高寮夜景公園', 1),
     ('家樂福倉儲', 1),
     ('美福倉儲', 1),
     ('楊梅', 1),
     ('桃園楊梅', 1),
     ('大園', 1),
     ('高雄岡山倉庫', 1),
     ('桃園大園', 1)]),
   ('文化',
    [('明華園', 6),
     ('衛武營音樂廳', 3),
     ('千禧公園', 2),
     ('衛武營', 2),
     ('新莊聯合辦公大樓', 1),
     ('屏東智慧農業學校', 1),
     ('南華微光', 1),
     ('南華校園', 1),
     ('高雄衛武營', 1),
     ('台南文化中心', 1),
     ('台中國家歌劇院', 1),
     ('台北國家戲劇院', 1),
     ('利沃夫博物館', 1),
     ('伊萬基夫歷史博物館', 1),
     ('哈爾科夫藝術博物館', 1),
     ('易北愛樂小廳', 1),
     ('柏林愛樂室內樂廳', 1),
     ('項鍊工作室', 1),
     ('大衛．胡斯', 1),
     ('台中國家歌劇院大劇院', 1)]),
   ('兩岸', [('安老院', 1)]),
   ('全部',
    [('台東志航基地', 8),
     ('明華園', 6),
     ('台東馬偕醫院', 5),
     ('新竹空軍基地', 4),
     ('新竹基地', 4),
     ('志航基地', 3),
     ('科博館', 3),
     ('新加坡華僑銀行室內體育館', 3),
     ('衛武營音樂廳', 3),
     ('玉山國家公園', 2),
     ('台南市立棒球場', 2),
     ('家樂福', 2),
     ('楊梅物流中心', 2),
     ('千禧公園', 2),
     ('衛武營', 2),
     ('君悅酒店', 1),
     ('台南空軍基地', 1),
     ('盧賽基地', 1),
     ('國立自然科學博物館', 1),
     ('嘉義縣立棒球場體驗球場', 1)])]],
 ['GPE',
  [('政治',
    [('台灣', 25),
     ('台東', 10),
     ('法國', 8),
     ('烏克蘭', 5),
     ('高雄', 5),
     ('澳洲', 5),
     ('德國', 4),
     ('雪梨', 4),
     ('新竹', 3),
     ('美國', 2),
     ('大陸', 2),
     ('高雄市', 2),
     ('台北', 2),
     ('中國', 2),
     ('台澳', 2),
     ('英國', 1),
     ('南台灣', 1),
     ('北市', 1),
     ('澳大利亞', 1),
     ('嘉義', 1)]),
   ('科技',
    [('台灣', 23),
     ('俄羅斯', 13),
     ('烏克蘭', 7),
     ('印度', 5),
     ('中國', 5),
     ('德國', 5),
     ('美國', 4),
     ('日本', 2),
     ('台北', 2),
     ('中華民國', 1),
     ('亞美尼亞', 1),
     ('亞塞拜然', 1),
     ('愛沙尼亞', 1),
     ('喬治亞', 1),
     ('匈牙利', 1),
     ('拉脫維亞', 1),
     ('立陶宛', 1),
     ('波蘭', 1),
     ('羅馬尼亞', 1),
     ('斯洛伐克', 1)]),
   ('運動',
    [('台灣', 13),
     ('新加坡', 10),
     ('巴西', 6),
     ('印度', 5),
     ('中國', 5),
     ('瑞典', 4),
     ('韓國', 4),
     ('台南', 3),
     ('克羅埃西亞', 3),
     ('新竹市', 2),
     ('南韓', 2),
     ('嘉義縣', 2),
     ('日本', 2),
     ('斯洛維尼亞', 2),
     ('北京', 2),
     ('烏克蘭', 2),
     ('淡水', 2),
     ('台中市', 1),
     ('旅美', 1),
     ('美國', 1)]),
   ('證卷',
    [('台灣', 18),
     ('台股', 15),
     ('台北', 4),
     ('烏克蘭', 2),
     ('中國大陸', 2),
     ('日本', 2),
     ('美股', 2),
     ('中國', 1),
     ('美國', 1),
     ('日股', 1)]),
   ('產經',
    [('台灣', 22),
     ('中國', 12),
     ('俄羅斯', 7),
     ('烏克蘭', 6),
     ('深圳', 4),
     ('深圳市', 3),
     ('俄烏', 2),
     ('吉林省', 2),
     ('長春市', 2),
     ('日本', 2),
     ('天津市', 2),
     ('台北', 2),
     ('美國', 2),
     ('廣東省', 2),
     ('紐約西德州', 1),
     ('西德州', 1),
     ('倫敦', 1),
     ('北海布倫特', 1),
     ('上海', 1),
     ('中國大陸', 1)]),
   ('娛樂',
    [('台灣', 11),
     ('美國', 10),
     ('英國', 9),
     ('香港', 5),
     ('洛杉磯', 4),
     ('南庄', 3),
     ('新北', 2),
     ('烏克蘭', 2),
     ('紐約', 2),
     ('台北', 2),
     ('法國', 1),
     ('德國', 1),
     ('日本', 1),
     ('加拿大', 1),
     ('新竹', 1),
     ('彰化', 1),
     ('屏東', 1),
     ('花蓮', 1),
     ('紐西蘭', 1),
     ('倫敦', 1)]),
   ('生活',
    [('台灣', 4),
     ('台北', 3),
     ('彰化縣', 2),
     ('中國', 2),
     ('南投縣名間鄉', 1),
     ('雲林縣', 1),
     ('金門', 1),
     ('新埔站', 1),
     ('苗栗縣', 1),
     ('員林市', 1),
     ('中華', 1),
     ('中壢', 1),
     ('香港', 1),
     ('深圳市', 1),
     ('東莞市', 1),
     ('台北市', 1),
     ('桃園市', 1),
     ('菲律賓', 1),
     ('越南', 1),
     ('泰國', 1)]),
   ('國際',
    [('俄羅斯', 23),
     ('俄國', 23),
     ('烏克蘭', 16),
     ('香港', 14),
     ('印度', 12),
     ('台灣', 12),
     ('美國', 10),
     ('德國', 10),
     ('伊朗', 9),
     ('莫斯科', 9),
     ('中國', 9),
     ('挪威', 7),
     ('日本', 7),
     ('澳洲', 4),
     ('英國', 3),
     ('俄方', 3),
     ('土耳其', 3),
     ('福井縣', 3),
     ('雪梨', 2),
     ('卡達', 2)]),
   ('社會',
    [('台灣', 4),
     ('義大利', 3),
     ('嘉義市', 2),
     ('高雄', 2),
     ('中國', 2),
     ('廣東', 2),
     ('台中', 2),
     ('桃園市', 2),
     ('苗栗縣', 1),
     ('通霄鎮', 1),
     ('新竹縣', 1),
     ('嘉義', 1),
     ('台中市', 1),
     ('神岡區', 1),
     ('花東', 1),
     ('東河鄉', 1),
     ('台東', 1),
     ('台東縣東河鄉', 1),
     ('財政部', 1),
     ('林口區', 1)]),
   ('文化',
    [('台灣', 30),
     ('高雄', 14),
     ('烏克蘭', 7),
     ('屏東', 6),
     ('德國', 6),
     ('美國', 5),
     ('柏林', 5),
     ('台南', 4),
     ('俄羅斯', 3),
     ('紐約', 2),
     ('屏東市', 2),
     ('新莊', 2),
     ('高雄市', 2),
     ('台北', 2),
     ('日本', 2),
     ('西班牙', 1),
     ('澳洲', 1),
     ('捷克布拉格', 1),
     ('俄國', 1),
     ('嘉義縣', 1)]),
   ('兩岸',
    [('中國', 90),
     ('香港', 69),
     ('俄羅斯', 22),
     ('北京', 19),
     ('深圳', 18),
     ('東莞', 16),
     ('港府', 14),
     ('美國', 13),
     ('台灣', 10),
     ('東莞市', 8),
     ('美方', 7),
     ('廣東', 3),
     ('上海', 3),
     ('廣東省', 3),
     ('吉林市', 3),
     ('澳門', 2),
     ('中方', 2),
     ('深圳市', 2),
     ('封城', 2),
     ('中港', 2)]),
   ('全部',
    [('台灣', 172),
     ('中國', 129),
     ('香港', 89),
     ('俄羅斯', 70),
     ('烏克蘭', 48),
     ('美國', 48),
     ('俄國', 27),
     ('德國', 26),
     ('深圳', 24),
     ('北京', 23),
     ('印度', 22),
     ('高雄', 21),
     ('台北', 19),
     ('日本', 18),
     ('英國', 17),
     ('東莞', 16),
     ('台股', 15),
     ('港府', 14),
     ('新加坡', 13),
     ('法國', 12)])]],
 ['LANGUAGE',
  [('政治', [('英文', 1)]),
   ('科技', []),
   ('運動', [('中文', 1)]),
   ('證卷', []),
   ('產經', []),
   ('娛樂', [('華語', 1), ('英文', 1)]),
   ('生活', []),
   ('國際', []),
   ('社會', []),
   ('文化', [('客家話', 1), ('閩南語', 1), ('日語', 1), ('吳儂軟語', 1)]),
   ('兩岸', [('英文', 2)]),
   ('全部',
    [('英文', 4),
     ('中文', 1),
     ('華語', 1),
     ('客家話', 1),
     ('閩南語', 1),
     ('日語', 1),
     ('吳儂軟語', 1)])]],
 ['LAW',
  [('政治', []),
   ('科技', [('LINE', 1)]),
   ('運動', []),
   ('證卷', []),
   ('產經', []),
   ('娛樂', []),
   ('生活', []),
   ('國際', [('國安法', 2), ('北約憲章第5條', 1)]),
   ('社會', []),
   ('文化', []),
   ('兩岸', [('香港國安法', 1), ('外國公司問責法', 1)]),
   ('全部',
    [('國安法', 2), ('LINE', 1), ('北約憲章第5條', 1), ('香港國安法', 1), ('外國公司問責法', 1)])]],
 ['LOC',
  [('政治',
    [('台灣西南防空識別區', 1),
     ('北美', 1),
     ('屯稜線', 1),
     ('丹大溪', 1),
     ('巒大溪', 1),
     ('郡大溪', 1)]),
   ('科技', [('南極', 7), ('月球', 5), ('月球南極', 1), ('太陽系', 1)]),
   ('運動', []),
   ('證卷', [('亞洲', 1)]),
   ('產經', [('歐洲', 12), ('東北', 1), ('塞港', 1)]),
   ('娛樂', [('神仙谷', 3), ('北美', 1), ('溪谷', 1)]),
   ('生活', [('東半部', 2), ('東北', 1), ('東南風', 1), ('馬祖地區', 1), ('基隆港', 1)]),
   ('國際',
    [('亞洲', 2), ('北極', 1), ('北歐', 1), ('博斯普魯斯海峽', 1), ('太平洋', 1), ('歐洲', 1)]),
   ('社會', [('高雄港', 1), ('陽明山', 1), ('中山區中山北路', 1), ('楊梅區', 1)]),
   ('文化',
    [('歐洲', 2),
     ('亞洲', 1),
     ('大海', 1),
     ('北美', 1),
     ('東海岸', 1),
     ('台南山', 1),
     ('東南亞', 1)]),
   ('兩岸', [('美東', 1), ('特別行政區', 1)]),
   ('全部',
    [('歐洲', 15),
     ('南極', 7),
     ('月球', 5),
     ('亞洲', 4),
     ('北美', 3),
     ('神仙谷', 3),
     ('東北', 2),
     ('東半部', 2),
     ('台灣西南防空識別區', 1),
     ('屯稜線', 1),
     ('丹大溪', 1),
     ('巒大溪', 1),
     ('郡大溪', 1),
     ('月球南極', 1),
     ('太陽系', 1),
     ('塞港', 1),
     ('溪谷', 1),
     ('東南風', 1),
     ('馬祖地區', 1),
     ('基隆港', 1)])]],
 ['MONEY',
  [('政治',
    [('新台幣6億元', 1),
     ('3萬5703美元', 1),
     ('約101萬元', 1),
     ('3萬5703', 1),
     ('新台幣約101萬元', 1),
     ('4億7222萬元', 1),
     ('1億3788萬元', 1)]),
   ('科技',
    [('1萬3900元', 5),
     ('1萬7900元', 3),
     ('1萬5500元', 2),
     ('1萬9000元', 2),
     ('3999美元', 2),
     ('新台幣60億元', 1),
     ('新台幣', 1),
     ('5萬9900元', 1),
     ('4萬5900元', 1),
     ('1.79萬元', 1),
     ('2萬2900元', 1),
     ('429美元', 1),
     ('399美元', 1),
     ('1999美元', 1),
     ('1599美元', 1),
     ('599美元', 1)]),
   ('運動', [('200萬美元', 4), ('十元', 1)]),
   ('證卷',
    [('新台幣2861.6億元', 4),
     ('0.1元', 4),
     ('20元', 3),
     ('132.5元', 3),
     ('7元', 2),
     ('4.5元', 2),
     ('1.31元', 2),
     ('1.93億元', 2),
     ('46.23元', 2),
     ('26元', 2),
     ('3億元', 2),
     ('16.04億元', 2),
     ('142.43億元', 2),
     ('新台幣2億元', 2),
     ('0.6元', 2),
     ('0.7元', 2),
     ('0.67元', 2),
     ('4.7億元', 2),
     ('1.52元', 2),
     ('164.5元', 1)]),
   ('產經',
    [('430億歐元', 3),
     ('28.53元', 2),
     ('28.450元', 2),
     ('28.420元', 2),
     ('28.534元', 2),
     ('1.01元', 2),
     ('新台幣4000億元', 1),
     ('173億元', 1),
     ('10.35元', 1),
     ('5元', 1),
     ('新台幣38.84億元', 1),
     ('1.3元', 1),
     ('0.65元', 1),
     ('0.5元', 1),
     ('新台幣2000萬元', 1),
     ('2000萬元', 1),
     ('2.02億元', 1),
     ('103.80美元', 1),
     ('108.13美元', 1),
     ('新台幣2千萬元', 1)]),
   ('娛樂', [('2000萬元', 1)]),
   ('生活',
    [('2元', 4),
     ('新台幣2萬元', 1),
     ('1萬2500元', 1),
     ('12萬5000元', 1),
     ('新台幣10萬元', 1),
     ('12億餘元', 1),
     ('新台幣3元', 1),
     ('38.5元', 1),
     ('48元', 1),
     ('新台幣575萬元', 1),
     ('50萬元', 1),
     ('575萬元', 1)]),
   ('國際', [('1490億印度盧比', 1), ('19.4億美元', 1)]),
   ('社會',
    [('80萬元', 5),
     ('新台幣6萬7500元', 2),
     ('600元', 2),
     ('10萬元', 2),
     ('30萬元', 2),
     ('500萬元', 2),
     ('新台幣3萬元', 1),
     ('新台幣500萬元', 1),
     ('200億元', 1),
     ('新台幣200億元', 1),
     ('12餘億元', 1),
     ('新台幣9萬元', 1),
     ('9萬元', 1),
     ('新台幣1000萬元', 1),
     ('35元', 1),
     ('1000萬元', 1),
     ('新台幣600元', 1),
     ('2500萬元', 1),
     ('200萬元', 1),
     ('新台幣80萬元', 1)]),
   ('文化', [('新台幣385萬元', 1), ('新台幣2700萬元', 1)]),
   ('兩岸',
    [('80.9港元', 1),
     ('8港元', 1),
     ('6400億美元', 1),
     ('約17兆新台幣', 1),
     ('約12.6兆新台幣', 1)]),
   ('全部',
    [('1萬3900元', 5),
     ('80萬元', 5),
     ('200萬美元', 4),
     ('新台幣2861.6億元', 4),
     ('0.1元', 4),
     ('2元', 4),
     ('1萬7900元', 3),
     ('20元', 3),
     ('132.5元', 3),
     ('3億元', 3),
     ('430億歐元', 3),
     ('新台幣', 2),
     ('1萬5500元', 2),
     ('1萬9000元', 2),
     ('3999美元', 2),
     ('7元', 2),
     ('4.5元', 2),
     ('1.31元', 2),
     ('1.93億元', 2),
     ('46.23元', 2)])]],
 ['NORP',
  [('政治',
    [('烏克蘭', 6),
     ('德商', 2),
     ('歐商', 1),
     ('美商', 1),
     ('日商', 1),
     ('中商', 1),
     ('法方', 1)]),
   ('科技', [('奧斯汀', 1), ('台灣', 1)]),
   ('運動', [('泰雅族', 1), ('捷克', 1), ('淡商', 1)]),
   ('證卷', []),
   ('產經', [('台商', 5)]),
   ('娛樂',
    [('華裔', 2),
     ('北埔人', 1),
     ('英國', 1),
     ('台灣人', 1),
     ('香港', 1),
     ('香港人', 1),
     ('烏克蘭', 1),
     ('烏克蘭人', 1),
     ('歐洲人', 1),
     ('中華', 1),
     ('美籍', 1),
     ('美國', 1)]),
   ('生活', [('印尼籍', 2)]),
   ('國際', [('俄國', 1)]),
   ('社會', [('台灣', 1), ('富商', 1)]),
   ('文化',
    [('台灣', 6),
     ('排灣族', 2),
     ('中國', 2),
     ('台裔', 2),
     ('鄒族', 1),
     ('德國', 1),
     ('華人', 1),
     ('台籍', 1),
     ('阿美族', 1),
     ('日本', 1),
     ('美籍', 1),
     ('英國', 1)]),
   ('兩岸',
    [('港人', 3),
     ('台籍', 1),
     ('中國', 1),
     ('港媒', 1),
     ('陸媒', 1),
     ('台資', 1),
     ('中文', 1),
     ('中國人', 1)]),
   ('全部',
    [('台灣', 8),
     ('烏克蘭', 7),
     ('台商', 5),
     ('中國', 3),
     ('港人', 3),
     ('德商', 2),
     ('英國', 2),
     ('華裔', 2),
     ('美籍', 2),
     ('印尼籍', 2),
     ('排灣族', 2),
     ('台裔', 2),
     ('台籍', 2),
     ('歐商', 1),
     ('美商', 1),

## Save each ne's top 200 category word frequency

In [43]:
import pandas as pd

In [44]:
df_top_word_NE = pd.DataFrame(top_word_NE, columns = ['ne_name','top_keys'])

In [45]:
df_top_word_NE

        ne_name                                           top_keys
0      CARDINAL  [(政治, [('2000', 7), ('4000', 2), ('13', 2), ('...
1          DATE  [(政治, [('今天', 35), ('12天', 2), ('5月', 2), ('同年...
2         EVENT  [(政治, [('COVID-19（2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭',...
3           FAC  [(政治, [('台東志航基地', 8), ('台東馬偕醫院', 5), ('新竹空軍基地'...
4           GPE  [(政治, [('台灣', 25), ('台東', 10), ('法國', 8), ('烏克...
5      LANGUAGE  [(政治, [('英文', 1)]), (科技, []), (運動, [('中文', 1)]...
6           LAW  [(政治, []), (科技, [('LINE', 1)]), (運動, []), (證卷,...
7           LOC  [(政治, [('台灣西南防空識別區', 1), ('北美', 1), ('屯稜線', 1)...
8         MONEY  [(政治, [('新台幣6億元', 1), ('3萬5703美元', 1), ('約101萬...
9          NORP  [(政治, [('烏克蘭', 6), ('德商', 2), ('歐商', 1), ('美商'...
10      ORDINAL  [(政治, [('第四', 2), ('第1', 1), ('第206', 1), ('第8...
11          ORG  [(政治, [('外交部', 16), ('立法院', 13), ('監察院', 9), (...
12      PERCENT  [(政治, [('5%', 1), ('45%', 1)]), (科技, [('100%',...
13       PERSON  [(政治, [('黃重凱', 24), ('柳惠千', 13), ('喬建中', 12), ...
14      PRODUCT  [(政治, [('2000', 3), ('殲16戰機', 2), ('2017', 1),...
15     QUANTITY  [(政治, [('2000呎', 6), ('10浬', 5), ('80公頃', 2), ...
16         TIME  [(政治, [('下午', 10), ('上午', 10), ('11時26分', 5), ...
17  WORK_OF_ART  [(政治, []), (科技, []), (運動, []), (證卷, []), (產經, ...

In [49]:
df_top_word_NE.to_csv('news_topkey_by_ner_and_category.csv', sep=',', index=False) # 本次的NER任務

# Another way to analyze by concatenating counter objects 

Code for your references

In [50]:
from collections import Counter
a = Counter({'menu': 20, 'good': 15, 'happy': 10, 'bar': 5})
b = Counter({'menu': 1, 'good': 1, 'bar': 3})
a + b

Counter({'menu': 21, 'good': 16, 'happy': 10, 'bar': 8})

In [51]:
top_cate_ner_words={} # final result
counter_all = Counter() # counter for category '全部'
for category in news_categories:
    
    df_group = df[df.category == category]
    
    # concatenate all filtered words in the same category
    words_group = []
    for row in df_group.entities:
        
        # filter words for each news
        filtered_words =[]
        for (ner, word) in eval(row):
            if (len(word) >= 2) & (ner in allowedNE):
                filtered_words.append(word)
                
        # concatenate filtered words  
        words_group += filtered_words

    # now we can count word frequency
    counter = Counter( words_group )
    
    # We use adding counter to get counter_all: 
    counter_all += counter

    topwords = counter.most_common(200)
    # store topwords
    top_cate_ner_words[category]= topwords

# Process category '全部'
top_cate_ne_words['全部'] = counter_all.most_common(200)

In [52]:
# All-in-one function
def get_top_ner_words():
    
    top_cate_ner_words={} # final result
    counter_all = Counter() # counter for category '全部'
    for category in news_categories:

        df_group = df[df.category == category]

        # concatenate all filtered words in the same category
        words_group = []
        for row in df_group.entities:

            # filter words for each news
            filtered_words =[]
            for (ner, word) in eval(row):
                if (len(word) >= 2) & (ner in allowedNE):
                    filtered_words.append(word)

            # concatenate filtered words  
            words_group += filtered_words

        # now we can count word frequency
        counter = Counter( words_group )

        # counter 
        counter_all += counter
        topwords = counter.most_common(200)

        # store topwords
        top_cate_ner_words[category]= topwords

    # Process category '全部'
    top_cate_ner_words['全部'] = counter_all.most_common(200)
    return list(top_cate_ner_words.items())

In [53]:
#allowedNE=['EVENT','FAC','GPE','LANGUAGE','LAW','LOC','NORP','ORG','PERSON','PRODUCT','WORK_OF_ART']
allowedNE=['PERSON']
get_top_ner_words()

[('政治',
  [('黃重凱', 24),
   ('柳惠千', 13),
   ('喬建中', 12),
   ('徐國勇', 11),
   ('季欽', 8),
   ('許舒博', 7),
   ('游錫堃', 6),
   ('侯富議', 6),
   ('蘇貞昌', 5),
   ('吳釗燮', 4),
   ('許佑格', 4),
   ('范惠君', 4),
   ('歐布萊恩', 4),
   ('陳其邁', 3),
   ('柯文哲', 3),
   ('陳智菡', 3),
   ('黃鼎翔', 3),
   ('王同義', 3),
   ('王美惠', 3),
   ('許邁德', 2),
   ('蔣萬安', 2),
   ('蔡練生', 2),
   ('沈榮津', 2),
   ('朱冠甍', 1),
   ('蘇紫雲', 1),
   ('蔣經國', 1),
   ('陳長江', 1),
   ('沈啟明', 1),
   ('周艷', 1),
   ('劉瑞寧', 1),
   ('賴新峰', 1),
   ('王奕然', 1),
   ('惠楊', 1),
   ('申濱', 1),
   ('李華', 1),
   ('李群', 1),
   ('施博祥', 1),
   ('蘇莉莉', 1),
   ('林栢梧', 1),
   ('葉義深', 1),
   ('蔡福松', 1),
   ('熊厚基', 1),
   ('陳元泰', 1),
   ('張仁澤', 1),
   ('黃重凱平', 1),
   ('葉宜津', 1),
   ('蔡崇義', 1),
   ('賴鼎銘', 1),
   ('王文淵', 1),
   ('洪孟楷', 1),
   ('吳彬福', 1),
   ('吳世峰', 1),
   ('江金亮', 1),
   ('劉浩帆', 1),
   ('張健翔', 1),
   ('何威克', 1),
   ('虞德忠', 1),
   ('劉永祥', 1),
   ('鄭育騰', 1),
   ('何子雨', 1)]),
 ('科技',
  [('林柏亨', 6),
   ('吳偉仁', 5),
   ('包淳偉', 4),
   ('黃晨瑋', 4),
   ('廖俊智', 4),
   ('波博', 3),
   ('黃文山', 3),
   ('艾偉', 3),
   ('王金燦', 2),
   ('庫克', 2),
   ('曾信超', 2),
   ('波皮斯庫', 2),
   ('王兆璋', 1),
   ('希塔拉姆', 1),
   ('吳宗信', 1),
   ('葉均蔚', 1),
   ('楊勇', 1),
   ('陳信安', 1),
   ('Tim哥', 1),
   ('夏哈', 1),
   ('Tim Cook）', 1),
   ('林文燦', 1),
   ('陳祺助', 1),
   ('林全能', 1),
   ('柯文哲', 1),
   ('侯友宜', 1),
   ('簡又新', 1)]),
 ('運動',
  [('林昀儒', 24),
   ('鄭怡靜', 24),
   ('莊智淵', 17),
   ('陳將双', 12),
   ('潘武雄', 10),
   ('陳建安', 8),
   ('布雷迪', 7),
   ('布魯娜', 6),
   ('賈奈特', 6),
   ('艾倫', 6),
   ('塞爾蒂克', 5),
   ('李恩芯', 5),
   ('王志庭', 4),
   ('施冠宇', 4),
   ('加奇尼', 4),
   ('樂天', 3),
   ('安宰賢', 3),
   ('巴特瑞', 3),
   ('梁家榮', 3),
   ('黃子鵬', 3),
   ('高飛', 3),
   ('郭俊麟', 3),
   ('陳冠宇', 3),
   ('皮爾斯', 3),
   ('帕森斯', 3),
   ('岱縈', 2),
   ('筠熹', 2),
   ('摩賈德', 2),
   ('林鍾勳', 2),
   ('張禹珍', 2),
   ('周哲宇', 2),
   ('張志豪', 2),
   ('王威晨', 2),
   ('江國豪', 2),
   ('官大元', 2),
   ('施子謙', 2),
   ('陳思羽', 2),
   ('約爾吉奇', 2),
   ('浦韋青', 1),
   ('胡瓜', 1),
   ('林襄', 1),
   ('霖霖', 1),
   ('伊婷（Kira）', 1),
   ('詩媛', 1),
   ('佳琳', 1),
   ('雅涵', 1),
   ('婉卉', 1),
   ('宋宋', 1),
   ('Tru', 1),
   ('Manika Batra', 1),
   ('林立', 1),
   ('何恆佑', 1),
   ('李丞齡', 1),
   ('萬昭清', 1),
   ('蘇俊羽', 1),
   ('王躍霖', 1),
   ('朱俊祥', 1),
   ('林立安', 1),
   ('藍寅倫', 1),
   ('林泓育', 1),
   ('林柏安', 1),
   ('黃明真', 1),
   ('邱邦', 1),
   ('曾傳昇安', 1),
   ('張祐嘉', 1),
   ('劉基鴻', 1),
   ('李展毅', 1),
   ('董秉軒', 1),
   ('潘志芳', 1),
   ('陳韋霖', 1),
   ('林逸翔', 1),
   ('曾峻岳', 1),
   ('高國輝', 1),
   ('陽春', 1),
   ('陽耀勳', 1),
   ('戴培峰', 1),
   ('申皓瑋', 1),
   ('江坤宇', 1),
   ('林書逸安', 1),
   ('吳哲源', 1),
   ('王奕凱', 1),
   ('吳俊偉', 1),
   ('王鏡銘', 1),
   ('林智平', 1),
   ('林政華', 1),
   ('蔡鎮宇', 1),
   ('林子豪', 1),
   ('高國慶', 1),
   ('陳傑憲', 1),
   ('劉予承', 1),
   ('伊藤美誠', 1),
   ('劉馨尹', 1),
   ('孫穎莎', 1),
   ('王曼昱', 1),
   ('樂天桃猿', 1),
   ('石川佳純', 1),
   ('瑪泰洛娃', 1),
   ('Ray Allen', 1),
   ('唐西奇', 1),
   ('丁威迪', 1),
   ('習近平', 1),
   ('廖振珽', 1),
   ('曾尖', 1),
   ('賴清德', 1),
   ('陳信安', 1),
   ('吳思瑤', 1),
   ('潘文忠', 1),
   ('張俊生', 1),
   ('鄭名斈', 1),
   ('謝銘駿', 1),
   ('黃子芸', 1)]),
 ('證卷', [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)]),
 ('產經',
  [('陳耀祥', 17),
   ('朱澤民', 9),
   ('曾博昇', 6),
   ('杜書全', 5),
   ('蘇松輝', 4),
   ('趙正宇', 3),
   ('林崇燾', 3),
   ('童振源', 3),
   ('郭幸容', 2),
   ('林德福', 2),
   ('吳秉叡', 2),
   ('李昆澤', 2),
   ('丁予嘉', 1),
   ('魏啟林', 1),
   ('佛里奇', 1),
   ('史屈特', 1),
   ('Susannah Streeter）', 1),
   ('林楚茵', 1),
   ('許智傑', 1),
   ('林俊憲', 1),
   ('陳素月', 1),
   ('劉世芳', 1),
   ('費多羅夫', 1),
   ('林見松', 1),
   ('陳阡蕙', 1),
   ('李玉香', 1),
   ('高嘉瑜', 1),
   ('許淑華', 1)]),
 ('娛樂',
  [('唐川', 20),
   ('歸亞蕾', 18),
   ('炎亞綸', 11),
   ('威廉赫特', 10),
   ('莊凱勛', 8),
   ('楊藜', 8),
   ('林暉閔', 7),
   ('納豆', 7),
   ('黃新皓', 6),
   ('珍康萍', 6),
   ('曹格', 6),
   ('侯友宜', 5),
   ('黃子佼', 5),
   ('百白', 4),
   ('孟耿如', 4),
   ('吳慷仁', 4),
   ('林心如', 4),
   ('郭宇宸', 3),
   ('茶金', 3),
   ('温昇豪', 3),
   ('郭子乾', 3),
   ('葉如芬', 3),
   ('楊雅喆', 3),
   ('連俞涵', 2),
   ('桂綸鎂', 2),
   ('威爾史密斯', 2),
   ('蔡英文', 2),
   ('林思宇', 2),
   ('陸夏', 2),
   ('張書豪', 2),
   ('張睿家', 2),
   ('姚愛寗', 2),
   ('林煒傑', 1),
   ('李見騰', 1),
   ('黃云歆', 1),
   ('葉泓毅', 1),
   ('郝心翔', 1),
   ('柏霖', 1),
   ('林郁智', 1),
   ('阿Ken', 1),
   ('林暐恆', 1),
   ('徐熙娣', 1),
   ('黃路梓茵', 1),
   ('陳嘉樺', 1),
   ('彭佳慧', 1),
   ('藍心湄', 1),
   ('張可昀', 1),
   ('蔡嘉茵', 1),
   ('大威', 1),
   ('小威', 1),
   ('喬安娜史坎蘭', 1),
   ('特洛伊科特蘇爾', 1),
   ('亞莉安娜', 1),
   ('黛博塞', 1),
   ('格雷格弗萊瑟', 1),
   ('周冠威', 1),
   ('理查', 1),
   ('曾均崧', 1),
   ('川哥', 1),
   ('川爸', 1),
   ('日頭哥', 1),
   ('天眼', 1),
   ('劉伯溫傳奇', 1),
   ('陂塘', 1),
   ('威爾', 1),
   ('赫特', 1),
   ('玉米', 1),
   ('姚愛寗心', 1),
   ('吳嘉星', 1),
   ('李安', 1),
   ('梅莉史翠普', 1),
   ('多曼尼', 1),
   ('劉品言', 1),
   ('謝瓊煖', 1),
   ('謝欣穎', 1),
   ('江宜蓉', 1)]),
 ('生活',
  [('陳時中', 13),
   ('彭佳偉', 13),
   ('黃恩鴻', 5),
   ('李宗宏', 3),
   ('江文全', 2),
   ('邱基旭', 2),
   ('蔡佩君', 2),
   ('王力宏', 1),
   ('王惠美', 1),
   ('柯文哲', 1)]),
 ('國際',
  [('蘇利文', 5),
   ('楊潔篪', 4),
   ('阿布拉莫維奇', 3),
   ('蒲亭', 3),
   ('米佐塔基斯', 3),
   ('羅傑斯', 3),
   ('波多利雅科', 3),
   ('切爾西', 2),
   ('潘恩', 2),
   ('拉夫羅夫', 2),
   ('阿布杜拉希安', 2),
   ('哈蒂柏札德', 2),
   ('奧德洛', 2),
   ('霍恩', 2),
   ('蕭茲', 2),
   ('布魯塞爾', 1),
   ('Marise Payne）', 1),
   ('米勒', 1),
   ('Alexey Miller）', 1),
   ('穆罕穆德', 1),
   ('Sheikh ', 1),
   ('波瑞爾', 1),
   ('普萊斯', 1),
   ('Vladimir Putin）', 1),
   ('拜登（Joe Biden）', 1),
   ('習近平', 1),
   ('岸田文雄', 1),
   ('岸田', 1),
   ('福山哲郎', 1),
   ('福山', 1)]),
 ('社會',
  [('戴寧', 8),
   ('孫道存', 7),
   ('鄭文燦', 6),
   ('孫芸芸', 4),
   ('孫瑩瑩', 3),
   ('孫智宏', 3),
   ('張女', 2),
   ('陳澤嘉', 2),
   ('吳逸萍', 2),
   ('莊英壽', 2),
   ('李作宏', 2),
   ('馬男', 1),
   ('洪裕翔', 1),
   ('何念慈育', 1),
   ('廖偉志', 1),
   ('廖鎮漢', 1),
   ('王國材', 1),
   ('蘇男', 1),
   ('劉育麟', 1),
   ('陳依芳', 1),
   ('邱仁德', 1),
   ('林明裕', 1),
   ('蔡英文', 1)]),
 ('文化',
  [('吳密察', 15),
   ('平珩', 10),
   ('吳蠻', 7),
   ('潘孟安', 6),
   ('吳思瑤', 5),
   ('楊書涵', 5),
   ('李其叡', 5),
   ('張徐展', 5),
   ('蔡采崴', 4),
   ('陳悅宜', 3),
   ('孫翠鳳', 3),
   ('朱天文', 3),
   ('顏伯駿', 3),
   ('鄭志偉', 3),
   ('朱安麗', 3),
   ('柳美', 3),
   ('大衛．胡斯', 3),
   ('李安', 2),
   ('譚盾', 2),
   ('阿儒瓦苡．篙瑪竿', 2),
   ('朱西甯', 2),
   ('李永得', 2),
   ('辜達齊', 2),
   ('黃致凱', 2),
   ('郭耀仁', 2),
   ('方志友', 2),
   ('謝瓊煖', 2),
   ('蔡燦得', 2),
   ('陳家逵', 2),
   ('張廖萬堅', 2),
   ('楊文信', 2),
   ('林佳瑩', 2),
   ('葉澤山', 2),
   ('郭春美', 2),
   ('林曼麗', 2),
   ('戴維斯', 2),
   ('侯傳安', 2),
   ('瑪芮娜', 1),
   ('羅曼菲', 1),
   ('武玉玲', 1),
   ('阿儒瓦苡．篙瑪', 1),
   ('安．芙拉娜根', 1),
   ('范惠君', 1),
   ('施百俊', 1),
   ('劉瑞琪', 1),
   ('吳侑函', 1),
   ('徹摩', 1),
   ('蘇達', 1),
   ('邱祖胤', 1),
   ('劉慕沙', 1),
   ('朱天衣', 1),
   ('吳桓中', 1),
   ('張若瑤', 1),
   ('陳其邁', 1),
   ('史哲', 1),
   ('狄志杰', 1),
   ('元介', 1),
   ('朱宥琳', 1),
   ('陳建凱', 1),
   ('蘇銘', 1),
   ('楊秀卿', 1),
   ('吳栯禔', 1),
   ('費利佩岡巴', 1),
   ('茱莉泰默', 1),
   ('黃國書', 1),
   ('萬美玲', 1),
   ('趙季平', 1),
   ('董榕森', 1),
   ('鄭思森', 1),
   ('關迺忠', 1),
   ('林奕華', 1),
   ('彭子程', 1),
   ('菅芒花', 1),
   ('李孟坡', 1),
   ('理查．史特勞斯', 1),
   ('穆勒', 1),
   ('簡碧青', 1),
   ('彭靖', 1),
   ('撒部．噶照', 1),
   ('陳昭香', 1),
   ('張秀琴', 1),
   ('阿婆蘭', 1),
   ('柴科夫斯基', 1),
   ('斯特內斯', 1),
   ('蕭士塔科維契', 1)]),
 ('兩岸',
  [('薛達', 6),
   ('林鄭月娥', 5),
   ('劉兆佳', 5),
   ('雷正龍', 3),
   ('趙立堅', 3),
   ('李希', 3),
   ('希魯阿諾夫', 3),
   ('王晟', 3),
   ('布吉敏', 2),
   ('蒲亭', 2),
   ('余永定', 2),
   ('張文宏', 2),
   ('林柏偉', 1),
   ('林伯偉', 1),
   ('黃守應', 1),
   ('王長青', 1),
   ('崔靜麟', 1),
   ('張竹君', 1),
   ('梁萬年', 1),
   ('高拔陞', 1),
   ('許樹昌', 1),
   ('鄭月娥', 1),
   ('閭丘露薇', 1),
   ('阿雷菲耶夫', 1),
   ('麥維德夫', 1),
   ('湯瑪斯（Neil Thomas）', 1),
   ('翟東升', 1),
   ('胡偉', 1),
   ('郭健安', 1),
   ('聶德權', 1),
   ('張宏文', 1),
   ('讓特', 1)]),
 ('全部',
  [('黃重凱', 24),
   ('林昀儒', 24),
   ('鄭怡靜', 24),
   ('唐川', 20),
   ('歸亞蕾', 18),
   ('莊智淵', 17),
   ('陳耀祥', 17),
   ('吳密察', 15),
   ('柳惠千', 13),
   ('陳時中', 13),
   ('彭佳偉', 13),
   ('喬建中', 12),
   ('陳將双', 12),
   ('徐國勇', 11),
   ('炎亞綸', 11),
   ('潘武雄', 10),
   ('威廉赫特', 10),
   ('平珩', 10),
   ('朱澤民', 9),
   ('季欽', 8),
   ('陳建安', 8),
   ('莊凱勛', 8),
   ('楊藜', 8),
   ('戴寧', 8),
   ('許舒博', 7),
   ('布雷迪', 7),
   ('林暉閔', 7),
   ('納豆', 7),
   ('孫道存', 7),
   ('吳蠻', 7),
   ('游錫堃', 6),
   ('侯富議', 6),
   ('林柏亨', 6),
   ('侯友宜', 6),
   ('布魯娜', 6),
   ('賈奈特', 6),
   ('艾倫', 6),
   ('吳思瑤', 6),
   ('曾博昇', 6),
   ('黃新皓', 6),
   ('珍康萍', 6),
   ('曹格', 6),
   ('鄭文燦', 6),
   ('潘孟安', 6),
   ('薛達', 6),
   ('蘇貞昌', 5),
   ('柯文哲', 5),
   ('范惠君', 5),
   ('吳偉仁', 5),
   ('塞爾蒂克', 5),
   ('李恩芯', 5),
   ('杜書全', 5),
   ('黃子佼', 5),
   ('黃恩鴻', 5),
   ('蒲亭', 5),
   ('蘇利文', 5),
   ('楊書涵', 5),
   ('李其叡', 5),
   ('張徐展', 5),
   ('林鄭月娥', 5),
   ('劉兆佳', 5),
   ('吳釗燮', 4),
   ('許佑格', 4),
   ('陳其邁', 4),
   ('歐布萊恩', 4),
   ('包淳偉', 4),
   ('黃晨瑋', 4),
   ('廖俊智', 4),
   ('王志庭', 4),
   ('施冠宇', 4),
   ('加奇尼', 4),
   ('蘇松輝', 4),
   ('百白', 4),
   ('孟耿如', 4),
   ('吳慷仁', 4),
   ('林心如', 4),
   ('楊潔篪', 4),
   ('孫芸芸', 4),
   ('蔡采崴', 4),
   ('陳智菡', 3),
   ('黃鼎翔', 3),
   ('王同義', 3),
   ('王美惠', 3),
   ('波博', 3),
   ('黃文山', 3),
   ('艾偉', 3),
   ('樂天', 3),
   ('安宰賢', 3),
   ('巴特瑞', 3),
   ('梁家榮', 3),
   ('黃子鵬', 3),
   ('高飛', 3),
   ('郭俊麟', 3),
   ('陳冠宇', 3),
   ('皮爾斯', 3),
   ('帕森斯', 3),
   ('林耕億', 3),
   ('趙正宇', 3),
   ('林崇燾', 3),
   ('童振源', 3),
   ('郭宇宸', 3),
   ('茶金', 3),
   ('温昇豪', 3),
   ('郭子乾', 3),
   ('葉如芬', 3),
   ('楊雅喆', 3),
   ('蔡英文', 3),
   ('李安', 3),
   ('謝瓊煖', 3),
   ('李宗宏', 3),
   ('阿布拉莫維奇', 3),
   ('米佐塔基斯', 3),
   ('羅傑斯', 3),
   ('波多利雅科', 3),
   ('孫瑩瑩', 3),
   ('孫智宏', 3),
   ('陳悅宜', 3),
   ('孫翠鳳', 3),
   ('朱天文', 3),
   ('顏伯駿', 3),
   ('鄭志偉', 3),
   ('朱安麗', 3),
   ('柳美', 3),
   ('大衛．胡斯', 3),
   ('雷正龍', 3),
   ('趙立堅', 3),
   ('李希', 3),
   ('希魯阿諾夫', 3),
   ('王晟', 3),
   ('許邁德', 2),
   ('蔣萬安', 2),
   ('蔡練生', 2),
   ('沈榮津', 2),
   ('王金燦', 2),
   ('陳信安', 2),
   ('庫克', 2),
   ('曾信超', 2),
   ('波皮斯庫', 2),
   ('岱縈', 2),
   ('筠熹', 2),
   ('摩賈德', 2),
   ('林鍾勳', 2),
   ('張禹珍', 2),
   ('周哲宇', 2),
   ('張志豪', 2),
   ('王威晨', 2),
   ('江國豪', 2),
   ('官大元', 2),
   ('施子謙', 2),
   ('陳思羽', 2),
   ('約爾吉奇', 2),
   ('習近平', 2),
   ('葉獻文', 2),
   ('李昌鴻', 2),
   ('郭幸容', 2),
   ('林德福', 2),
   ('吳秉叡', 2),
   ('李昆澤', 2),
   ('連俞涵', 2),
   ('桂綸鎂', 2),
   ('威爾史密斯', 2),
   ('林思宇', 2),
   ('陸夏', 2),
   ('張書豪', 2),
   ('張睿家', 2),
   ('姚愛寗', 2),
   ('江文全', 2),
   ('邱基旭', 2),
   ('蔡佩君', 2),
   ('切爾西', 2),
   ('潘恩', 2),
   ('拉夫羅夫', 2),
   ('阿布杜拉希安', 2),
   ('哈蒂柏札德', 2),
   ('奧德洛', 2),
   ('霍恩', 2),
   ('蕭茲', 2),
   ('張女', 2),
   ('陳澤嘉', 2),
   ('吳逸萍', 2),
   ('莊英壽', 2),
   ('李作宏', 2),
   ('譚盾', 2),
   ('阿儒瓦苡．篙瑪竿', 2),
   ('朱西甯', 2),
   ('李永得', 2),
   ('辜達齊', 2),
   ('黃致凱', 2),
   ('郭耀仁', 2),
   ('方志友', 2),
   ('蔡燦得', 2),
   ('陳家逵', 2),
   ('張廖萬堅', 2),
   ('楊文信', 2),
   ('林佳瑩', 2),
   ('葉澤山', 2),
   ('郭春美', 2),
   ('林曼麗', 2),
   ('戴維斯', 2),
   ('侯傳安', 2)])]