# Prepare data for Django website
     
    data = {
      "PERSON":{
        "政治":[('黃重凱', 24),
                ('柳惠千', 13),
                ('喬建中', 12),
                ('徐國勇', 11),
                ('季欽', 8),
                ('許舒博', 7),
                ('游錫堃', 6),
                ('侯富議', 6),
                ('蘇貞昌', 5),
                ('吳釗燮', 4)],
        "科技":[ ... ]
      }
    }


    data['PERSON']['政治'][0:5]

    [('黃重凱', 24),
     ('柳惠千', 13),
     ('喬建中', 12),
     ('徐國勇', 11),
     ('季欽', 8)
     ]


    We need the cloud data with the following format

    'data_cloud': [
      {'text': '江啟臣', 'size': 90},
      {'text': '林佳龍', 'size': 60},
      {'text': '王育敏', 'size': 50},
      {'text': '蔡英文', 'size': 30},
      {'text': '蔡宜芳', 'size': 30},
      {'text': '史順文', 'size': 20},
      {'text': '沈伯洋', 'size': 20},
      {'text': '佳安道', 'size': 10},
      {'text': '陳時中', 'size': 10},
      {'text': '張益贍', 'size': 10}]

# Load data

In [1]:
import pandas as pd

In [2]:
df_data = pd.read_csv('news_topkey_by_ner_and_category.csv',sep=',')

In [3]:
df_data

        ne_name                                           top_keys
0      CARDINAL  [('政治', [('2000', 7), ('4000', 2), ('13', 2), ...
1          DATE  [('政治', [('今天', 35), ('12天', 2), ('5月', 2), ('...
2         EVENT  [('政治', [('COVID-19（2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭...
3           FAC  [('政治', [('台東志航基地', 8), ('台東馬偕醫院', 5), ('新竹空軍基...
4           GPE  [('政治', [('台灣', 25), ('台東', 10), ('法國', 8), ('...
5      LANGUAGE  [('政治', [('英文', 1)]), ('科技', []), ('運動', [('中文...
6           LAW  [('政治', []), ('科技', [('LINE', 1)]), ('運動', [])...
7           LOC  [('政治', [('台灣西南防空識別區', 1), ('北美', 1), ('屯稜線', ...
8         MONEY  [('政治', [('新台幣6億元', 1), ('3萬5703美元', 1), ('約10...
9          NORP  [('政治', [('烏克蘭', 6), ('德商', 2), ('歐商', 1), ('美...
10      ORDINAL  [('政治', [('第四', 2), ('第1', 1), ('第206', 1), ('...
11          ORG  [('政治', [('外交部', 16), ('立法院', 13), ('監察院', 9),...
12      PERCENT  [('政治', [('5%', 1), ('45%', 1)]), ('科技', [('10...
13       PERSON  [('政治', [('黃重凱', 24), ('柳惠千', 13), ('喬建中', 12)...
14      PRODUCT  [('政治', [('2000', 3), ('殲16戰機', 2), ('2017', 1...
15     QUANTITY  [('政治', [('2000呎', 6), ('10浬', 5), ('80公頃', 2)...
16         TIME  [('政治', [('下午', 10), ('上午', 10), ('11時26分', 5)...
17  WORK_OF_ART  [('政治', []), ('科技', []), ('運動', []), ('證卷', []...

# prepare NER data (dict format)

In [4]:
data={}
for idx in range(len(df_data)):
    data[df_data.loc[idx,'ne_name']] = dict(eval(df_data.loc[idx, 'top_keys']))

In [5]:
data

{'CARDINAL': {'政治': [('2000', 7),
   ('4000', 2),
   ('13', 2),
   ('54', 2),
   ('1730', 1),
   ('20', 1),
   ('38', 1),
   ('16', 1),
   ('39', 1),
   ('30', 1),
   ('90', 1),
   ('10萬', 1),
   ('12', 1),
   ('11', 1),
   ('41', 1),
   ('2017', 1),
   ('2036', 1)],
  '科技': [('4.0', 4),
   ('1200萬', 3),
   ('23', 2),
   ('120萬', 2),
   ('之一', 2),
   ('64', 2),
   ('25', 1),
   ('200', 1),
   ('15', 1),
   ('1萬', 1),
   ('2.5', 1),
   ('4000', 1),
   ('20', 1),
   ('60', 1),
   ('5G', 1),
   ('30', 1),
   ('33', 1),
   ('1176', 1),
   ('一半', 1),
   ('19', 1)],
  '運動': [('16', 19),
   ('11', 19),
   ('10', 5),
   ('32', 3),
   ('22', 2),
   ('57', 2),
   ('12', 2),
   ('7萬', 1),
   ('103萬', 1),
   ('31', 1),
   ('91', 1),
   ('128', 1),
   ('84', 1),
   ('92', 1),
   ('95', 1),
   ('四分', 1),
   ('20', 1),
   ('48', 1),
   ('18', 1),
   ('21', 1)],
  '證卷': [('50', 6),
   ('10', 4),
   ('十名', 2),
   ('505', 1),
   ('1287', 1),
   ('一半', 1),
   ('11', 1),
   ('29', 1),
   ('2名', 1),
   ('6.32倍', 1),
   ('1.85', 1),
   ('12.7倍', 1),
   ('13倍', 1),
   ('1.9倍', 1),
   ('1452萬4527', 1),
   ('633萬7576', 1),
   ('486', 1),
   ('367', 1),
   ('130', 1),
   ('5名', 1)],
  '產經': [('上億', 2),
   ('24', 1),
   ('2.0', 1),
   ('21', 1),
   ('2400萬', 1),
   ('60多', 1),
   ('66', 1),
   ('50萬顆', 1),
   ('147', 1),
   ('4萬多', 1),
   ('2600', 1),
   ('4000', 1)],
  '娛樂': [('200多', 2), ('2000萬', 1), ('三百', 1), ('10幾', 1)],
  '生活': [('17', 6),
   ('14', 5),
   ('23', 4),
   ('04', 4),
   ('13', 3),
   ('12', 3),
   ('2400', 3),
   ('2019', 2),
   ('19', 2),
   ('10', 2),
   ('16', 2),
   ('663', 2),
   ('20', 2),
   ('18', 2),
   ('07', 2),
   ('06', 2),
   ('11', 2),
   ('02', 2),
   ('08', 2),
   ('15', 2)],
  '國際': [('3萬', 1),
   ('200', 1),
   ('50', 1),
   ('之一', 1),
   ('4836', 1),
   ('5000', 1),
   ('500', 1),
   ('8631.9', 1),
   ('64', 1),
   ('17', 1),
   ('35', 1)],
  '社會': [('360萬', 2),
   ('68', 2),
   ('17', 1),
   ('50', 1),
   ('10', 1),
   ('200餘', 1),
   ('千萬', 1),
   ('一半', 1),
   ('44', 1),
   ('百餘', 1),
   ('317', 1),
   ('18', 1),
   ('43', 1)],
  '文化': [('10', 3),
   ('130', 1),
   ('30', 1),
   ('上萬', 1),
   ('15', 1),
   ('之一', 1),
   ('25', 1),
   ('100', 1),
   ('20', 1),
   ('1億', 1),
   ('70萬', 1),
   ('1萬多', 1),
   ('69萬多', 1),
   ('一半', 1),
   ('200多', 1),
   ('500', 1)],
  '兩岸': [('2019', 3),
   ('75', 3),
   ('300', 3),
   ('4000', 2),
   ('10', 2),
   ('100萬', 2),
   ('119', 2),
   ('約1000', 2),
   ('3.2萬', 2),
   ('1萬', 2),
   ('3993', 2),
   ('1337', 2),
   ('895', 2),
   ('2266', 2),
   ('1萬餘', 1),
   ('27', 1),
   ('31個', 1),
   ('19', 1),
   ('1萬4868', 1),
   ('72萬', 1)],
  '全部': [('16', 23),
   ('11', 23),
   ('10', 17),
   ('2000', 8),
   ('50', 8),
   ('17', 8),
   ('4000', 6),
   ('20', 6),
   ('12', 6),
   ('23', 6),
   ('13', 5),
   ('之一', 5),
   ('2019', 5),
   ('14', 5),
   ('30', 4),
   ('15', 4),
   ('1萬', 4),
   ('一半', 4),
   ('19', 4),
   ('4.0', 4)]},
 'DATE': {'政治': [('今天', 35),
   ('12天', 2),
   ('5月', 2),
   ('同年12月', 2),
   ('4個月', 2),
   ('一年', 2),
   ('7日', 1),
   ('18日', 1),
   ('6個月', 1),
   ('3月18日', 1),
   ('民國109年', 1),
   ('11日', 1),
   ('近年', 1),
   ('20年', 1),
   ('當年', 1),
   ('民國109年9月17日', 1),
   ('110年10月1日', 1),
   ('同年10月2日', 1),
   ('10月3日', 1),
   ('10月4日', 1)],
  '科技': [('今天', 27),
   ('18日', 6),
   ('1月', 4),
   ('11日', 4),
   ('春季', 4),
   ('去年4月', 2),
   ('2016年', 2),
   ('去年10月', 2),
   ('2030年', 2),
   ('2023年底', 2),
   ('今年', 2),
   ('下週', 2),
   ('多年來', 2),
   ('1年', 2),
   ('3月23日', 2),
   ('2020年12月', 1),
   ('過去一年', 1),
   ('上個月', 1),
   ('9日', 1),
   ('2018年4月', 1)],
  '運動': [('今天', 47),
   ('今年', 9),
   ('昨天', 8),
   ('去年', 4),
   ('2年', 4),
   ('7日至20日', 4),
   ('一年', 4),
   ('40歲', 3),
   ('上個月', 2),
   ('一日', 2),
   ('2008年', 2),
   ('冬季', 2),
   ('11日', 1),
   ('27日', 1),
   ('105年', 1),
   ('10年', 1),
   ('109年', 1),
   ('去年11月底', 1),
   ('近4個月', 1),
   ('年底', 1)],
  '證卷': [('今天', 36),
   ('去年', 24),
   ('今年', 12),
   ('2021年', 11),
   ('3月', 11),
   ('2020年', 7),
   ('2月', 6),
   ('前2月', 4),
   ('4月', 4),
   ('10年', 3),
   ('本週', 3),
   ('2022年', 3),
   ('12個月', 2),
   ('去年10月', 2),
   ('14日', 2),
   ('今年前2月', 2),
   ('2019年', 2),
   ('2021年度', 2),
   ('2個月', 2),
   ('明天', 1)],
  '產經': [('今天', 30),
   ('今年', 23),
   ('去年', 16),
   ('前年', 4),
   ('上週', 2),
   ('3月15日', 2),
   ('3月底', 2),
   ('2021年', 2),
   ('第1季', 2),
   ('農曆年', 2),
   ('全年', 1),
   ('這2年', 1),
   ('去年12月', 1),
   ('今年3月1日', 1),
   ('7個', 1),
   ('2017年至今', 1),
   ('2019年', 1),
   ('2019', 1),
   ('11日', 1),
   ('今年一月', 1)],
  '娛樂': [('今天', 26),
   ('昨天', 7),
   ('去年', 5),
   ('2月', 4),
   ('5月', 3),
   ('今年', 3),
   ('13日', 3),
   ('38歲', 3),
   ('34歲', 3),
   ('41歲', 2),
   ('69歲', 2),
   ('近年', 2),
   ('1983年', 2),
   ('50多年', 2),
   ('1月', 1),
   ('今年1月24日', 1),
   ('一年', 1),
   ('半世紀', 1),
   ('10年', 1),
   ('前幾天', 1)],
  '生活': [('今天', 22),
   ('7天', 6),
   ('10天', 4),
   ('3月7日', 4),
   ('5天', 3),
   ('5月', 3),
   ('近年', 3),
   ('2012年', 3),
   ('去年', 3),
   ('11日', 3),
   ('17日', 3),
   ('3天', 2),
   ('未來一個多月', 2),
   ('2019年', 2),
   ('18日', 2),
   ('4月', 2),
   ('2019', 2),
   ('3月', 1),
   ('7月', 1),
   ('1110314', 1)],
  '國際': [('今天', 28),
   ('昨天', 5),
   ('2015年', 3),
   ('上週', 3),
   ('14日', 2),
   ('2014年', 1),
   ('15日', 1),
   ('明天', 1),
   ('2018年', 1),
   ('10個多月', 1),
   ('5日', 1),
   ('11日', 1),
   ('2022年', 1),
   ('2年', 1),
   ('3月14日至4月1日', 1),
   ('今年', 1),
   ('4月', 1),
   ('本週', 1),
   ('16日', 1),
   ('數年', 1)],
  '社會': [('今天', 33),
   ('昨天', 4),
   ('3年', 4),
   ('10日', 3),
   ('日前', 2),
   ('明天', 2),
   ('3月', 2),
   ('30日', 2),
   ('9日', 2),
   ('12日', 2),
   ('去年11月', 2),
   ('1年6月', 2),
   ('2023年', 2),
   ('108年', 2),
   ('8歲', 2),
   ('40歲', 1),
   ('5年', 1),
   ('108年5月18日', 1),
   ('40日', 1),
   ('108年9月', 1)],
  '文化': [('今天', 20),
   ('今年', 11),
   ('7月', 3),
   ('6日', 3),
   ('去年', 2),
   ('26日', 2),
   ('21世紀', 2),
   ('2019年', 2),
   ('3個月', 2),
   ('未來3個月', 2),
   ('2021年', 2),
   ('百年', 2),
   ('日治時期', 2),
   ('40年', 1),
   ('2020年', 1),
   ('1980年', 1),
   ('年度', 1),
   ('近年', 1),
   ('3月15日', 1),
   ('11日', 1)],
  '兩岸': [('今天', 28),
   ('13日', 9),
   ('7天', 6),
   ('昨天', 4),
   ('今日', 3),
   ('14天', 3),
   ('2020年5月', 2),
   ('11日', 2),
   ('近日', 2),
   ('14日', 2),
   ('2019年', 2),
   ('近年', 2),
   ('本週', 2),
   ('今年', 2),
   ('2至3週', 2),
   ('10幾年', 1),
   ('1日', 1),
   ('3月1日至13日', 1),
   ('6年', 1),
   ('2019年底', 1)],
  '全部': [('今天', 332),
   ('今年', 66),
   ('去年', 57),
   ('昨天', 28),
   ('2021年', 19),
   ('11日', 15),
   ('2月', 15),
   ('3月', 14),
   ('13日', 13),
   ('18日', 12),
   ('7天', 12),
   ('4月', 11),
   ('2020年', 11),
   ('2019年', 11),
   ('近年', 10),
   ('5月', 9),
   ('2年', 8),
   ('14日', 8),
   ('一年', 7),
   ('1月', 7)]},
 'EVENT': {'政治': [('COVID-19（2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭', 1)],
  '科技': [],
  '運動': [('帕運會', 3),
   ('奧運', 2),
   ('東京奧運', 1),
   ('超級盃', 1),
   ('去年東京奧運', 1),
   ('帕運', 1)],
  '證卷': [],
  '產經': [('俄烏戰爭', 5), ('俄烏戰事', 1)],
  '娛樂': [],
  '生活': [('COVID-19', 1)],
  '國際': [('烏克蘭戰爭', 2), ('COVID-19', 1), ('2019', 1)],
  '社會': [],
  '文化': [('雪梨雙年展', 4),
   ('第23屆雪梨雙年展', 2),
   ('2019', 1),
   ('百老匯', 1),
   ('高雄春天藝術節', 1),
   ('2022年高雄春天藝術節', 1),
   ('2019冠狀病毒疾病', 1),
   ('百週年慶', 1)],
  '兩岸': [('東莞市疫情防控指揮辦', 1), ('2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭', 1)],
  '全部': [('俄烏戰爭', 7),
   ('雪梨雙年展', 4),
   ('帕運會', 3),
   ('奧運', 2),
   ('COVID-19', 2),
   ('烏克蘭戰爭', 2),
   ('2019', 2),
   ('第23屆雪梨雙年展', 2),
   ('COVID-19（2019冠狀病毒疾病）疫情', 1),
   ('東京奧運', 1),
   ('超級盃', 1),
   ('去年東京奧運', 1),
   ('帕運', 1),
   ('俄烏戰事', 1),
   ('百老匯', 1),
   ('高雄春天藝術節', 1),
   ('2022年高雄春天藝術節', 1),
   ('2019冠狀病毒疾病', 1),
   ('百週年慶', 1),
   ('東莞市疫情防控指揮辦', 1)]},
 'FAC': {'政治': [('台東志航基地', 8),
   ('台東馬偕醫院', 5),
   ('新竹空軍基地', 4),
   ('新竹基地', 4),
   ('志航基地', 3),
   ('玉山國家公園', 2),
   ('君悅酒店', 1),
   ('台南空軍基地', 1),
   ('盧賽基地', 1)],
  '科技': [('科博館', 3), ('國立自然科學博物館', 1)],
  '運動': [('新加坡華僑銀行室內體育館', 3),
   ('台南市立棒球場', 2),
   ('嘉義縣立棒球場體驗球場', 1),
   ('斗六棒球場', 1),
   ('立棒球場', 1),
   ('OCBC Arena', 1),
   ('國家體育場', 1),
   ('鳥巢', 1)],
  '證卷': [],
  '產經': [('長春廠', 1)],
  '娛樂': [('鶯歌後村堰遙控飛機場', 1), ('台灣會館', 1)],
  '生活': [],
  '國際': [],
  '社會': [('家樂福', 2),
   ('楊梅物流中心', 2),
   ('竹東火車站', 1),
   ('永明派出所', 1),
   ('桃機東變電站', 1),
   ('桃機西變電站', 1),
   ('高寮夜景公園', 1),
   ('家樂福倉儲', 1),
   ('美福倉儲', 1),
   ('楊梅', 1),
   ('桃園楊梅', 1),
   ('大園', 1),
   ('高雄岡山倉庫', 1),
   ('桃園大園', 1)],
  '文化': [('明華園', 6),
   ('衛武營音樂廳', 3),
   ('千禧公園', 2),
   ('衛武營', 2),
   ('新莊聯合辦公大樓', 1),
   ('屏東智慧農業學校', 1),
   ('南華微光', 1),
   ('南華校園', 1),
   ('高雄衛武營', 1),
   ('台南文化中心', 1),
   ('台中國家歌劇院', 1),
   ('台北國家戲劇院', 1),
   ('利沃夫博物館', 1),
   ('伊萬基夫歷史博物館', 1),
   ('哈爾科夫藝術博物館', 1),
   ('易北愛樂小廳', 1),
   ('柏林愛樂室內樂廳', 1),
   ('項鍊工作室', 1),
   ('大衛．胡斯', 1),
   ('台中國家歌劇院大劇院', 1)],
  '兩岸': [('安老院', 1)],
  '全部': [('台東志航基地', 8),
   ('明華園', 6),
   ('台東馬偕醫院', 5),
   ('新竹空軍基地', 4),
   ('新竹基地', 4),
   ('志航基地', 3),
   ('科博館', 3),
   ('新加坡華僑銀行室內體育館', 3),
   ('衛武營音樂廳', 3),
   ('玉山國家公園', 2),
   ('台南市立棒球場', 2),
   ('家樂福', 2),
   ('楊梅物流中心', 2),
   ('千禧公園', 2),
   ('衛武營', 2),
   ('君悅酒店', 1),
   ('台南空軍基地', 1),
   ('盧賽基地', 1),
   ('國立自然科學博物館', 1),
   ('嘉義縣立棒球場體驗球場', 1)]},
 'GPE': {'政治': [('台灣', 25),
   ('台東', 10),
   ('法國', 8),
   ('烏克蘭', 5),
   ('高雄', 5),
   ('澳洲', 5),
   ('德國', 4),
   ('雪梨', 4),
   ('新竹', 3),
   ('美國', 2),
   ('大陸', 2),
   ('高雄市', 2),
   ('台北', 2),
   ('中國', 2),
   ('台澳', 2),
   ('英國', 1),
   ('南台灣', 1),
   ('北市', 1),
   ('澳大利亞', 1),
   ('嘉義', 1)],
  '科技': [('台灣', 23),
   ('俄羅斯', 13),
   ('烏克蘭', 7),
   ('印度', 5),
   ('中國', 5),
   ('德國', 5),
   ('美國', 4),
   ('日本', 2),
   ('台北', 2),
   ('中華民國', 1),
   ('亞美尼亞', 1),
   ('亞塞拜然', 1),
   ('愛沙尼亞', 1),
   ('喬治亞', 1),
   ('匈牙利', 1),
   ('拉脫維亞', 1),
   ('立陶宛', 1),
   ('波蘭', 1),
   ('羅馬尼亞', 1),
   ('斯洛伐克', 1)],
  '運動': [('台灣', 13),
   ('新加坡', 10),
   ('巴西', 6),
   ('印度', 5),
   ('中國', 5),
   ('瑞典', 4),
   ('韓國', 4),
   ('台南', 3),
   ('克羅埃西亞', 3),
   ('新竹市', 2),
   ('南韓', 2),
   ('嘉義縣', 2),
   ('日本', 2),
   ('斯洛維尼亞', 2),
   ('北京', 2),
   ('烏克蘭', 2),
   ('淡水', 2),
   ('台中市', 1),
   ('旅美', 1),
   ('美國', 1)],
  '證卷': [('台灣', 18),
   ('台股', 15),
   ('台北', 4),
   ('烏克蘭', 2),
   ('中國大陸', 2),
   ('日本', 2),
   ('美股', 2),
   ('中國', 1),
   ('美國', 1),
   ('日股', 1)],
  '產經': [('台灣', 22),
   ('中國', 12),
   ('俄羅斯', 7),
   ('烏克蘭', 6),
   ('深圳', 4),
   ('深圳市', 3),
   ('俄烏', 2),
   ('吉林省', 2),
   ('長春市', 2),
   ('日本', 2),
   ('天津市', 2),
   ('台北', 2),
   ('美國', 2),
   ('廣東省', 2),
   ('紐約西德州', 1),
   ('西德州', 1),
   ('倫敦', 1),
   ('北海布倫特', 1),
   ('上海', 1),
   ('中國大陸', 1)],
  '娛樂': [('台灣', 11),
   ('美國', 10),
   ('英國', 9),
   ('香港', 5),
   ('洛杉磯', 4),
   ('南庄', 3),
   ('新北', 2),
   ('烏克蘭', 2),
   ('紐約', 2),
   ('台北', 2),
   ('法國', 1),
   ('德國', 1),
   ('日本', 1),
   ('加拿大', 1),
   ('新竹', 1),
   ('彰化', 1),
   ('屏東', 1),
   ('花蓮', 1),
   ('紐西蘭', 1),
   ('倫敦', 1)],
  '生活': [('台灣', 4),
   ('台北', 3),
   ('彰化縣', 2),
   ('中國', 2),
   ('南投縣名間鄉', 1),
   ('雲林縣', 1),
   ('金門', 1),
   ('新埔站', 1),
   ('苗栗縣', 1),
   ('員林市', 1),
   ('中華', 1),
   ('中壢', 1),
   ('香港', 1),
   ('深圳市', 1),
   ('東莞市', 1),
   ('台北市', 1),
   ('桃園市', 1),
   ('菲律賓', 1),
   ('越南', 1),
   ('泰國', 1)],
  '國際': [('俄羅斯', 23),
   ('俄國', 23),
   ('烏克蘭', 16),
   ('香港', 14),
   ('印度', 12),
   ('台灣', 12),
   ('美國', 10),
   ('德國', 10),
   ('伊朗', 9),
   ('莫斯科', 9),
   ('中國', 9),
   ('挪威', 7),
   ('日本', 7),
   ('澳洲', 4),
   ('英國', 3),
   ('俄方', 3),
   ('土耳其', 3),
   ('福井縣', 3),
   ('雪梨', 2),
   ('卡達', 2)],
  '社會': [('台灣', 4),
   ('義大利', 3),
   ('嘉義市', 2),
   ('高雄', 2),
   ('中國', 2),
   ('廣東', 2),
   ('台中', 2),
   ('桃園市', 2),
   ('苗栗縣', 1),
   ('通霄鎮', 1),
   ('新竹縣', 1),
   ('嘉義', 1),
   ('台中市', 1),
   ('神岡區', 1),
   ('花東', 1),
   ('東河鄉', 1),
   ('台東', 1),
   ('台東縣東河鄉', 1),
   ('財政部', 1),
   ('林口區', 1)],
  '文化': [('台灣', 30),
   ('高雄', 14),
   ('烏克蘭', 7),
   ('屏東', 6),
   ('德國', 6),
   ('美國', 5),
   ('柏林', 5),
   ('台南', 4),
   ('俄羅斯', 3),
   ('紐約', 2),
   ('屏東市', 2),
   ('新莊', 2),
   ('高雄市', 2),
   ('台北', 2),
   ('日本', 2),
   ('西班牙', 1),
   ('澳洲', 1),
   ('捷克布拉格', 1),
   ('俄國', 1),
   ('嘉義縣', 1)],
  '兩岸': [('中國', 90),
   ('香港', 69),
   ('俄羅斯', 22),
   ('北京', 19),
   ('深圳', 18),
   ('東莞', 16),
   ('港府', 14),
   ('美國', 13),
   ('台灣', 10),
   ('東莞市', 8),
   ('美方', 7),
   ('廣東', 3),
   ('上海', 3),
   ('廣東省', 3),
   ('吉林市', 3),
   ('澳門', 2),
   ('中方', 2),
   ('深圳市', 2),
   ('封城', 2),
   ('中港', 2)],
  '全部': [('台灣', 172),
   ('中國', 129),
   ('香港', 89),
   ('俄羅斯', 70),
   ('烏克蘭', 48),
   ('美國', 48),
   ('俄國', 27),
   ('德國', 26),
   ('深圳', 24),
   ('北京', 23),
   ('印度', 22),
   ('高雄', 21),
   ('台北', 19),
   ('日本', 18),
   ('英國', 17),
   ('東莞', 16),
   ('台股', 15),
   ('港府', 14),
   ('新加坡', 13),
   ('法國', 12)]},
 'LANGUAGE': {'政治': [('英文', 1)],
  '科技': [],
  '運動': [('中文', 1)],
  '證卷': [],
  '產經': [],
  '娛樂': [('華語', 1), ('英文', 1)],
  '生活': [],
  '國際': [],
  '社會': [],
  '文化': [('客家話', 1), ('閩南語', 1), ('日語', 1), ('吳儂軟語', 1)],
  '兩岸': [('英文', 2)],
  '全部': [('英文', 4),
   ('中文', 1),
   ('華語', 1),
   ('客家話', 1),
   ('閩南語', 1),
   ('日語', 1),
   ('吳儂軟語', 1)]},
 'LAW': {'政治': [],
  '科技': [('LINE', 1)],
  '運動': [],
  '證卷': [],
  '產經': [],
  '娛樂': [],
  '生活': [],
  '國際': [('國安法', 2), ('北約憲章第5條', 1)],
  '社會': [],
  '文化': [],
  '兩岸': [('香港國安法', 1), ('外國公司問責法', 1)],
  '全部': [('國安法', 2),
   ('LINE', 1),
   ('北約憲章第5條', 1),
   ('香港國安法', 1),
   ('外國公司問責法', 1)]},
 'LOC': {'政治': [('台灣西南防空識別區', 1),
   ('北美', 1),
   ('屯稜線', 1),
   ('丹大溪', 1),
   ('巒大溪', 1),
   ('郡大溪', 1)],
  '科技': [('南極', 7), ('月球', 5), ('月球南極', 1), ('太陽系', 1)],
  '運動': [],
  '證卷': [('亞洲', 1)],
  '產經': [('歐洲', 12), ('東北', 1), ('塞港', 1)],
  '娛樂': [('神仙谷', 3), ('北美', 1), ('溪谷', 1)],
  '生活': [('東半部', 2), ('東北', 1), ('東南風', 1), ('馬祖地區', 1), ('基隆港', 1)],
  '國際': [('亞洲', 2),
   ('北極', 1),
   ('北歐', 1),
   ('博斯普魯斯海峽', 1),
   ('太平洋', 1),
   ('歐洲', 1)],
  '社會': [('高雄港', 1), ('陽明山', 1), ('中山區中山北路', 1), ('楊梅區', 1)],
  '文化': [('歐洲', 2),
   ('亞洲', 1),
   ('大海', 1),
   ('北美', 1),
   ('東海岸', 1),
   ('台南山', 1),
   ('東南亞', 1)],
  '兩岸': [('美東', 1), ('特別行政區', 1)],
  '全部': [('歐洲', 15),
   ('南極', 7),
   ('月球', 5),
   ('亞洲', 4),
   ('北美', 3),
   ('神仙谷', 3),
   ('東北', 2),
   ('東半部', 2),
   ('台灣西南防空識別區', 1),
   ('屯稜線', 1),
   ('丹大溪', 1),
   ('巒大溪', 1),
   ('郡大溪', 1),
   ('月球南極', 1),
   ('太陽系', 1),
   ('塞港', 1),
   ('溪谷', 1),
   ('東南風', 1),
   ('馬祖地區', 1),
   ('基隆港', 1)]},
 'MONEY': {'政治': [('新台幣6億元', 1),
   ('3萬5703美元', 1),
   ('約101萬元', 1),
   ('3萬5703', 1),
   ('新台幣約101萬元', 1),
   ('4億7222萬元', 1),
   ('1億3788萬元', 1)],
  '科技': [('1萬3900元', 5),
   ('1萬7900元', 3),
   ('1萬5500元', 2),
   ('1萬9000元', 2),
   ('3999美元', 2),
   ('新台幣60億元', 1),
   ('新台幣', 1),
   ('5萬9900元', 1),
   ('4萬5900元', 1),
   ('1.79萬元', 1),
   ('2萬2900元', 1),
   ('429美元', 1),
   ('399美元', 1),
   ('1999美元', 1),
   ('1599美元', 1),
   ('599美元', 1)],
  '運動': [('200萬美元', 4), ('十元', 1)],
  '證卷': [('新台幣2861.6億元', 4),
   ('0.1元', 4),
   ('20元', 3),
   ('132.5元', 3),
   ('7元', 2),
   ('4.5元', 2),
   ('1.31元', 2),
   ('1.93億元', 2),
   ('46.23元', 2),
   ('26元', 2),
   ('3億元', 2),
   ('16.04億元', 2),
   ('142.43億元', 2),
   ('新台幣2億元', 2),
   ('0.6元', 2),
   ('0.7元', 2),
   ('0.67元', 2),
   ('4.7億元', 2),
   ('1.52元', 2),
   ('164.5元', 1)],
  '產經': [('430億歐元', 3),
   ('28.53元', 2),
   ('28.450元', 2),
   ('28.420元', 2),
   ('28.534元', 2),
   ('1.01元', 2),
   ('新台幣4000億元', 1),
   ('173億元', 1),
   ('10.35元', 1),
   ('5元', 1),
   ('新台幣38.84億元', 1),
   ('1.3元', 1),
   ('0.65元', 1),
   ('0.5元', 1),
   ('新台幣2000萬元', 1),
   ('2000萬元', 1),
   ('2.02億元', 1),
   ('103.80美元', 1),
   ('108.13美元', 1),
   ('新台幣2千萬元', 1)],
  '娛樂': [('2000萬元', 1)],
  '生活': [('2元', 4),
   ('新台幣2萬元', 1),
   ('1萬2500元', 1),
   ('12萬5000元', 1),
   ('新台幣10萬元', 1),
   ('12億餘元', 1),
   ('新台幣3元', 1),
   ('38.5元', 1),
   ('48元', 1),
   ('新台幣575萬元', 1),
   ('50萬元', 1),
   ('575萬元', 1)],
  '國際': [('1490億印度盧比', 1), ('19.4億美元', 1)],
  '社會': [('80萬元', 5),
   ('新台幣6萬7500元', 2),
   ('600元', 2),
   ('10萬元', 2),
   ('30萬元', 2),
   ('500萬元', 2),
   ('新台幣3萬元', 1),
   ('新台幣500萬元', 1),
   ('200億元', 1),
   ('新台幣200億元', 1),
   ('12餘億元', 1),
   ('新台幣9萬元', 1),
   ('9萬元', 1),
   ('新台幣1000萬元', 1),
   ('35元', 1),
   ('1000萬元', 1),
   ('新台幣600元', 1),
   ('2500萬元', 1),
   ('200萬元', 1),
   ('新台幣80萬元', 1)],
  '文化': [('新台幣385萬元', 1), ('新台幣2700萬元', 1)],
  '兩岸': [('80.9港元', 1),
   ('8港元', 1),
   ('6400億美元', 1),
   ('約17兆新台幣', 1),
   ('約12.6兆新台幣', 1)],
  '全部': [('1萬3900元', 5),
   ('80萬元', 5),
   ('200萬美元', 4),
   ('新台幣2861.6億元', 4),
   ('0.1元', 4),
   ('2元', 4),
   ('1萬7900元', 3),
   ('20元', 3),
   ('132.5元', 3),
   ('3億元', 3),
   ('430億歐元', 3),
   ('新台幣', 2),
   ('1萬5500元', 2),
   ('1萬9000元', 2),
   ('3999美元', 2),
   ('7元', 2),
   ('4.5元', 2),
   ('1.31元', 2),
   ('1.93億元', 2),
   ('46.23元', 2)]},
 'NORP': {'政治': [('烏克蘭', 6),
   ('德商', 2),
   ('歐商', 1),
   ('美商', 1),
   ('日商', 1),
   ('中商', 1),
   ('法方', 1)],
  '科技': [('奧斯汀', 1), ('台灣', 1)],
  '運動': [('泰雅族', 1), ('捷克', 1), ('淡商', 1)],
  '證卷': [],
  '產經': [('台商', 5)],
  '娛樂': [('華裔', 2),
   ('北埔人', 1),
   ('英國', 1),
   ('台灣人', 1),
   ('香港', 1),
   ('香港人', 1),
   ('烏克蘭', 1),
   ('烏克蘭人', 1),
   ('歐洲人', 1),
   ('中華', 1),
   ('美籍', 1),
   ('美國', 1)],
  '生活': [('印尼籍', 2)],
  '國際': [('俄國', 1)],
  '社會': [('台灣', 1), ('富商', 1)],
  '文化': [('台灣', 6),
   ('排灣族', 2),
   ('中國', 2),
   ('台裔', 2),
   ('鄒族', 1),
   ('德國', 1),
   ('華人', 1),
   ('台籍', 1),
   ('阿美族', 1),
   ('日本', 1),
   ('美籍', 1),
   ('英國', 1)],
  '兩岸': [('港人', 3),
   ('台籍', 1),
   ('中國', 1),
   ('港媒', 1),
   ('陸媒', 1),
   ('台資', 1),
   ('中文', 1),
   ('中國人', 1)],
  '全部': [('台灣', 8),
   ('烏克蘭', 7),
   ('台商', 5),
   ('中國', 3),
   ('港人', 3),
   ('德商', 2),
   ('英國', 2),
   ('華裔', 2),
   ('美籍', 2),
   ('印尼籍', 2),
   ('排灣族', 2),
   ('台裔', 2),
   ('台籍', 2),
   ('歐商', 1),
   ('美商', 1),
   ('日商', 1),
   ('中商', 1),
   ('法方', 1),
   ('奧斯汀', 1),
   ('泰雅族', 1)]},
 'ORDINAL': {'政治': [('第四', 2),
   ('第1', 1),
   ('第206', 1),
   ('第8', 1),
   ('第60', 1),
   ('第一', 1),
   ('第二', 1),
   ('第三', 1),
   ('第五', 1),
   ('第六', 1)],
  '科技': [('第3', 6), ('第5', 4), ('第4', 3), ('第一', 2), ('第三', 1), ('第二', 1)],
  '運動': [('第3', 9),
   ('第一', 4),
   ('第2', 4),
   ('第4', 3),
   ('29', 1),
   ('第24', 1),
   ('第45', 1),
   ('第23', 1),
   ('第二', 1),
   ('第7', 1)],
  '證卷': [('第4', 1)],
  '產經': [('第20', 1), ('第一', 1), ('第2', 1), ('第15', 1), ('第27', 1)],
  '娛樂': [('第一', 5), ('第三', 3), ('第49', 1), ('第44', 1)],
  '生活': [('第一', 3),
   ('第二', 3),
   ('第九', 2),
   ('第11102', 1),
   ('第111062', 1),
   ('第三', 1)],
  '國際': [('第4', 2), ('第一', 2)],
  '社會': [('第2', 2),
   ('第一', 2),
   ('第3', 1),
   ('第三', 1),
   ('第4', 1),
   ('第1', 1),
   ('第一時間', 1)],
  '文化': [('第一', 9),
   ('第3', 2),
   ('第33', 1),
   ('第一時間', 1),
   ('首次', 1),
   ('第9', 1),
   ('第15', 1),
   ('第6', 1),
   ('第2', 1),
   ('第五', 1),
   ('第四', 1)],
  '兩岸': [('第5', 8), ('第一', 2), ('第3', 2), ('第二', 1), ('第三', 1)],
  '全部': [('第一', 31),
   ('第3', 20),
   ('第5', 12),
   ('第4', 10),
   ('第三', 8),
   ('第2', 8),
   ('第二', 7),
   ('第四', 3),
   ('第1', 2),
   ('第五', 2),
   ('第15', 2),
   ('第九', 2),
   ('第一時間', 2),
   ('第206', 1),
   ('第8', 1),
   ('第60', 1),
   ('第六', 1),
   ('29', 1),
   ('第24', 1),
   ('第45', 1)]},
 'ORG': {'政治': [('外交部', 16),
   ('立法院', 13),
   ('監察院', 9),
   ('行政院', 8),
   ('國防部', 7),
   ('內政部', 6),
   ('中央社', 5),
   ('國民黨', 4),
   ('CPTPP', 4),
   ('工總', 3),
   ('空軍', 3),
   ('中央', 2),
   ('政府', 2),
   ('北市府', 2),
   ('澳洲國會', 2),
   ('紐約台灣商會', 2),
   ('空軍司令部', 2),
   ('外交部長', 1),
   ('慈濟', 1),
   ('國防安全研究院', 1)],
  '科技': [('蘋果', 20),
   ('中研院', 6),
   ('宏達電', 3),
   ('中央社', 3),
   ('台灣海洋科技研究中心', 2),
   ('印度科技部', 2),
   ('Meta', 2),
   ('路透社', 2),
   ('國研院', 2),
   ('太空中心', 2),
   ('Tim哥', 2),
   ('敏實科技大學', 2),
   ('LINE', 2),
   ('印度理工學院', 1),
   ('海洋中心', 1),
   ('印度理工學院古瓦哈蒂分校', 1),
   ('科技部', 1),
   ('TIHs', 1),
   ('國研院國網中心', 1),
   ('印度理工學院堪坡校區', 1)],
  '運動': [('獅隊', 11),
   ('桃猿隊', 9),
   ('兄弟', 6),
   ('中央社', 5),
   ('桃猿', 5),
   ('南山高中', 4),
   ('世界桌球職業大聯盟', 4),
   ('味全龍隊', 4),
   ('統一獅隊', 3),
   ('台北興富發隊', 3),
   ('平等國小', 2),
   ('OCBC Arena', 2),
   ('統一', 2),
   ('綠衫軍', 2),
   ('光復高中', 1),
   ('平等國民小學女籃隊', 1),
   ('台北金華國中', 1),
   ('中華', 1),
   ('皇家隊', 1),
   ('興富發隊', 1)],
  '證卷': [('陽明', 9),
   ('揚弈科技', 8),
   ('友通', 7),

In [6]:
# Alternative way
data={}
for idx, (nerName, topKeys) in df_data.iterrows():
    data[nerName] = dict(eval(topKeys))

In [7]:
data

{'CARDINAL': {'政治': [('2000', 7),
   ('4000', 2),
   ('13', 2),
   ('54', 2),
   ('1730', 1),
   ('20', 1),
   ('38', 1),
   ('16', 1),
   ('39', 1),
   ('30', 1),
   ('90', 1),
   ('10萬', 1),
   ('12', 1),
   ('11', 1),
   ('41', 1),
   ('2017', 1),
   ('2036', 1)],
  '科技': [('4.0', 4),
   ('1200萬', 3),
   ('23', 2),
   ('120萬', 2),
   ('之一', 2),
   ('64', 2),
   ('25', 1),
   ('200', 1),
   ('15', 1),
   ('1萬', 1),
   ('2.5', 1),
   ('4000', 1),
   ('20', 1),
   ('60', 1),
   ('5G', 1),
   ('30', 1),
   ('33', 1),
   ('1176', 1),
   ('一半', 1),
   ('19', 1)],
  '運動': [('16', 19),
   ('11', 19),
   ('10', 5),
   ('32', 3),
   ('22', 2),
   ('57', 2),
   ('12', 2),
   ('7萬', 1),
   ('103萬', 1),
   ('31', 1),
   ('91', 1),
   ('128', 1),
   ('84', 1),
   ('92', 1),
   ('95', 1),
   ('四分', 1),
   ('20', 1),
   ('48', 1),
   ('18', 1),
   ('21', 1)],
  '證卷': [('50', 6),
   ('10', 4),
   ('十名', 2),
   ('505', 1),
   ('1287', 1),
   ('一半', 1),
   ('11', 1),
   ('29', 1),
   ('2名', 1),
   ('6.32倍', 1),
   ('1.85', 1),
   ('12.7倍', 1),
   ('13倍', 1),
   ('1.9倍', 1),
   ('1452萬4527', 1),
   ('633萬7576', 1),
   ('486', 1),
   ('367', 1),
   ('130', 1),
   ('5名', 1)],
  '產經': [('上億', 2),
   ('24', 1),
   ('2.0', 1),
   ('21', 1),
   ('2400萬', 1),
   ('60多', 1),
   ('66', 1),
   ('50萬顆', 1),
   ('147', 1),
   ('4萬多', 1),
   ('2600', 1),
   ('4000', 1)],
  '娛樂': [('200多', 2), ('2000萬', 1), ('三百', 1), ('10幾', 1)],
  '生活': [('17', 6),
   ('14', 5),
   ('23', 4),
   ('04', 4),
   ('13', 3),
   ('12', 3),
   ('2400', 3),
   ('2019', 2),
   ('19', 2),
   ('10', 2),
   ('16', 2),
   ('663', 2),
   ('20', 2),
   ('18', 2),
   ('07', 2),
   ('06', 2),
   ('11', 2),
   ('02', 2),
   ('08', 2),
   ('15', 2)],
  '國際': [('3萬', 1),
   ('200', 1),
   ('50', 1),
   ('之一', 1),
   ('4836', 1),
   ('5000', 1),
   ('500', 1),
   ('8631.9', 1),
   ('64', 1),
   ('17', 1),
   ('35', 1)],
  '社會': [('360萬', 2),
   ('68', 2),
   ('17', 1),
   ('50', 1),
   ('10', 1),
   ('200餘', 1),
   ('千萬', 1),
   ('一半', 1),
   ('44', 1),
   ('百餘', 1),
   ('317', 1),
   ('18', 1),
   ('43', 1)],
  '文化': [('10', 3),
   ('130', 1),
   ('30', 1),
   ('上萬', 1),
   ('15', 1),
   ('之一', 1),
   ('25', 1),
   ('100', 1),
   ('20', 1),
   ('1億', 1),
   ('70萬', 1),
   ('1萬多', 1),
   ('69萬多', 1),
   ('一半', 1),
   ('200多', 1),
   ('500', 1)],
  '兩岸': [('2019', 3),
   ('75', 3),
   ('300', 3),
   ('4000', 2),
   ('10', 2),
   ('100萬', 2),
   ('119', 2),
   ('約1000', 2),
   ('3.2萬', 2),
   ('1萬', 2),
   ('3993', 2),
   ('1337', 2),
   ('895', 2),
   ('2266', 2),
   ('1萬餘', 1),
   ('27', 1),
   ('31個', 1),
   ('19', 1),
   ('1萬4868', 1),
   ('72萬', 1)],
  '全部': [('16', 23),
   ('11', 23),
   ('10', 17),
   ('2000', 8),
   ('50', 8),
   ('17', 8),
   ('4000', 6),
   ('20', 6),
   ('12', 6),
   ('23', 6),
   ('13', 5),
   ('之一', 5),
   ('2019', 5),
   ('14', 5),
   ('30', 4),
   ('15', 4),
   ('1萬', 4),
   ('一半', 4),
   ('19', 4),
   ('4.0', 4)]},
 'DATE': {'政治': [('今天', 35),
   ('12天', 2),
   ('5月', 2),
   ('同年12月', 2),
   ('4個月', 2),
   ('一年', 2),
   ('7日', 1),
   ('18日', 1),
   ('6個月', 1),
   ('3月18日', 1),
   ('民國109年', 1),
   ('11日', 1),
   ('近年', 1),
   ('20年', 1),
   ('當年', 1),
   ('民國109年9月17日', 1),
   ('110年10月1日', 1),
   ('同年10月2日', 1),
   ('10月3日', 1),
   ('10月4日', 1)],
  '科技': [('今天', 27),
   ('18日', 6),
   ('1月', 4),
   ('11日', 4),
   ('春季', 4),
   ('去年4月', 2),
   ('2016年', 2),
   ('去年10月', 2),
   ('2030年', 2),
   ('2023年底', 2),
   ('今年', 2),
   ('下週', 2),
   ('多年來', 2),
   ('1年', 2),
   ('3月23日', 2),
   ('2020年12月', 1),
   ('過去一年', 1),
   ('上個月', 1),
   ('9日', 1),
   ('2018年4月', 1)],
  '運動': [('今天', 47),
   ('今年', 9),
   ('昨天', 8),
   ('去年', 4),
   ('2年', 4),
   ('7日至20日', 4),
   ('一年', 4),
   ('40歲', 3),
   ('上個月', 2),
   ('一日', 2),
   ('2008年', 2),
   ('冬季', 2),
   ('11日', 1),
   ('27日', 1),
   ('105年', 1),
   ('10年', 1),
   ('109年', 1),
   ('去年11月底', 1),
   ('近4個月', 1),
   ('年底', 1)],
  '證卷': [('今天', 36),
   ('去年', 24),
   ('今年', 12),
   ('2021年', 11),
   ('3月', 11),
   ('2020年', 7),
   ('2月', 6),
   ('前2月', 4),
   ('4月', 4),
   ('10年', 3),
   ('本週', 3),
   ('2022年', 3),
   ('12個月', 2),
   ('去年10月', 2),
   ('14日', 2),
   ('今年前2月', 2),
   ('2019年', 2),
   ('2021年度', 2),
   ('2個月', 2),
   ('明天', 1)],
  '產經': [('今天', 30),
   ('今年', 23),
   ('去年', 16),
   ('前年', 4),
   ('上週', 2),
   ('3月15日', 2),
   ('3月底', 2),
   ('2021年', 2),
   ('第1季', 2),
   ('農曆年', 2),
   ('全年', 1),
   ('這2年', 1),
   ('去年12月', 1),
   ('今年3月1日', 1),
   ('7個', 1),
   ('2017年至今', 1),
   ('2019年', 1),
   ('2019', 1),
   ('11日', 1),
   ('今年一月', 1)],
  '娛樂': [('今天', 26),
   ('昨天', 7),
   ('去年', 5),
   ('2月', 4),
   ('5月', 3),
   ('今年', 3),
   ('13日', 3),
   ('38歲', 3),
   ('34歲', 3),
   ('41歲', 2),
   ('69歲', 2),
   ('近年', 2),
   ('1983年', 2),
   ('50多年', 2),
   ('1月', 1),
   ('今年1月24日', 1),
   ('一年', 1),
   ('半世紀', 1),
   ('10年', 1),
   ('前幾天', 1)],
  '生活': [('今天', 22),
   ('7天', 6),
   ('10天', 4),
   ('3月7日', 4),
   ('5天', 3),
   ('5月', 3),
   ('近年', 3),
   ('2012年', 3),
   ('去年', 3),
   ('11日', 3),
   ('17日', 3),
   ('3天', 2),
   ('未來一個多月', 2),
   ('2019年', 2),
   ('18日', 2),
   ('4月', 2),
   ('2019', 2),
   ('3月', 1),
   ('7月', 1),
   ('1110314', 1)],
  '國際': [('今天', 28),
   ('昨天', 5),
   ('2015年', 3),
   ('上週', 3),
   ('14日', 2),
   ('2014年', 1),
   ('15日', 1),
   ('明天', 1),
   ('2018年', 1),
   ('10個多月', 1),
   ('5日', 1),
   ('11日', 1),
   ('2022年', 1),
   ('2年', 1),
   ('3月14日至4月1日', 1),
   ('今年', 1),
   ('4月', 1),
   ('本週', 1),
   ('16日', 1),
   ('數年', 1)],
  '社會': [('今天', 33),
   ('昨天', 4),
   ('3年', 4),
   ('10日', 3),
   ('日前', 2),
   ('明天', 2),
   ('3月', 2),
   ('30日', 2),
   ('9日', 2),
   ('12日', 2),
   ('去年11月', 2),
   ('1年6月', 2),
   ('2023年', 2),
   ('108年', 2),
   ('8歲', 2),
   ('40歲', 1),
   ('5年', 1),
   ('108年5月18日', 1),
   ('40日', 1),
   ('108年9月', 1)],
  '文化': [('今天', 20),
   ('今年', 11),
   ('7月', 3),
   ('6日', 3),
   ('去年', 2),
   ('26日', 2),
   ('21世紀', 2),
   ('2019年', 2),
   ('3個月', 2),
   ('未來3個月', 2),
   ('2021年', 2),
   ('百年', 2),
   ('日治時期', 2),
   ('40年', 1),
   ('2020年', 1),
   ('1980年', 1),
   ('年度', 1),
   ('近年', 1),
   ('3月15日', 1),
   ('11日', 1)],
  '兩岸': [('今天', 28),
   ('13日', 9),
   ('7天', 6),
   ('昨天', 4),
   ('今日', 3),
   ('14天', 3),
   ('2020年5月', 2),
   ('11日', 2),
   ('近日', 2),
   ('14日', 2),
   ('2019年', 2),
   ('近年', 2),
   ('本週', 2),
   ('今年', 2),
   ('2至3週', 2),
   ('10幾年', 1),
   ('1日', 1),
   ('3月1日至13日', 1),
   ('6年', 1),
   ('2019年底', 1)],
  '全部': [('今天', 332),
   ('今年', 66),
   ('去年', 57),
   ('昨天', 28),
   ('2021年', 19),
   ('11日', 15),
   ('2月', 15),
   ('3月', 14),
   ('13日', 13),
   ('18日', 12),
   ('7天', 12),
   ('4月', 11),
   ('2020年', 11),
   ('2019年', 11),
   ('近年', 10),
   ('5月', 9),
   ('2年', 8),
   ('14日', 8),
   ('一年', 7),
   ('1月', 7)]},
 'EVENT': {'政治': [('COVID-19（2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭', 1)],
  '科技': [],
  '運動': [('帕運會', 3),
   ('奧運', 2),
   ('東京奧運', 1),
   ('超級盃', 1),
   ('去年東京奧運', 1),
   ('帕運', 1)],
  '證卷': [],
  '產經': [('俄烏戰爭', 5), ('俄烏戰事', 1)],
  '娛樂': [],
  '生活': [('COVID-19', 1)],
  '國際': [('烏克蘭戰爭', 2), ('COVID-19', 1), ('2019', 1)],
  '社會': [],
  '文化': [('雪梨雙年展', 4),
   ('第23屆雪梨雙年展', 2),
   ('2019', 1),
   ('百老匯', 1),
   ('高雄春天藝術節', 1),
   ('2022年高雄春天藝術節', 1),
   ('2019冠狀病毒疾病', 1),
   ('百週年慶', 1)],
  '兩岸': [('東莞市疫情防控指揮辦', 1), ('2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭', 1)],
  '全部': [('俄烏戰爭', 7),
   ('雪梨雙年展', 4),
   ('帕運會', 3),
   ('奧運', 2),
   ('COVID-19', 2),
   ('烏克蘭戰爭', 2),
   ('2019', 2),
   ('第23屆雪梨雙年展', 2),
   ('COVID-19（2019冠狀病毒疾病）疫情', 1),
   ('東京奧運', 1),
   ('超級盃', 1),
   ('去年東京奧運', 1),
   ('帕運', 1),
   ('俄烏戰事', 1),
   ('百老匯', 1),
   ('高雄春天藝術節', 1),
   ('2022年高雄春天藝術節', 1),
   ('2019冠狀病毒疾病', 1),
   ('百週年慶', 1),
   ('東莞市疫情防控指揮辦', 1)]},
 'FAC': {'政治': [('台東志航基地', 8),
   ('台東馬偕醫院', 5),
   ('新竹空軍基地', 4),
   ('新竹基地', 4),
   ('志航基地', 3),
   ('玉山國家公園', 2),
   ('君悅酒店', 1),
   ('台南空軍基地', 1),
   ('盧賽基地', 1)],
  '科技': [('科博館', 3), ('國立自然科學博物館', 1)],
  '運動': [('新加坡華僑銀行室內體育館', 3),
   ('台南市立棒球場', 2),
   ('嘉義縣立棒球場體驗球場', 1),
   ('斗六棒球場', 1),
   ('立棒球場', 1),
   ('OCBC Arena', 1),
   ('國家體育場', 1),
   ('鳥巢', 1)],
  '證卷': [],
  '產經': [('長春廠', 1)],
  '娛樂': [('鶯歌後村堰遙控飛機場', 1), ('台灣會館', 1)],
  '生活': [],
  '國際': [],
  '社會': [('家樂福', 2),
   ('楊梅物流中心', 2),
   ('竹東火車站', 1),
   ('永明派出所', 1),
   ('桃機東變電站', 1),
   ('桃機西變電站', 1),
   ('高寮夜景公園', 1),
   ('家樂福倉儲', 1),
   ('美福倉儲', 1),
   ('楊梅', 1),
   ('桃園楊梅', 1),
   ('大園', 1),
   ('高雄岡山倉庫', 1),
   ('桃園大園', 1)],
  '文化': [('明華園', 6),
   ('衛武營音樂廳', 3),
   ('千禧公園', 2),
   ('衛武營', 2),
   ('新莊聯合辦公大樓', 1),
   ('屏東智慧農業學校', 1),
   ('南華微光', 1),
   ('南華校園', 1),
   ('高雄衛武營', 1),
   ('台南文化中心', 1),
   ('台中國家歌劇院', 1),
   ('台北國家戲劇院', 1),
   ('利沃夫博物館', 1),
   ('伊萬基夫歷史博物館', 1),
   ('哈爾科夫藝術博物館', 1),
   ('易北愛樂小廳', 1),
   ('柏林愛樂室內樂廳', 1),
   ('項鍊工作室', 1),
   ('大衛．胡斯', 1),
   ('台中國家歌劇院大劇院', 1)],
  '兩岸': [('安老院', 1)],
  '全部': [('台東志航基地', 8),
   ('明華園', 6),
   ('台東馬偕醫院', 5),
   ('新竹空軍基地', 4),
   ('新竹基地', 4),
   ('志航基地', 3),
   ('科博館', 3),
   ('新加坡華僑銀行室內體育館', 3),
   ('衛武營音樂廳', 3),
   ('玉山國家公園', 2),
   ('台南市立棒球場', 2),
   ('家樂福', 2),
   ('楊梅物流中心', 2),
   ('千禧公園', 2),
   ('衛武營', 2),
   ('君悅酒店', 1),
   ('台南空軍基地', 1),
   ('盧賽基地', 1),
   ('國立自然科學博物館', 1),
   ('嘉義縣立棒球場體驗球場', 1)]},
 'GPE': {'政治': [('台灣', 25),
   ('台東', 10),
   ('法國', 8),
   ('烏克蘭', 5),
   ('高雄', 5),
   ('澳洲', 5),
   ('德國', 4),
   ('雪梨', 4),
   ('新竹', 3),
   ('美國', 2),
   ('大陸', 2),
   ('高雄市', 2),
   ('台北', 2),
   ('中國', 2),
   ('台澳', 2),
   ('英國', 1),
   ('南台灣', 1),
   ('北市', 1),
   ('澳大利亞', 1),
   ('嘉義', 1)],
  '科技': [('台灣', 23),
   ('俄羅斯', 13),
   ('烏克蘭', 7),
   ('印度', 5),
   ('中國', 5),
   ('德國', 5),
   ('美國', 4),
   ('日本', 2),
   ('台北', 2),
   ('中華民國', 1),
   ('亞美尼亞', 1),
   ('亞塞拜然', 1),
   ('愛沙尼亞', 1),
   ('喬治亞', 1),
   ('匈牙利', 1),
   ('拉脫維亞', 1),
   ('立陶宛', 1),
   ('波蘭', 1),
   ('羅馬尼亞', 1),
   ('斯洛伐克', 1)],
  '運動': [('台灣', 13),
   ('新加坡', 10),
   ('巴西', 6),
   ('印度', 5),
   ('中國', 5),
   ('瑞典', 4),
   ('韓國', 4),
   ('台南', 3),
   ('克羅埃西亞', 3),
   ('新竹市', 2),
   ('南韓', 2),
   ('嘉義縣', 2),
   ('日本', 2),
   ('斯洛維尼亞', 2),
   ('北京', 2),
   ('烏克蘭', 2),
   ('淡水', 2),
   ('台中市', 1),
   ('旅美', 1),
   ('美國', 1)],
  '證卷': [('台灣', 18),
   ('台股', 15),
   ('台北', 4),
   ('烏克蘭', 2),
   ('中國大陸', 2),
   ('日本', 2),
   ('美股', 2),
   ('中國', 1),
   ('美國', 1),
   ('日股', 1)],
  '產經': [('台灣', 22),
   ('中國', 12),
   ('俄羅斯', 7),
   ('烏克蘭', 6),
   ('深圳', 4),
   ('深圳市', 3),
   ('俄烏', 2),
   ('吉林省', 2),
   ('長春市', 2),
   ('日本', 2),
   ('天津市', 2),
   ('台北', 2),
   ('美國', 2),
   ('廣東省', 2),
   ('紐約西德州', 1),
   ('西德州', 1),
   ('倫敦', 1),
   ('北海布倫特', 1),
   ('上海', 1),
   ('中國大陸', 1)],
  '娛樂': [('台灣', 11),
   ('美國', 10),
   ('英國', 9),
   ('香港', 5),
   ('洛杉磯', 4),
   ('南庄', 3),
   ('新北', 2),
   ('烏克蘭', 2),
   ('紐約', 2),
   ('台北', 2),
   ('法國', 1),
   ('德國', 1),
   ('日本', 1),
   ('加拿大', 1),
   ('新竹', 1),
   ('彰化', 1),
   ('屏東', 1),
   ('花蓮', 1),
   ('紐西蘭', 1),
   ('倫敦', 1)],
  '生活': [('台灣', 4),
   ('台北', 3),
   ('彰化縣', 2),
   ('中國', 2),
   ('南投縣名間鄉', 1),
   ('雲林縣', 1),
   ('金門', 1),
   ('新埔站', 1),
   ('苗栗縣', 1),
   ('員林市', 1),
   ('中華', 1),
   ('中壢', 1),
   ('香港', 1),
   ('深圳市', 1),
   ('東莞市', 1),
   ('台北市', 1),
   ('桃園市', 1),
   ('菲律賓', 1),
   ('越南', 1),
   ('泰國', 1)],
  '國際': [('俄羅斯', 23),
   ('俄國', 23),
   ('烏克蘭', 16),
   ('香港', 14),
   ('印度', 12),
   ('台灣', 12),
   ('美國', 10),
   ('德國', 10),
   ('伊朗', 9),
   ('莫斯科', 9),
   ('中國', 9),
   ('挪威', 7),
   ('日本', 7),
   ('澳洲', 4),
   ('英國', 3),
   ('俄方', 3),
   ('土耳其', 3),
   ('福井縣', 3),
   ('雪梨', 2),
   ('卡達', 2)],
  '社會': [('台灣', 4),
   ('義大利', 3),
   ('嘉義市', 2),
   ('高雄', 2),
   ('中國', 2),
   ('廣東', 2),
   ('台中', 2),
   ('桃園市', 2),
   ('苗栗縣', 1),
   ('通霄鎮', 1),
   ('新竹縣', 1),
   ('嘉義', 1),
   ('台中市', 1),
   ('神岡區', 1),
   ('花東', 1),
   ('東河鄉', 1),
   ('台東', 1),
   ('台東縣東河鄉', 1),
   ('財政部', 1),
   ('林口區', 1)],
  '文化': [('台灣', 30),
   ('高雄', 14),
   ('烏克蘭', 7),
   ('屏東', 6),
   ('德國', 6),
   ('美國', 5),
   ('柏林', 5),
   ('台南', 4),
   ('俄羅斯', 3),
   ('紐約', 2),
   ('屏東市', 2),
   ('新莊', 2),
   ('高雄市', 2),
   ('台北', 2),
   ('日本', 2),
   ('西班牙', 1),
   ('澳洲', 1),
   ('捷克布拉格', 1),
   ('俄國', 1),
   ('嘉義縣', 1)],
  '兩岸': [('中國', 90),
   ('香港', 69),
   ('俄羅斯', 22),
   ('北京', 19),
   ('深圳', 18),
   ('東莞', 16),
   ('港府', 14),
   ('美國', 13),
   ('台灣', 10),
   ('東莞市', 8),
   ('美方', 7),
   ('廣東', 3),
   ('上海', 3),
   ('廣東省', 3),
   ('吉林市', 3),
   ('澳門', 2),
   ('中方', 2),
   ('深圳市', 2),
   ('封城', 2),
   ('中港', 2)],
  '全部': [('台灣', 172),
   ('中國', 129),
   ('香港', 89),
   ('俄羅斯', 70),
   ('烏克蘭', 48),
   ('美國', 48),
   ('俄國', 27),
   ('德國', 26),
   ('深圳', 24),
   ('北京', 23),
   ('印度', 22),
   ('高雄', 21),
   ('台北', 19),
   ('日本', 18),
   ('英國', 17),
   ('東莞', 16),
   ('台股', 15),
   ('港府', 14),
   ('新加坡', 13),
   ('法國', 12)]},
 'LANGUAGE': {'政治': [('英文', 1)],
  '科技': [],
  '運動': [('中文', 1)],
  '證卷': [],
  '產經': [],
  '娛樂': [('華語', 1), ('英文', 1)],
  '生活': [],
  '國際': [],
  '社會': [],
  '文化': [('客家話', 1), ('閩南語', 1), ('日語', 1), ('吳儂軟語', 1)],
  '兩岸': [('英文', 2)],
  '全部': [('英文', 4),
   ('中文', 1),
   ('華語', 1),
   ('客家話', 1),
   ('閩南語', 1),
   ('日語', 1),
   ('吳儂軟語', 1)]},
 'LAW': {'政治': [],
  '科技': [('LINE', 1)],
  '運動': [],
  '證卷': [],
  '產經': [],
  '娛樂': [],
  '生活': [],
  '國際': [('國安法', 2), ('北約憲章第5條', 1)],
  '社會': [],
  '文化': [],
  '兩岸': [('香港國安法', 1), ('外國公司問責法', 1)],
  '全部': [('國安法', 2),
   ('LINE', 1),
   ('北約憲章第5條', 1),
   ('香港國安法', 1),
   ('外國公司問責法', 1)]},
 'LOC': {'政治': [('台灣西南防空識別區', 1),
   ('北美', 1),
   ('屯稜線', 1),
   ('丹大溪', 1),
   ('巒大溪', 1),
   ('郡大溪', 1)],
  '科技': [('南極', 7), ('月球', 5), ('月球南極', 1), ('太陽系', 1)],
  '運動': [],
  '證卷': [('亞洲', 1)],
  '產經': [('歐洲', 12), ('東北', 1), ('塞港', 1)],
  '娛樂': [('神仙谷', 3), ('北美', 1), ('溪谷', 1)],
  '生活': [('東半部', 2), ('東北', 1), ('東南風', 1), ('馬祖地區', 1), ('基隆港', 1)],
  '國際': [('亞洲', 2),
   ('北極', 1),
   ('北歐', 1),
   ('博斯普魯斯海峽', 1),
   ('太平洋', 1),
   ('歐洲', 1)],
  '社會': [('高雄港', 1), ('陽明山', 1), ('中山區中山北路', 1), ('楊梅區', 1)],
  '文化': [('歐洲', 2),
   ('亞洲', 1),
   ('大海', 1),
   ('北美', 1),
   ('東海岸', 1),
   ('台南山', 1),
   ('東南亞', 1)],
  '兩岸': [('美東', 1), ('特別行政區', 1)],
  '全部': [('歐洲', 15),
   ('南極', 7),
   ('月球', 5),
   ('亞洲', 4),
   ('北美', 3),
   ('神仙谷', 3),
   ('東北', 2),
   ('東半部', 2),
   ('台灣西南防空識別區', 1),
   ('屯稜線', 1),
   ('丹大溪', 1),
   ('巒大溪', 1),
   ('郡大溪', 1),
   ('月球南極', 1),
   ('太陽系', 1),
   ('塞港', 1),
   ('溪谷', 1),
   ('東南風', 1),
   ('馬祖地區', 1),
   ('基隆港', 1)]},
 'MONEY': {'政治': [('新台幣6億元', 1),
   ('3萬5703美元', 1),
   ('約101萬元', 1),
   ('3萬5703', 1),
   ('新台幣約101萬元', 1),
   ('4億7222萬元', 1),
   ('1億3788萬元', 1)],
  '科技': [('1萬3900元', 5),
   ('1萬7900元', 3),
   ('1萬5500元', 2),
   ('1萬9000元', 2),
   ('3999美元', 2),
   ('新台幣60億元', 1),
   ('新台幣', 1),
   ('5萬9900元', 1),
   ('4萬5900元', 1),
   ('1.79萬元', 1),
   ('2萬2900元', 1),
   ('429美元', 1),
   ('399美元', 1),
   ('1999美元', 1),
   ('1599美元', 1),
   ('599美元', 1)],
  '運動': [('200萬美元', 4), ('十元', 1)],
  '證卷': [('新台幣2861.6億元', 4),
   ('0.1元', 4),
   ('20元', 3),
   ('132.5元', 3),
   ('7元', 2),
   ('4.5元', 2),
   ('1.31元', 2),
   ('1.93億元', 2),
   ('46.23元', 2),
   ('26元', 2),
   ('3億元', 2),
   ('16.04億元', 2),
   ('142.43億元', 2),
   ('新台幣2億元', 2),
   ('0.6元', 2),
   ('0.7元', 2),
   ('0.67元', 2),
   ('4.7億元', 2),
   ('1.52元', 2),
   ('164.5元', 1)],
  '產經': [('430億歐元', 3),
   ('28.53元', 2),
   ('28.450元', 2),
   ('28.420元', 2),
   ('28.534元', 2),
   ('1.01元', 2),
   ('新台幣4000億元', 1),
   ('173億元', 1),
   ('10.35元', 1),
   ('5元', 1),
   ('新台幣38.84億元', 1),
   ('1.3元', 1),
   ('0.65元', 1),
   ('0.5元', 1),
   ('新台幣2000萬元', 1),
   ('2000萬元', 1),
   ('2.02億元', 1),
   ('103.80美元', 1),
   ('108.13美元', 1),
   ('新台幣2千萬元', 1)],
  '娛樂': [('2000萬元', 1)],
  '生活': [('2元', 4),
   ('新台幣2萬元', 1),
   ('1萬2500元', 1),
   ('12萬5000元', 1),
   ('新台幣10萬元', 1),
   ('12億餘元', 1),
   ('新台幣3元', 1),
   ('38.5元', 1),
   ('48元', 1),
   ('新台幣575萬元', 1),
   ('50萬元', 1),
   ('575萬元', 1)],
  '國際': [('1490億印度盧比', 1), ('19.4億美元', 1)],
  '社會': [('80萬元', 5),
   ('新台幣6萬7500元', 2),
   ('600元', 2),
   ('10萬元', 2),
   ('30萬元', 2),
   ('500萬元', 2),
   ('新台幣3萬元', 1),
   ('新台幣500萬元', 1),
   ('200億元', 1),
   ('新台幣200億元', 1),
   ('12餘億元', 1),
   ('新台幣9萬元', 1),
   ('9萬元', 1),
   ('新台幣1000萬元', 1),
   ('35元', 1),
   ('1000萬元', 1),
   ('新台幣600元', 1),
   ('2500萬元', 1),
   ('200萬元', 1),
   ('新台幣80萬元', 1)],
  '文化': [('新台幣385萬元', 1), ('新台幣2700萬元', 1)],
  '兩岸': [('80.9港元', 1),
   ('8港元', 1),
   ('6400億美元', 1),
   ('約17兆新台幣', 1),
   ('約12.6兆新台幣', 1)],
  '全部': [('1萬3900元', 5),
   ('80萬元', 5),
   ('200萬美元', 4),
   ('新台幣2861.6億元', 4),
   ('0.1元', 4),
   ('2元', 4),
   ('1萬7900元', 3),
   ('20元', 3),
   ('132.5元', 3),
   ('3億元', 3),
   ('430億歐元', 3),
   ('新台幣', 2),
   ('1萬5500元', 2),
   ('1萬9000元', 2),
   ('3999美元', 2),
   ('7元', 2),
   ('4.5元', 2),
   ('1.31元', 2),
   ('1.93億元', 2),
   ('46.23元', 2)]},
 'NORP': {'政治': [('烏克蘭', 6),
   ('德商', 2),
   ('歐商', 1),
   ('美商', 1),
   ('日商', 1),
   ('中商', 1),
   ('法方', 1)],
  '科技': [('奧斯汀', 1), ('台灣', 1)],
  '運動': [('泰雅族', 1), ('捷克', 1), ('淡商', 1)],
  '證卷': [],
  '產經': [('台商', 5)],
  '娛樂': [('華裔', 2),
   ('北埔人', 1),
   ('英國', 1),
   ('台灣人', 1),
   ('香港', 1),
   ('香港人', 1),
   ('烏克蘭', 1),
   ('烏克蘭人', 1),
   ('歐洲人', 1),
   ('中華', 1),
   ('美籍', 1),
   ('美國', 1)],
  '生活': [('印尼籍', 2)],
  '國際': [('俄國', 1)],
  '社會': [('台灣', 1), ('富商', 1)],
  '文化': [('台灣', 6),
   ('排灣族', 2),
   ('中國', 2),
   ('台裔', 2),
   ('鄒族', 1),
   ('德國', 1),
   ('華人', 1),
   ('台籍', 1),
   ('阿美族', 1),
   ('日本', 1),
   ('美籍', 1),
   ('英國', 1)],
  '兩岸': [('港人', 3),
   ('台籍', 1),
   ('中國', 1),
   ('港媒', 1),
   ('陸媒', 1),
   ('台資', 1),
   ('中文', 1),
   ('中國人', 1)],
  '全部': [('台灣', 8),
   ('烏克蘭', 7),
   ('台商', 5),
   ('中國', 3),
   ('港人', 3),
   ('德商', 2),
   ('英國', 2),
   ('華裔', 2),
   ('美籍', 2),
   ('印尼籍', 2),
   ('排灣族', 2),
   ('台裔', 2),
   ('台籍', 2),
   ('歐商', 1),
   ('美商', 1),
   ('日商', 1),
   ('中商', 1),
   ('法方', 1),
   ('奧斯汀', 1),
   ('泰雅族', 1)]},
 'ORDINAL': {'政治': [('第四', 2),
   ('第1', 1),
   ('第206', 1),
   ('第8', 1),
   ('第60', 1),
   ('第一', 1),
   ('第二', 1),
   ('第三', 1),
   ('第五', 1),
   ('第六', 1)],
  '科技': [('第3', 6), ('第5', 4), ('第4', 3), ('第一', 2), ('第三', 1), ('第二', 1)],
  '運動': [('第3', 9),
   ('第一', 4),
   ('第2', 4),
   ('第4', 3),
   ('29', 1),
   ('第24', 1),
   ('第45', 1),
   ('第23', 1),
   ('第二', 1),
   ('第7', 1)],
  '證卷': [('第4', 1)],
  '產經': [('第20', 1), ('第一', 1), ('第2', 1), ('第15', 1), ('第27', 1)],
  '娛樂': [('第一', 5), ('第三', 3), ('第49', 1), ('第44', 1)],
  '生活': [('第一', 3),
   ('第二', 3),
   ('第九', 2),
   ('第11102', 1),
   ('第111062', 1),
   ('第三', 1)],
  '國際': [('第4', 2), ('第一', 2)],
  '社會': [('第2', 2),
   ('第一', 2),
   ('第3', 1),
   ('第三', 1),
   ('第4', 1),
   ('第1', 1),
   ('第一時間', 1)],
  '文化': [('第一', 9),
   ('第3', 2),
   ('第33', 1),
   ('第一時間', 1),
   ('首次', 1),
   ('第9', 1),
   ('第15', 1),
   ('第6', 1),
   ('第2', 1),
   ('第五', 1),
   ('第四', 1)],
  '兩岸': [('第5', 8), ('第一', 2), ('第3', 2), ('第二', 1), ('第三', 1)],
  '全部': [('第一', 31),
   ('第3', 20),
   ('第5', 12),
   ('第4', 10),
   ('第三', 8),
   ('第2', 8),
   ('第二', 7),
   ('第四', 3),
   ('第1', 2),
   ('第五', 2),
   ('第15', 2),
   ('第九', 2),
   ('第一時間', 2),
   ('第206', 1),
   ('第8', 1),
   ('第60', 1),
   ('第六', 1),
   ('29', 1),
   ('第24', 1),
   ('第45', 1)]},
 'ORG': {'政治': [('外交部', 16),
   ('立法院', 13),
   ('監察院', 9),
   ('行政院', 8),
   ('國防部', 7),
   ('內政部', 6),
   ('中央社', 5),
   ('國民黨', 4),
   ('CPTPP', 4),
   ('工總', 3),
   ('空軍', 3),
   ('中央', 2),
   ('政府', 2),
   ('北市府', 2),
   ('澳洲國會', 2),
   ('紐約台灣商會', 2),
   ('空軍司令部', 2),
   ('外交部長', 1),
   ('慈濟', 1),
   ('國防安全研究院', 1)],
  '科技': [('蘋果', 20),
   ('中研院', 6),
   ('宏達電', 3),
   ('中央社', 3),
   ('台灣海洋科技研究中心', 2),
   ('印度科技部', 2),
   ('Meta', 2),
   ('路透社', 2),
   ('國研院', 2),
   ('太空中心', 2),
   ('Tim哥', 2),
   ('敏實科技大學', 2),
   ('LINE', 2),
   ('印度理工學院', 1),
   ('海洋中心', 1),
   ('印度理工學院古瓦哈蒂分校', 1),
   ('科技部', 1),
   ('TIHs', 1),
   ('國研院國網中心', 1),
   ('印度理工學院堪坡校區', 1)],
  '運動': [('獅隊', 11),
   ('桃猿隊', 9),
   ('兄弟', 6),
   ('中央社', 5),
   ('桃猿', 5),
   ('南山高中', 4),
   ('世界桌球職業大聯盟', 4),
   ('味全龍隊', 4),
   ('統一獅隊', 3),
   ('台北興富發隊', 3),
   ('平等國小', 2),
   ('OCBC Arena', 2),
   ('統一', 2),
   ('綠衫軍', 2),
   ('光復高中', 1),
   ('平等國民小學女籃隊', 1),
   ('台北金華國中', 1),
   ('中華', 1),
   ('皇家隊', 1),
   ('興富發隊', 1)],
  '證卷': [('陽明', 9),
   ('揚弈科技', 8),
   ('友通', 7),

In [8]:
data['PERSON']['政治'][0:10]

[('黃重凱', 24),
 ('柳惠千', 13),
 ('喬建中', 12),
 ('徐國勇', 11),
 ('季欽', 8),
 ('許舒博', 7),
 ('游錫堃', 6),
 ('侯富議', 6),
 ('蘇貞昌', 5),
 ('吳釗燮', 4)]

In [9]:
data["PERSON"]["科技"][0:5]

[('林柏亨', 6), ('吳偉仁', 5), ('包淳偉', 4), ('黃晨瑋', 4), ('廖俊智', 4)]

In [10]:
data["PERSON"]["娛樂"][0:5]

[('唐川', 20), ('歸亞蕾', 18), ('炎亞綸', 11), ('威廉赫特', 10), ('莊凱勛', 8)]

In [11]:
data["PRODUCT"]["科技"][0:5]

[('iPhone SE', 8),
 ('iPad Air', 8),
 ('M1 Ultra', 6),
 ('iPhone', 5),
 ('Mac Studio', 5)]

## Step by Step

In [12]:
df_data

        ne_name                                           top_keys
0      CARDINAL  [('政治', [('2000', 7), ('4000', 2), ('13', 2), ...
1          DATE  [('政治', [('今天', 35), ('12天', 2), ('5月', 2), ('...
2         EVENT  [('政治', [('COVID-19（2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭...
3           FAC  [('政治', [('台東志航基地', 8), ('台東馬偕醫院', 5), ('新竹空軍基...
4           GPE  [('政治', [('台灣', 25), ('台東', 10), ('法國', 8), ('...
5      LANGUAGE  [('政治', [('英文', 1)]), ('科技', []), ('運動', [('中文...
6           LAW  [('政治', []), ('科技', [('LINE', 1)]), ('運動', [])...
7           LOC  [('政治', [('台灣西南防空識別區', 1), ('北美', 1), ('屯稜線', ...
8         MONEY  [('政治', [('新台幣6億元', 1), ('3萬5703美元', 1), ('約10...
9          NORP  [('政治', [('烏克蘭', 6), ('德商', 2), ('歐商', 1), ('美...
10      ORDINAL  [('政治', [('第四', 2), ('第1', 1), ('第206', 1), ('...
11          ORG  [('政治', [('外交部', 16), ('立法院', 13), ('監察院', 9),...
12      PERCENT  [('政治', [('5%', 1), ('45%', 1)]), ('科技', [('10...
13       PERSON  [('政治', [('黃重凱', 24), ('柳惠千', 13), ('喬建中', 12)...
14      PRODUCT  [('政治', [('2000', 3), ('殲16戰機', 2), ('2017', 1...
15     QUANTITY  [('政治', [('2000呎', 6), ('10浬', 5), ('80公頃', 2)...
16         TIME  [('政治', [('下午', 10), ('上午', 10), ('11時26分', 5)...
17  WORK_OF_ART  [('政治', []), ('科技', []), ('運動', []), ('證卷', []...

In [13]:
df_data.iloc[0,0]

'CARDINAL'

In [14]:
df_data.iloc[1,0]

'DATE'

In [15]:
df_data.iloc[13, 0]  # Person NER name
df_data.loc[13, 'ne_name']  # Person NER name

'PERSON'

In [16]:
df_data.iloc[13, 1]  # Person keywords
df_data.loc[13, 'top_keys']  # Person keywords

"[('政治', [('黃重凱', 24), ('柳惠千', 13), ('喬建中', 12), ('徐國勇', 11), ('季欽', 8), ('許舒博', 7), ('游錫堃', 6), ('侯富議', 6), ('蘇貞昌', 5), ('吳釗燮', 4), ('許佑格', 4), ('范惠君', 4), ('歐布萊恩', 4), ('陳其邁', 3), ('柯文哲', 3), ('陳智菡', 3), ('黃鼎翔', 3), ('王同義', 3), ('王美惠', 3), ('許邁德', 2)]), ('科技', [('林柏亨', 6), ('吳偉仁', 5), ('包淳偉', 4), ('黃晨瑋', 4), ('廖俊智', 4), ('波博', 3), ('黃文山', 3), ('艾偉', 3), ('王金燦', 2), ('庫克', 2), ('曾信超', 2), ('波皮斯庫', 2), ('王兆璋', 1), ('希塔拉姆', 1), ('吳宗信', 1), ('葉均蔚', 1), ('楊勇', 1), ('陳信安', 1), ('Tim哥', 1), ('夏哈', 1)]), ('運動', [('林昀儒', 24), ('鄭怡靜', 24), ('莊智淵', 17), ('陳將双', 12), ('潘武雄', 10), ('陳建安', 8), ('布雷迪', 7), ('布魯娜', 6), ('賈奈特', 6), ('艾倫', 6), ('塞爾蒂克', 5), ('李恩芯', 5), ('王志庭', 4), ('施冠宇', 4), ('加奇尼', 4), ('樂天', 3), ('安宰賢', 3), ('巴特瑞', 3), ('梁家榮', 3), ('黃子鵬', 3)]), ('證卷', [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)]), ('產經', [('陳耀祥', 17), ('朱澤民', 9), ('曾博昇', 6), ('杜書全', 5), ('蘇松輝', 4), ('趙正宇', 3), ('林崇燾', 3), ('童振源', 3), ('郭幸容', 2), ('林德福', 2), ('吳秉叡', 2), ('李昆澤', 2), ('丁予嘉', 1), ('魏啟林', 1), ('佛里奇', 1), ('史屈特', 1), ('Susannah Streeter）', 1), ('林楚茵', 1), ('許智傑', 1), ('林俊憲', 1)]), ('娛樂', [('唐川', 20), ('歸亞蕾', 18), ('炎亞綸', 11), ('威廉赫特', 10), ('莊凱勛', 8), ('楊藜', 8), ('林暉閔', 7), ('納豆', 7), ('黃新皓', 6), ('珍康萍', 6), ('曹格', 6), ('侯友宜', 5), ('黃子佼', 5), ('百白', 4), ('孟耿如', 4), ('吳慷仁', 4), ('林心如', 4), ('郭宇宸', 3), ('茶金', 3), ('温昇豪', 3)]), ('生活', [('陳時中', 13), ('彭佳偉', 13), ('黃恩鴻', 5), ('李宗宏', 3), ('江文全', 2), ('邱基旭', 2), ('蔡佩君', 2), ('王力宏', 1), ('王惠美', 1), ('柯文哲', 1)]), ('國際', [('蘇利文', 5), ('楊潔篪', 4), ('阿布拉莫維奇', 3), ('蒲亭', 3), ('米佐塔基斯', 3), ('羅傑斯', 3), ('波多利雅科', 3), ('切爾西', 2), ('潘恩', 2), ('拉夫羅夫', 2), ('阿布杜拉希安', 2), ('哈蒂柏札德', 2), ('奧德洛', 2), ('霍恩', 2), ('蕭茲', 2), ('布魯塞爾', 1), ('Marise Payne）', 1), ('米勒', 1), ('Alexey Miller）', 1), ('穆罕穆德', 1)]), ('社會', [('戴寧', 8), ('孫道存', 7), ('鄭文燦', 6), ('孫芸芸', 4), ('孫瑩瑩', 3), ('孫智宏', 3), ('張女', 2), ('陳澤嘉', 2), ('吳逸萍', 2), ('莊英壽', 2), ('李作宏', 2), ('馬男', 1), ('洪裕翔', 1), ('何念慈育', 1), ('廖偉志', 1), ('廖鎮漢', 1), ('王國材', 1), ('蘇男', 1), ('劉育麟', 1), ('陳依芳', 1)]), ('文化', [('吳密察', 15), ('平珩', 10), ('吳蠻', 7), ('潘孟安', 6), ('吳思瑤', 5), ('楊書涵', 5), ('李其叡', 5), ('張徐展', 5), ('蔡采崴', 4), ('陳悅宜', 3), ('孫翠鳳', 3), ('朱天文', 3), ('顏伯駿', 3), ('鄭志偉', 3), ('朱安麗', 3), ('柳美', 3), ('大衛．胡斯', 3), ('李安', 2), ('譚盾', 2), ('阿儒瓦苡．篙瑪竿', 2)]), ('兩岸', [('薛達', 6), ('林鄭月娥', 5), ('劉兆佳', 5), ('雷正龍', 3), ('趙立堅', 3), ('李希', 3), ('希魯阿諾夫', 3), ('王晟', 3), ('布吉敏', 2), ('蒲亭', 2), ('余永定', 2), ('張文宏', 2), ('林柏偉', 1), ('林伯偉', 1), ('黃守應', 1), ('王長青', 1), ('崔靜麟', 1), ('張竹君', 1), ('梁萬年', 1), ('高拔陞', 1)]), ('全部', [('黃重凱', 24), ('林昀儒', 24), ('鄭怡靜', 24), ('唐川', 20), ('歸亞蕾', 18), ('莊智淵', 17), ('陳耀祥', 17), ('吳密察', 15), ('柳惠千', 13), ('陳時中', 13), ('彭佳偉', 13), ('喬建中', 12), ('陳將双', 12), ('徐國勇', 11), ('炎亞綸', 11), ('潘武雄', 10), ('威廉赫特', 10), ('平珩', 10), ('朱澤民', 9), ('季欽', 8)])]"

In [17]:
eval(df_data.loc[13, 'top_keys'])  # Person keywords

[('政治',
  [('黃重凱', 24),
   ('柳惠千', 13),
   ('喬建中', 12),
   ('徐國勇', 11),
   ('季欽', 8),
   ('許舒博', 7),
   ('游錫堃', 6),
   ('侯富議', 6),
   ('蘇貞昌', 5),
   ('吳釗燮', 4),
   ('許佑格', 4),
   ('范惠君', 4),
   ('歐布萊恩', 4),
   ('陳其邁', 3),
   ('柯文哲', 3),
   ('陳智菡', 3),
   ('黃鼎翔', 3),
   ('王同義', 3),
   ('王美惠', 3),
   ('許邁德', 2)]),
 ('科技',
  [('林柏亨', 6),
   ('吳偉仁', 5),
   ('包淳偉', 4),
   ('黃晨瑋', 4),
   ('廖俊智', 4),
   ('波博', 3),
   ('黃文山', 3),
   ('艾偉', 3),
   ('王金燦', 2),
   ('庫克', 2),
   ('曾信超', 2),
   ('波皮斯庫', 2),
   ('王兆璋', 1),
   ('希塔拉姆', 1),
   ('吳宗信', 1),
   ('葉均蔚', 1),
   ('楊勇', 1),
   ('陳信安', 1),
   ('Tim哥', 1),
   ('夏哈', 1)]),
 ('運動',
  [('林昀儒', 24),
   ('鄭怡靜', 24),
   ('莊智淵', 17),
   ('陳將双', 12),
   ('潘武雄', 10),
   ('陳建安', 8),
   ('布雷迪', 7),
   ('布魯娜', 6),
   ('賈奈特', 6),
   ('艾倫', 6),
   ('塞爾蒂克', 5),
   ('李恩芯', 5),
   ('王志庭', 4),
   ('施冠宇', 4),
   ('加奇尼', 4),
   ('樂天', 3),
   ('安宰賢', 3),
   ('巴特瑞', 3),
   ('梁家榮', 3),
   ('黃子鵬', 3)]),
 ('證卷', [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)]),
 ('產經',
  [('陳耀祥', 17),
   ('朱澤民', 9),
   ('曾博昇', 6),
   ('杜書全', 5),
   ('蘇松輝', 4),
   ('趙正宇', 3),
   ('林崇燾', 3),
   ('童振源', 3),
   ('郭幸容', 2),
   ('林德福', 2),
   ('吳秉叡', 2),
   ('李昆澤', 2),
   ('丁予嘉', 1),
   ('魏啟林', 1),
   ('佛里奇', 1),
   ('史屈特', 1),
   ('Susannah Streeter）', 1),
   ('林楚茵', 1),
   ('許智傑', 1),
   ('林俊憲', 1)]),
 ('娛樂',
  [('唐川', 20),
   ('歸亞蕾', 18),
   ('炎亞綸', 11),
   ('威廉赫特', 10),
   ('莊凱勛', 8),
   ('楊藜', 8),
   ('林暉閔', 7),
   ('納豆', 7),
   ('黃新皓', 6),
   ('珍康萍', 6),
   ('曹格', 6),
   ('侯友宜', 5),
   ('黃子佼', 5),
   ('百白', 4),
   ('孟耿如', 4),
   ('吳慷仁', 4),
   ('林心如', 4),
   ('郭宇宸', 3),
   ('茶金', 3),
   ('温昇豪', 3)]),
 ('生活',
  [('陳時中', 13),
   ('彭佳偉', 13),
   ('黃恩鴻', 5),
   ('李宗宏', 3),
   ('江文全', 2),
   ('邱基旭', 2),
   ('蔡佩君', 2),
   ('王力宏', 1),
   ('王惠美', 1),
   ('柯文哲', 1)]),
 ('國際',
  [('蘇利文', 5),
   ('楊潔篪', 4),
   ('阿布拉莫維奇', 3),
   ('蒲亭', 3),
   ('米佐塔基斯', 3),
   ('羅傑斯', 3),
   ('波多利雅科', 3),
   ('切爾西', 2),
   ('潘恩', 2),
   ('拉夫羅夫', 2),
   ('阿布杜拉希安', 2),
   ('哈蒂柏札德', 2),
   ('奧德洛', 2),
   ('霍恩', 2),
   ('蕭茲', 2),
   ('布魯塞爾', 1),
   ('Marise Payne）', 1),
   ('米勒', 1),
   ('Alexey Miller）', 1),
   ('穆罕穆德', 1)]),
 ('社會',
  [('戴寧', 8),
   ('孫道存', 7),
   ('鄭文燦', 6),
   ('孫芸芸', 4),
   ('孫瑩瑩', 3),
   ('孫智宏', 3),
   ('張女', 2),
   ('陳澤嘉', 2),
   ('吳逸萍', 2),
   ('莊英壽', 2),
   ('李作宏', 2),
   ('馬男', 1),
   ('洪裕翔', 1),
   ('何念慈育', 1),
   ('廖偉志', 1),
   ('廖鎮漢', 1),
   ('王國材', 1),
   ('蘇男', 1),
   ('劉育麟', 1),
   ('陳依芳', 1)]),
 ('文化',
  [('吳密察', 15),
   ('平珩', 10),
   ('吳蠻', 7),
   ('潘孟安', 6),
   ('吳思瑤', 5),
   ('楊書涵', 5),
   ('李其叡', 5),
   ('張徐展', 5),
   ('蔡采崴', 4),
   ('陳悅宜', 3),
   ('孫翠鳳', 3),
   ('朱天文', 3),
   ('顏伯駿', 3),
   ('鄭志偉', 3),
   ('朱安麗', 3),
   ('柳美', 3),
   ('大衛．胡斯', 3),
   ('李安', 2),
   ('譚盾', 2),
   ('阿儒瓦苡．篙瑪竿', 2)]),
 ('兩岸',
  [('薛達', 6),
   ('林鄭月娥', 5),
   ('劉兆佳', 5),
   ('雷正龍', 3),
   ('趙立堅', 3),
   ('李希', 3),
   ('希魯阿諾夫', 3),
   ('王晟', 3),
   ('布吉敏', 2),
   ('蒲亭', 2),
   ('余永定', 2),
   ('張文宏', 2),
   ('林柏偉', 1),
   ('林伯偉', 1),
   ('黃守應', 1),
   ('王長青', 1),
   ('崔靜麟', 1),
   ('張竹君', 1),
   ('梁萬年', 1),
   ('高拔陞', 1)]),
 ('全部',
  [('黃重凱', 24),
   ('林昀儒', 24),
   ('鄭怡靜', 24),
   ('唐川', 20),
   ('歸亞蕾', 18),
   ('莊智淵', 17),
   ('陳耀祥', 17),
   ('吳密察', 15),
   ('柳惠千', 13),
   ('陳時中', 13),
   ('彭佳偉', 13),
   ('喬建中', 12),
   ('陳將双', 12),
   ('徐國勇', 11),
   ('炎亞綸', 11),
   ('潘武雄', 10),
   ('威廉赫特', 10),
   ('平珩', 10),
   ('朱澤民', 9),
   ('季欽', 8)])]

In [18]:
eval(df_data.loc[13, 'top_keys'])

[('政治',
  [('黃重凱', 24),
   ('柳惠千', 13),
   ('喬建中', 12),
   ('徐國勇', 11),
   ('季欽', 8),
   ('許舒博', 7),
   ('游錫堃', 6),
   ('侯富議', 6),
   ('蘇貞昌', 5),
   ('吳釗燮', 4),
   ('許佑格', 4),
   ('范惠君', 4),
   ('歐布萊恩', 4),
   ('陳其邁', 3),
   ('柯文哲', 3),
   ('陳智菡', 3),
   ('黃鼎翔', 3),
   ('王同義', 3),
   ('王美惠', 3),
   ('許邁德', 2)]),
 ('科技',
  [('林柏亨', 6),
   ('吳偉仁', 5),
   ('包淳偉', 4),
   ('黃晨瑋', 4),
   ('廖俊智', 4),
   ('波博', 3),
   ('黃文山', 3),
   ('艾偉', 3),
   ('王金燦', 2),
   ('庫克', 2),
   ('曾信超', 2),
   ('波皮斯庫', 2),
   ('王兆璋', 1),
   ('希塔拉姆', 1),
   ('吳宗信', 1),
   ('葉均蔚', 1),
   ('楊勇', 1),
   ('陳信安', 1),
   ('Tim哥', 1),
   ('夏哈', 1)]),
 ('運動',
  [('林昀儒', 24),
   ('鄭怡靜', 24),
   ('莊智淵', 17),
   ('陳將双', 12),
   ('潘武雄', 10),
   ('陳建安', 8),
   ('布雷迪', 7),
   ('布魯娜', 6),
   ('賈奈特', 6),
   ('艾倫', 6),
   ('塞爾蒂克', 5),
   ('李恩芯', 5),
   ('王志庭', 4),
   ('施冠宇', 4),
   ('加奇尼', 4),
   ('樂天', 3),
   ('安宰賢', 3),
   ('巴特瑞', 3),
   ('梁家榮', 3),
   ('黃子鵬', 3)]),
 ('證卷', [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)]),
 ('產經',
  [('陳耀祥', 17),
   ('朱澤民', 9),
   ('曾博昇', 6),
   ('杜書全', 5),
   ('蘇松輝', 4),
   ('趙正宇', 3),
   ('林崇燾', 3),
   ('童振源', 3),
   ('郭幸容', 2),
   ('林德福', 2),
   ('吳秉叡', 2),
   ('李昆澤', 2),
   ('丁予嘉', 1),
   ('魏啟林', 1),
   ('佛里奇', 1),
   ('史屈特', 1),
   ('Susannah Streeter）', 1),
   ('林楚茵', 1),
   ('許智傑', 1),
   ('林俊憲', 1)]),
 ('娛樂',
  [('唐川', 20),
   ('歸亞蕾', 18),
   ('炎亞綸', 11),
   ('威廉赫特', 10),
   ('莊凱勛', 8),
   ('楊藜', 8),
   ('林暉閔', 7),
   ('納豆', 7),
   ('黃新皓', 6),
   ('珍康萍', 6),
   ('曹格', 6),
   ('侯友宜', 5),
   ('黃子佼', 5),
   ('百白', 4),
   ('孟耿如', 4),
   ('吳慷仁', 4),
   ('林心如', 4),
   ('郭宇宸', 3),
   ('茶金', 3),
   ('温昇豪', 3)]),
 ('生活',
  [('陳時中', 13),
   ('彭佳偉', 13),
   ('黃恩鴻', 5),
   ('李宗宏', 3),
   ('江文全', 2),
   ('邱基旭', 2),
   ('蔡佩君', 2),
   ('王力宏', 1),
   ('王惠美', 1),
   ('柯文哲', 1)]),
 ('國際',
  [('蘇利文', 5),
   ('楊潔篪', 4),
   ('阿布拉莫維奇', 3),
   ('蒲亭', 3),
   ('米佐塔基斯', 3),
   ('羅傑斯', 3),
   ('波多利雅科', 3),
   ('切爾西', 2),
   ('潘恩', 2),
   ('拉夫羅夫', 2),
   ('阿布杜拉希安', 2),
   ('哈蒂柏札德', 2),
   ('奧德洛', 2),
   ('霍恩', 2),
   ('蕭茲', 2),
   ('布魯塞爾', 1),
   ('Marise Payne）', 1),
   ('米勒', 1),
   ('Alexey Miller）', 1),
   ('穆罕穆德', 1)]),
 ('社會',
  [('戴寧', 8),
   ('孫道存', 7),
   ('鄭文燦', 6),
   ('孫芸芸', 4),
   ('孫瑩瑩', 3),
   ('孫智宏', 3),
   ('張女', 2),
   ('陳澤嘉', 2),
   ('吳逸萍', 2),
   ('莊英壽', 2),
   ('李作宏', 2),
   ('馬男', 1),
   ('洪裕翔', 1),
   ('何念慈育', 1),
   ('廖偉志', 1),
   ('廖鎮漢', 1),
   ('王國材', 1),
   ('蘇男', 1),
   ('劉育麟', 1),
   ('陳依芳', 1)]),
 ('文化',
  [('吳密察', 15),
   ('平珩', 10),
   ('吳蠻', 7),
   ('潘孟安', 6),
   ('吳思瑤', 5),
   ('楊書涵', 5),
   ('李其叡', 5),
   ('張徐展', 5),
   ('蔡采崴', 4),
   ('陳悅宜', 3),
   ('孫翠鳳', 3),
   ('朱天文', 3),
   ('顏伯駿', 3),
   ('鄭志偉', 3),
   ('朱安麗', 3),
   ('柳美', 3),
   ('大衛．胡斯', 3),
   ('李安', 2),
   ('譚盾', 2),
   ('阿儒瓦苡．篙瑪竿', 2)]),
 ('兩岸',
  [('薛達', 6),
   ('林鄭月娥', 5),
   ('劉兆佳', 5),
   ('雷正龍', 3),
   ('趙立堅', 3),
   ('李希', 3),
   ('希魯阿諾夫', 3),
   ('王晟', 3),
   ('布吉敏', 2),
   ('蒲亭', 2),
   ('余永定', 2),
   ('張文宏', 2),
   ('林柏偉', 1),
   ('林伯偉', 1),
   ('黃守應', 1),
   ('王長青', 1),
   ('崔靜麟', 1),
   ('張竹君', 1),
   ('梁萬年', 1),
   ('高拔陞', 1)]),
 ('全部',
  [('黃重凱', 24),
   ('林昀儒', 24),
   ('鄭怡靜', 24),
   ('唐川', 20),
   ('歸亞蕾', 18),
   ('莊智淵', 17),
   ('陳耀祥', 17),
   ('吳密察', 15),
   ('柳惠千', 13),
   ('陳時中', 13),
   ('彭佳偉', 13),
   ('喬建中', 12),
   ('陳將双', 12),
   ('徐國勇', 11),
   ('炎亞綸', 11),
   ('潘武雄', 10),
   ('威廉赫特', 10),
   ('平珩', 10),
   ('朱澤民', 9),
   ('季欽', 8)])]

In [19]:
dict(eval(df_data.loc[13, 'top_keys']) )

{'政治': [('黃重凱', 24),
  ('柳惠千', 13),
  ('喬建中', 12),
  ('徐國勇', 11),
  ('季欽', 8),
  ('許舒博', 7),
  ('游錫堃', 6),
  ('侯富議', 6),
  ('蘇貞昌', 5),
  ('吳釗燮', 4),
  ('許佑格', 4),
  ('范惠君', 4),
  ('歐布萊恩', 4),
  ('陳其邁', 3),
  ('柯文哲', 3),
  ('陳智菡', 3),
  ('黃鼎翔', 3),
  ('王同義', 3),
  ('王美惠', 3),
  ('許邁德', 2)],
 '科技': [('林柏亨', 6),
  ('吳偉仁', 5),
  ('包淳偉', 4),
  ('黃晨瑋', 4),
  ('廖俊智', 4),
  ('波博', 3),
  ('黃文山', 3),
  ('艾偉', 3),
  ('王金燦', 2),
  ('庫克', 2),
  ('曾信超', 2),
  ('波皮斯庫', 2),
  ('王兆璋', 1),
  ('希塔拉姆', 1),
  ('吳宗信', 1),
  ('葉均蔚', 1),
  ('楊勇', 1),
  ('陳信安', 1),
  ('Tim哥', 1),
  ('夏哈', 1)],
 '運動': [('林昀儒', 24),
  ('鄭怡靜', 24),
  ('莊智淵', 17),
  ('陳將双', 12),
  ('潘武雄', 10),
  ('陳建安', 8),
  ('布雷迪', 7),
  ('布魯娜', 6),
  ('賈奈特', 6),
  ('艾倫', 6),
  ('塞爾蒂克', 5),
  ('李恩芯', 5),
  ('王志庭', 4),
  ('施冠宇', 4),
  ('加奇尼', 4),
  ('樂天', 3),
  ('安宰賢', 3),
  ('巴特瑞', 3),
  ('梁家榮', 3),
  ('黃子鵬', 3)],
 '證卷': [('林耕億', 3), ('葉獻文', 2), ('李昌鴻', 2), ('黃水可', 1)],
 '產經': [('陳耀祥', 17),
  ('朱澤民', 9),
  ('曾博昇', 6),
  ('杜書全', 5),
  ('蘇松輝', 4),
  ('趙正宇', 3),
  ('林崇燾', 3),
  ('童振源', 3),
  ('郭幸容', 2),
  ('林德福', 2),
  ('吳秉叡', 2),
  ('李昆澤', 2),
  ('丁予嘉', 1),
  ('魏啟林', 1),
  ('佛里奇', 1),
  ('史屈特', 1),
  ('Susannah Streeter）', 1),
  ('林楚茵', 1),
  ('許智傑', 1),
  ('林俊憲', 1)],
 '娛樂': [('唐川', 20),
  ('歸亞蕾', 18),
  ('炎亞綸', 11),
  ('威廉赫特', 10),
  ('莊凱勛', 8),
  ('楊藜', 8),
  ('林暉閔', 7),
  ('納豆', 7),
  ('黃新皓', 6),
  ('珍康萍', 6),
  ('曹格', 6),
  ('侯友宜', 5),
  ('黃子佼', 5),
  ('百白', 4),
  ('孟耿如', 4),
  ('吳慷仁', 4),
  ('林心如', 4),
  ('郭宇宸', 3),
  ('茶金', 3),
  ('温昇豪', 3)],
 '生活': [('陳時中', 13),
  ('彭佳偉', 13),
  ('黃恩鴻', 5),
  ('李宗宏', 3),
  ('江文全', 2),
  ('邱基旭', 2),
  ('蔡佩君', 2),
  ('王力宏', 1),
  ('王惠美', 1),
  ('柯文哲', 1)],
 '國際': [('蘇利文', 5),
  ('楊潔篪', 4),
  ('阿布拉莫維奇', 3),
  ('蒲亭', 3),
  ('米佐塔基斯', 3),
  ('羅傑斯', 3),
  ('波多利雅科', 3),
  ('切爾西', 2),
  ('潘恩', 2),
  ('拉夫羅夫', 2),
  ('阿布杜拉希安', 2),
  ('哈蒂柏札德', 2),
  ('奧德洛', 2),
  ('霍恩', 2),
  ('蕭茲', 2),
  ('布魯塞爾', 1),
  ('Marise Payne）', 1),
  ('米勒', 1),
  ('Alexey Miller）', 1),
  ('穆罕穆德', 1)],
 '社會': [('戴寧', 8),
  ('孫道存', 7),
  ('鄭文燦', 6),
  ('孫芸芸', 4),
  ('孫瑩瑩', 3),
  ('孫智宏', 3),
  ('張女', 2),
  ('陳澤嘉', 2),
  ('吳逸萍', 2),
  ('莊英壽', 2),
  ('李作宏', 2),
  ('馬男', 1),
  ('洪裕翔', 1),
  ('何念慈育', 1),
  ('廖偉志', 1),
  ('廖鎮漢', 1),
  ('王國材', 1),
  ('蘇男', 1),
  ('劉育麟', 1),
  ('陳依芳', 1)],
 '文化': [('吳密察', 15),
  ('平珩', 10),
  ('吳蠻', 7),
  ('潘孟安', 6),
  ('吳思瑤', 5),
  ('楊書涵', 5),
  ('李其叡', 5),
  ('張徐展', 5),
  ('蔡采崴', 4),
  ('陳悅宜', 3),
  ('孫翠鳳', 3),
  ('朱天文', 3),
  ('顏伯駿', 3),
  ('鄭志偉', 3),
  ('朱安麗', 3),
  ('柳美', 3),
  ('大衛．胡斯', 3),
  ('李安', 2),
  ('譚盾', 2),
  ('阿儒瓦苡．篙瑪竿', 2)],
 '兩岸': [('薛達', 6),
  ('林鄭月娥', 5),
  ('劉兆佳', 5),
  ('雷正龍', 3),
  ('趙立堅', 3),
  ('李希', 3),
  ('希魯阿諾夫', 3),
  ('王晟', 3),
  ('布吉敏', 2),
  ('蒲亭', 2),
  ('余永定', 2),
  ('張文宏', 2),
  ('林柏偉', 1),
  ('林伯偉', 1),
  ('黃守應', 1),
  ('王長青', 1),
  ('崔靜麟', 1),
  ('張竹君', 1),
  ('梁萬年', 1),
  ('高拔陞', 1)],
 '全部': [('黃重凱', 24),
  ('林昀儒', 24),
  ('鄭怡靜', 24),
  ('唐川', 20),
  ('歸亞蕾', 18),
  ('莊智淵', 17),
  ('陳耀祥', 17),
  ('吳密察', 15),
  ('柳惠千', 13),
  ('陳時中', 13),
  ('彭佳偉', 13),
  ('喬建中', 12),
  ('陳將双', 12),
  ('徐國勇', 11),
  ('炎亞綸', 11),
  ('潘武雄', 10),
  ('威廉赫特', 10),
  ('平珩', 10),
  ('朱澤民', 9),
  ('季欽', 8)]}

In [20]:
# row by row 
for row in df_data.iterrows():
    print(row)
    break

(0, ne_name                                              CARDINAL
top_keys    [('政治', [('2000', 7), ('4000', 2), ('13', 2), ...
Name: 0, dtype: object)

In [21]:
for idx, (nerName, topKeys) in df_data.iterrows():
    print(nerName)
    print(topKeys)
    break

CARDINAL
[('政治', [('2000', 7), ('4000', 2), ('13', 2), ('54', 2), ('1730', 1), ('20', 1), ('38', 1), ('16', 1), ('39', 1), ('30', 1), ('90', 1), ('10萬', 1), ('12', 1), ('11', 1), ('41', 1), ('2017', 1), ('2036', 1)]), ('科技', [('4.0', 4), ('1200萬', 3), ('23', 2), ('120萬', 2), ('之一', 2), ('64', 2), ('25', 1), ('200', 1), ('15', 1), ('1萬', 1), ('2.5', 1), ('4000', 1), ('20', 1), ('60', 1), ('5G', 1), ('30', 1), ('33', 1), ('1176', 1), ('一半', 1), ('19', 1)]), ('運動', [('16', 19), ('11', 19), ('10', 5), ('32', 3), ('22', 2), ('57', 2), ('12', 2), ('7萬', 1), ('103萬', 1), ('31', 1), ('91', 1), ('128', 1), ('84', 1), ('92', 1), ('95', 1), ('四分', 1), ('20', 1), ('48', 1), ('18', 1), ('21', 1)]), ('證卷', [('50', 6), ('10', 4), ('十名', 2), ('505', 1), ('1287', 1), ('一半', 1), ('11', 1), ('29', 1), ('2名', 1), ('6.32倍', 1), ('1.85', 1), ('12.7倍', 1), ('13倍', 1), ('1.9倍', 1), ('1452萬4527', 1), ('633萬7576', 1), ('486', 1), ('367', 1), ('130', 1), ('5名', 1)]), ('產經', [('上億', 2), ('24', 1), ('2.0', 1), ('21', 1), ('2400萬', 1), ('60多', 1), ('66', 1), ('50萬顆', 1), ('147', 1), ('4萬多', 1), ('2600', 1), ('4000', 1)]), ('娛樂', [('200多', 2), ('2000萬', 1), ('三百', 1), ('10幾', 1)]), ('生活', [('17', 6), ('14', 5), ('23', 4), ('04', 4), ('13', 3), ('12', 3), ('2400', 3), ('2019', 2), ('19', 2), ('10', 2), ('16', 2), ('663', 2), ('20', 2), ('18', 2), ('07', 2), ('06', 2), ('11', 2), ('02', 2), ('08', 2), ('15', 2)]), ('國際', [('3萬', 1), ('200', 1), ('50', 1), ('之一', 1), ('4836', 1), ('5000', 1), ('500', 1), ('8631.9', 1), ('64', 1), ('17', 1), ('35', 1)]), ('社會', [('360萬', 2), ('68', 2), ('17', 1), ('50', 1), ('10', 1), ('200餘', 1), ('千萬', 1), ('一半', 1), ('44', 1), ('百餘', 1), ('317', 1), ('18', 1), ('43', 1)]), ('文化', [('10', 3), ('130', 1), ('30', 1), ('上萬', 1), ('15', 1), ('之一', 1), ('25', 1), ('100', 1), ('20', 1), ('1億', 1), ('70萬', 1), ('1萬多', 1), ('69萬多', 1), ('一半', 1), ('200多', 1), ('500', 1)]), ('兩岸', [('2019', 3), ('75', 3), ('300', 3), ('4000', 2), ('10', 2), ('100萬', 2), ('119', 2), ('約1000', 2), ('3.2萬', 2), ('1萬', 2), ('3993', 2), ('1337', 2), ('895', 2), ('2266', 2), ('1萬餘', 1), ('27', 1), ('31個', 1), ('19', 1), ('1萬4868', 1), ('72萬', 1)]), ('全部', [('16', 23), ('11', 23), ('10', 17), ('2000', 8), ('50', 8), ('17', 8), ('4000', 6), ('20', 6), ('12', 6), ('23', 6), ('13', 5), ('之一', 5), ('2019', 5), ('14', 5), ('30', 4), ('15', 4), ('1萬', 4), ('一半', 4), ('19', 4), ('4.0', 4)])]

In [22]:
data={}
for idx, (nerName, topKeys) in df_data.iterrows():
    data[nerName] = dict(eval(topKeys))

# Prepare index dictonary for NER

We will use them later on Django website

The catetory and ne_name are encoded to number on frondend page. So we have to conver number to category name.

    CARDINAL	數字
    DATE	日期
    EVENT	事件
    FAC	設施
    GPE	行政區
    LANGUAGE	語言
    LAW	法律
    LOC	地理區
    MONEY	金錢
    NORP	民族、宗教、政治團體
    ORDINAL	序數
    ORG	組織
    PERCENT	百分比率
    PERSON	人物
    PRODUCT	產品
    QUANTITY	數量
    TIME	時間
    WORK_OF_ART	作品

In [23]:
# ne names
ne_name =['EVENT','FAC','GPE','LANGUAGE','LAW','LOC','NORP','ORG','PERSON','PRODUCT','WORK_OF_ART']

idx2nename = { str(i) : item for i, item in enumerate(ne_name)} # dictionary

In [24]:
idx2nename

{'0': 'EVENT',
 '1': 'FAC',
 '2': 'GPE',
 '3': 'LANGUAGE',
 '4': 'LAW',
 '5': 'LOC',
 '6': 'NORP',
 '7': 'ORG',
 '8': 'PERSON',
 '9': 'PRODUCT',
 '10': 'WORK_OF_ART'}

In [25]:
idx2nename['8']

'PERSON'

In [26]:
# category names
news_categories=['政治','科技','運動','證卷','產經','娛樂','生活','國際','社會','文化','兩岸','全部']
idx2category = { str(i) : item for i, item in enumerate(news_categories)}

In [27]:
idx2category

{'0': '政治',
 '1': '科技',
 '2': '運動',
 '3': '證卷',
 '4': '產經',
 '5': '娛樂',
 '6': '生活',
 '7': '國際',
 '8': '社會',
 '9': '文化',
 '10': '兩岸',
 '11': '全部'}

In [28]:
# query with name string
data['LAW'][ '全部' ][0:10]

[('國安法', 2), ('LINE', 1), ('北約憲章第5條', 1), ('香港國安法', 1), ('外國公司問責法', 1)]

In [29]:
# query with encoded number
data[idx2nename['4']][ idx2category['11']][0:10]

[('國安法', 2), ('LINE', 1), ('北約憲章第5條', 1), ('香港國安法', 1), ('外國公司問責法', 1)]

In [30]:
# query with index
data[ne_name[4]][ news_categories[11]][0:10]

[('國安法', 2), ('LINE', 1), ('北約憲章第5條', 1), ('香港國安法', 1), ('外國公司問責法', 1)]

# Define Django function

In [31]:
'''
{'CARDINAL': {'政治': [('2020', 249),
   ('10', 170),
   ('15', 113),
   ('13', 105),
  ...
  }
'''

# ne names
ne_name =['EVENT','FAC','GPE','LANGUAGE','LAW','LOC','NORP','ORG','PERSON','PRODUCT','WORK_OF_ART']
idx2nename = { str(i) : item for i, item in enumerate(ne_name)}
'''
{0: 'EVENT',
 1: 'FAC',
 2: 'GPE',
 3: 'LANGUAGE',
 4: 'LAW',
 5: 'LOC',
 6: 'NORP',
 7: 'ORG',
 8: 'PERSON',
 9: 'PRODUCT',
 10: 'WORK_OF_ART'}

Name	Description
CARDINAL	數字
DATE	日期
EVENT	事件
FAC	設施
GPE	行政區
LANGUAGE	語言
LAW	法律
LOC	地理區
MONEY	金錢
NORP	民族、宗教、政治團體
ORDINAL	序數
ORG	組織
PERCENT	百分比率
PERSON	人物
PRODUCT	產品
QUANTITY	數量
TIME	時間
WORK_OF_ART	作品

'''

# category names
news_categories=['政治','科技','運動','證卷','產經','娛樂','生活','國際','社會','文化','兩岸','全部']
idx2cate = { str(i) : item for i, item in enumerate(news_categories)}
'''
{'0': '政治',
 '1': '科技',
 '2': '運動',
 '3': '證卷',
 '4': '產經',
 '5': '娛樂',
 '6': '生活',
 '7': '國際',
 '8': '社會',
 '9': '文化',
 '10': '兩岸',
 '11': '全部'}
'''

def load_data_topNer():
    # read data
    df_data = pd.read_csv('app_top_ner/dataset/news_topkey_by_ner_and_category.csv')

    global data
    data = {}
    for idx, (nerName, topKeys) in df_data.iterrows():
        data[nerName] = dict(eval(topKeys))


# We should call load_data() at first.
# load_data_topNer()

# Get data for wordcloud

## cloud chart data

clouddata=[{
      'text': '韓國瑜',
      'size': 40
    },
    {
      'text': '蔡英文',
      'size': 15
    },
    {
      'text': '賴清德',
      'size': 25
    }]

In [32]:
wf_pairs = data['PERSON']['政治'][0:10]

In [33]:
wf_pairs

[('黃重凱', 24),
 ('柳惠千', 13),
 ('喬建中', 12),
 ('徐國勇', 11),
 ('季欽', 8),
 ('許舒博', 7),
 ('游錫堃', 6),
 ('侯富議', 6),
 ('蘇貞昌', 5),
 ('吳釗燮', 4)]

In [34]:
wf_pairs

[('黃重凱', 24),
 ('柳惠千', 13),
 ('喬建中', 12),
 ('徐國勇', 11),
 ('季欽', 8),
 ('許舒博', 7),
 ('游錫堃', 6),
 ('侯富議', 6),
 ('蘇貞昌', 5),
 ('吳釗燮', 4)]

In [35]:
[{'text':w, 'size':f} for w, f in wf_pairs]

[{'text': '黃重凱', 'size': 24},
 {'text': '柳惠千', 'size': 13},
 {'text': '喬建中', 'size': 12},
 {'text': '徐國勇', 'size': 11},
 {'text': '季欽', 'size': 8},
 {'text': '許舒博', 'size': 7},
 {'text': '游錫堃', 'size': 6},
 {'text': '侯富議', 'size': 6},
 {'text': '蘇貞昌', 'size': 5},
 {'text': '吳釗燮', 'size': 4}]

    textSizeMin = 10 # new_min
    textSizeMax = 80 # new_max
    新餅多大: 80-10 = 70

    {'text': '黃重凱', 'size': 24}   ==> 80
     {'text': '吳釗燮', 'size': 4}   ==> 10
     舊餅多大: 24-4 = 20

     (24-4) / (24-4)  * ( 80-10  )  + 10  ==> 80
     (13-4) / (24-4)  * ( 80-10  )  + 10  ==> 41
     ...
     ...
     (4-4) / (24-4)  * ( 80-10  )  + 10  ==> 10

## Min-Max Scaling

<img src="https://image.slidesharecdn.com/tcdsp17-featureengineering-extendedversion-170719211326/95/feature-engineering-getting-most-out-of-data-for-predictive-models-tdc-2017-30-638.jpg?cb=1500581962" width="550">

<img src="https://chrisalbon.com/images/machine_learning_flashcards/MinMax_Scaling_print.png" width="550">


<img src='https://www.researchgate.net/publication/282541174/figure/fig1/AS:307388692353061@1450298583749/Min-max-method-of-normalization.png' width="550">

<img src='https://t4tutorials.com/wp-content/uploads/2019/09/Min-Max-Normalization-Equation-Pythone-Matlab.png' width="550">

<img src='scale_formula.jpg' width="550">

In [36]:
wf_pairs

[('黃重凱', 24),
 ('柳惠千', 13),
 ('喬建中', 12),
 ('徐國勇', 11),
 ('季欽', 8),
 ('許舒博', 7),
 ('游錫堃', 6),
 ('侯富議', 6),
 ('蘇貞昌', 5),
 ('吳釗燮', 4)]

In [37]:
# the minimun value is in the last最後一列(-1)是最小值
wf_pairs[-1][1]

4

In [38]:
# the maximum value is in the first第0列是最大值
wf_pairs[0][1]

24

In [39]:
min_= wf_pairs[-1][1]
max_= wf_pairs[0][1]

# We scale frequency value from 4-12 into 10~80
new_min = 10
new_max = 80

In [40]:
# Scale values 
[{'text':w, 'size':int(new_min+(f-min_)/(max_-min_)*(new_max-new_min))} for w, f in wf_pairs]

[{'text': '黃重凱', 'size': 80},
 {'text': '柳惠千', 'size': 41},
 {'text': '喬建中', 'size': 38},
 {'text': '徐國勇', 'size': 34},
 {'text': '季欽', 'size': 24},
 {'text': '許舒博', 'size': 20},
 {'text': '游錫堃', 'size': 17},
 {'text': '侯富議', 'size': 17},
 {'text': '蘇貞昌', 'size': 13},
 {'text': '吳釗燮', 'size': 10}]

In [41]:
if (min_ != max_):
    max_min_range = max_ - min_

else:
    # every word size is 1 / len(wf_pairs) 
    # 當每個字的頻率都一樣時，讓每個字的高度大小都一樣，分子是1，分母是字數==>均分
    max_min_range = len(wf_pairs)
    min_ = min_ - 1

In [42]:
max_min_range

20

In [43]:
# Scale values 
# cloud chart data
# using proportional scaling

# You can specify the two text sizes according to your size of chart canvas
textSizeMin = 10 # new_min
textSizeMax = 80 # new_max
clouddata = [{'text':w, 'size':int(textSizeMin+(f - min_)/max_min_range*(textSizeMax-textSizeMin))} for w, f in wf_pairs]

In [44]:
clouddata

[{'text': '黃重凱', 'size': 80},
 {'text': '柳惠千', 'size': 41},
 {'text': '喬建中', 'size': 38},
 {'text': '徐國勇', 'size': 34},
 {'text': '季欽', 'size': 24},
 {'text': '許舒博', 'size': 20},
 {'text': '游錫堃', 'size': 17},
 {'text': '侯富議', 'size': 17},
 {'text': '蘇貞昌', 'size': 13},
 {'text': '吳釗燮', 'size': 10}]

In [45]:
wf_pairs = data['EVENT']['政治'][0:10]

In [46]:
wf_pairs

[('COVID-19（2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭', 1)]

In [47]:
len(wf_pairs)

2

In [48]:
min_= wf_pairs[-1][1]
max_= wf_pairs[0][1]

In [49]:
[{'text':w, 'size':int(new_min+(f-min_)/(max_-min_)*(new_max-new_min))} for w, f in wf_pairs]

ZeroDivisionError: division by zero

In [50]:
if (min_ != max_):
    max_min_range = max_ - min_

else:
    max_min_range = len(wf_pairs)
    min_ = min_ - 1 # every f - min_ will be 1 now, so that every keyword size is porportional to 1 / len(wf_pairs)

In [51]:
max_min_range

2

In [52]:
len(wf_pairs)

2

In [53]:
[{'text':w, 'size':int(textSizeMin+(f - min_)/max_min_range*(textSizeMax-textSizeMin))} for w, f in wf_pairs]

[{'text': 'COVID-19（2019冠狀病毒疾病）疫情', 'size': 45}, {'text': '俄烏戰爭', 'size': 45}]

In [54]:
def get_category_topkey(ner_value, cate, topk):

    # data for displaying top keywords
    wf_pairs = data[ner_value][cate][0:topk]
    
    # if result is empty
    if wf_pairs == []:
        return []
    
    # data for bar chart
    words = [w for w, f in wf_pairs]
    freqs = [f for w, f in wf_pairs]
    
    # get the minimum and maximum frequency value in the wf_pairs
    min_= wf_pairs[-1][1] # the last keyword with the largest frequency value
    max_= wf_pairs[0][1]  # the first keyword with the smallest frequency value
    
    
    # You can specify the two text size according to your size of chart area
    textSizeMin = 10 # new_min
    textSizeMax = 80 # new_max

    
    # if all frequences are the same, "divided by zero" exception will arise.
    # In the following case, exception will arise.
    # We must deal with this.
    # [('AA', 1), ('BB', 1), ('CC', 1)]
    # Instead of (max_-min_), we use len(wf_pairs) as divisor.
    # every word size is 1 / len(wf_pairs) 
    # 當每個字的頻率都一樣時，讓每個字的高度大小都一樣，分子是1，分母是字數==>均分
    
    if (min_ != max_):
        max_min_range = max_ - min_

    else:
        max_min_range = len(wf_pairs)
        min_ = min_ - 1 # every size is 1 / len(wf_pairs)
    
    # word cloud chart data
    # using proportional scaling
    clouddata = [{'text':w, 'size':int(textSizeMin+(f - min_)/max_min_range*(textSizeMax-textSizeMin))} for w, f in wf_pairs]

    # clouddata=[{'text':w, 'size':int(new_min+(f-min_)/(max_-min_)*(new_max-new_min))} for w, f in wf_pairs]
    
    responseData = {
        "wf_pairs": wf_pairs,
        "data_barchart":{
                        "category": cate,
                        "labels": words,
                        "values": freqs
                        },
        "data_cloud": clouddata}
    return responseData

# Now we can get chart data easily

In [55]:
get_category_topkey('PERSON','政治',5)

{'wf_pairs': [('黃重凱', 24), ('柳惠千', 13), ('喬建中', 12), ('徐國勇', 11), ('季欽', 8)],
 'data_barchart': {'category': '政治',
  'labels': ['黃重凱', '柳惠千', '喬建中', '徐國勇', '季欽'],
  'values': [24, 13, 12, 11, 8]},
 'data_cloud': [{'text': '黃重凱', 'size': 80},
  {'text': '柳惠千', 'size': 31},
  {'text': '喬建中', 'size': 27},
  {'text': '徐國勇', 'size': 23},
  {'text': '季欽', 'size': 10}]}

In [56]:
get_category_topkey('PRODUCT','全部',5)

{'wf_pairs': [('iPhone SE', 8),
  ('iPad Air', 8),
  ('M1 Ultra', 6),
  ('iPhone', 5),
  ('Mac Studio', 5)],
 'data_barchart': {'category': '全部',
  'labels': ['iPhone SE', 'iPad Air', 'M1 Ultra', 'iPhone', 'Mac Studio'],
  'values': [8, 8, 6, 5, 5]},
 'data_cloud': [{'text': 'iPhone SE', 'size': 80},
  {'text': 'iPad Air', 'size': 80},
  {'text': 'M1 Ultra', 'size': 33},
  {'text': 'iPhone', 'size': 10},
  {'text': 'Mac Studio', 'size': 10}]}

In [57]:
get_category_topkey('EVENT','政治',5)

{'wf_pairs': [('COVID-19（2019冠狀病毒疾病）疫情', 1), ('俄烏戰爭', 1)],
 'data_barchart': {'category': '政治',
  'labels': ['COVID-19（2019冠狀病毒疾病）疫情', '俄烏戰爭'],
  'values': [1, 1]},
 'data_cloud': [{'text': 'COVID-19（2019冠狀病毒疾病）疫情', 'size': 45},
  {'text': '俄烏戰爭', 'size': 45}]}

# Compelete Functions in Django views.py

In [ ]:
from django.shortcuts import render
import pandas as pd

from django.http import  JsonResponse
from django.views.decorators.csrf import csrf_exempt

'''
{'CARDINAL': {'政治': [('2020', 249),
   ('10', 170),
   ('15', 113),
   ('13', 105),
  ...
  }
'''

# ne names
ne_name =['EVENT','FAC','GPE','LANGUAGE','LAW','LOC','NORP','ORG','PERSON','PRODUCT','WORK_OF_ART']
idx2nename = { str(i) : item for i, item in enumerate(ne_name)}
'''
{0: 'EVENT',
 1: 'FAC',
 2: 'GPE',
 3: 'LANGUAGE',
 4: 'LAW',
 5: 'LOC',
 6: 'NORP',
 7: 'ORG',
 8: 'PERSON',
 9: 'PRODUCT',
 10: 'WORK_OF_ART'}

Name	Description
CARDINAL	數字
DATE	日期
EVENT	事件
FAC	設施
GPE	行政區
LANGUAGE	語言
LAW	法律
LOC	地理區
MONEY	金錢
NORP	民族、宗教、政治團體
ORDINAL	序數
ORG	組織
PERCENT	百分比率
PERSON	人物
PRODUCT	產品
QUANTITY	數量
TIME	時間
WORK_OF_ART	作品

'''

# category names
news_categories=['政治','科技','運動','證卷','產經','娛樂','生活','國際','社會','文化','兩岸','全部']
idx2cate = { str(i) : item for i, item in enumerate(news_categories)}
'''
{'0': '政治',
 '1': '科技',
 '2': '運動',
 '3': '證卷',
 '4': '產經',
 '5': '娛樂',
 '6': '生活',
 '7': '國際',
 '8': '社會',
 '9': '文化',
 '10': '兩岸',
 '11': '全部'}
'''

def load_data_topNer():
    # read data
    df_data = pd.read_csv('app_top_ner/dataset/news_topkey_by_ner_and_category.csv')

    global data
    data = {}
    for idx, (nerName, topKeys) in df_data.iterrows():
        data[nerName] = dict(eval(topKeys))


# We should call load_data() at first.
load_data_topNer()

def home(request):
    return render(request,'app_top_ner/home.html')

# When Post is used, the csrf of this function should be ignored
@csrf_exempt
def api_get_cat_topkey(request):

    # POST方式取得新聞類別
    cate = request.POST.get('news_category')
    cate = idx2cate[cate]

    # 取得多少筆關鍵詞
    topk = int(request.POST.get('topk'))

    ner_value = request.POST.get('ner_value')
    ner_value = idx2nename[ner_value]

    print(ner_value, cate, topk)

    responseData = get_category_topkey(ner_value, cate, topk)
    response = {'data': responseData }
    print(response)
    return JsonResponse(response)


# Cloud chart
# text size based on the value of word frequency for drawing cloud chart
'''
    clouddata=[{
      'text': '台北市',
      'size': 40
    },
    {
      'text': '高雄市',
      'size': 15
    },
    {
      'text': '台北市',
      'size': 25
    }]
'''

def get_category_topkey(ner_value, cate, topk):

    wf_pairs = data[ner_value][cate][0:topk]

    if wf_pairs == []:
        return []

    words = [w for w, f in wf_pairs]
    freqs = [f for w, f in wf_pairs]

    # Prepare cloud chart data
    # the minimum and maximum frequency of top words
    min_ = wf_pairs[-1][1]  # the last line is smaller
    max_ = wf_pairs[0][1]   # the first frequency value is larger

    textSizeMin = 10
    textSizeMax = 90

    # if all frequences are the same, "divided by zero" exception will arise.
    # In the following case, exception will arise.
    # We must deal with this.
    # [('AA', 1), ('BB', 1), ('CC', 1)]
    # Instead of (max_-min_), we use len(wf_pairs) as divisor.
    # every word size is equal. 
    # 當每個字的頻率都一樣時，讓每個字的高度大小都一樣，分子是1，分母是字數==>1/len(wf_pairs)
    if (min_ != max_):
        max_min_range = max_ - min_

    else:
        max_min_range = len(wf_pairs)
        min_ = min_ - 1 

    # cloud chart data
    # using proportional scaling
    clouddata = [{'text':w, 'size':int(textSizeMin+(f - min_)/max_min_range*(textSizeMax-textSizeMin))} for w, f in wf_pairs]

    responseData = {
        "wf_pairs": wf_pairs,
        "data_barchart":{
                        "category": cate,
                        "labels": words,
                        "values": freqs
                        },
        "data_cloud": clouddata}
    return responseData


print("app_top_ner載入成功!")

# For your references

In [ ]:
# This is an alternative way for your reference
data={}
for idx, row in df_data.iterrows():
    # for each category
    cate_wf={} # category-word-frequency
    for cate, topkeys in eval(row['top_keys']):
        cate_wf[cate] = topkeys
    # for every ner 
    data[row['ne_name']] = cate_wf

In [ ]:
# This is an alternative way for your reference
data={}
for idx in range(len(df_data)):
    # for each category
    cate_wf={} # category-word-frequency
    for cate, wf in eval(df_data.iloc[idx, 1]): #iloc
        cate_wf[cate] = wf
    # for each ner 
    data[df_data.iloc[idx,0]] = cate_wf

In [ ]:
# This is an alternative way for your reference
data={}
for idx in range(len(df_data)):
    # for each category
    cate_wf={} # category-word-frequency
    for cate, wf in eval(df_data.loc[idx, 'top_keys']): #loc
        cate_wf[cate] = wf
    # for each ner 
    data[df_data.loc[idx,'ne_name']] = cate_wf