# Classifier transfor leaning from LLM 情緒類別分類器(遷移學習)

This is a comprahensive notebook and tutorial on how to fine tune the `qwen-0.5b` classification model

Fine-tuning Qwen-0.5B (a smaller model) with LoRA (Low-Rank Adaptation) is an efficient approach that requires less computational power.

It got a classification accuracy of 0.93.

# Colab GPU
## 設定執行階段 變更執行階段類型 硬體加速器  選取GPU

In [1]:
!nvidia-smi

Thu Apr  3 20:49:27 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.09                 Driver Version: 561.09         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  |   00000000:01:00.0 Off |                  Off |
| 46%   69C    P2            407W /  450W |    2818MiB /  24564MiB |     87%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     33960      C   ...ang\miniconda3\envs\ai24\python.exe      N/A      |
+-----------------------------------------------------------------------------------------+

In [2]:
# 列出GPU與CPU資源
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 16644549555763398029
xla_global_id: -1
]

In [3]:
# Specify the GPU device to use
#import os
#os.environ["CUDA_VISIBLE_DEVICES"] = "0"

## Ubuntu版本資訊

In [4]:
!lsb_release -a

'lsb_release' ���O�����Υ~���R�O�B�i���檺�{���Χ妸�ɡC

# 掛載雲端硬碟

In [5]:
# from google.colab import drive
# drive.mount('/content/drive')

# 切換工作目錄到雲端硬碟目錄下(取用資料比較方便，可以用相對路徑)

你要改成你自己雲端硬碟目錄的路徑，可複製路徑並貼上，不要用鍵盤輸入!

In [6]:
# cd to_your_folder
# cd命令的前面一行不要加上說明文字，否則colab的cd會認不得指令

# Insatll packages


        transformers: For model handling.
        peft: For LoRA integration.
        datasets: For dataset handling.
        accelerate: For distributed training.
        bitsandbytes: For memory-efficient training (optional but useful for Qwen).

In [7]:
#!pip install transformers peft datasets accelerate bitsandbytes

In [ ]:
import torch
import datasets
import pandas as pd
import evaluate
import numpy as np

# Load Huggingface transformers
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForCausalLM
from transformers import TrainingArguments, Trainer
from transformers import BertTokenizer, BertTokenizerFast, BertForSequenceClassification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch

WARNING:tensorflow:From c:\Users\clhuang\miniconda3\envs\ai24\lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [9]:
# Setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

Using device: cuda

# Read data

簡體中文資料，資料集來自於網路，轉換成繁體中文

In [10]:
df = pd.read_csv('./dataset_reviews.csv', sep='|')

In [11]:
df

                                                    text  label
0      做父母一定要有劉墉這樣的心態，不斷地學習，不斷地進步，不斷地給自己補充新鮮血液，讓自己保持一...      1
1      作者真有英國人嚴謹的風格，提出觀點、進行論述論證，儘管本人對物理學瞭解不深，但是仍然能感受到...      1
2      作者長篇大論借用詳細報告數據處理工作和計算結果支持其新觀點。為什麼荷蘭曾經縣有歐洲最高的生產...      1
3      作者在戰幾時之前用了〞擁抱〞令人叫絕．日本如果沒有戰敗，就有會有美軍的佔領，沒胡官僚主義的延...      1
4      作者在少年時即喜閱讀，能看出他精讀了無數經典，因而他有一個龐大的內心世界。他的作品最難能可貴...      1
...                                                  ...    ...
80437                                 以前幾乎天天吃，現在調料什麼都不放，      0
80438           昨天訂涼皮兩份，什麼調料都沒有放，就放了點麻油，特別難吃，丟了一份，再也不想吃了      0
80439                                          涼皮太辣,吃不下都      0
80440                                       本來遲到了還自己點！！！      0
80441                  肉夾饃不錯，羊肉泡饃醬肉包很一般。涼麪沒想象中好吃。送餐倒是很快。      0

[80442 rows x 2 columns]

In [12]:
df.dtypes

text     object
label     int64
dtype: object

# Convert the format of y 

Convert the format of y from int to LongTensor

## Convert label using one-hot representation 輸出資料格式one-hot轉換
    
    轉成用2個節點表達兩類
    類別0: [1 0]  
    類別1: [0 1]  


    如果是3個類別用3個節點表之:
    類別0: [1 0 0]  
    類別1: [0 1 0]  
    類別2: [0 0 1]

負面情緒Negative 0 --> [1 0] 

正面情緒Positive 1 --> [0 1] 

## Easy Represention 0,1,2... (內部會自動轉換為one-hot)

    負面情緒Negative 0 --> [0] 

    正面情緒Positive 1 --> [1] 

    如果是3個類別
    中立情緒 Neutral 2 --> [2]

In [13]:
# Map labels to integers
categories=['負面','正面']

In [14]:

label_to_id = { cate : i for i, cate in enumerate(categories)}

In [15]:
label_to_id

{'負面': 0, '正面': 1}

In [16]:
id_to_label = { i : cate for i, cate in enumerate(categories)}

In [17]:
id_to_label

{0: '負面', 1: '正面'}

# Sample some examples for demonstration

In [ ]:
df = df.sample(20000)

# Conver pandas dataframe to Huggingface Dataset

In [19]:
dataset = datasets.Dataset.from_pandas(df, preserve_index=False)
# eval_data = Dataset.from_pandas(X_eval)

In [20]:
dataset

Dataset({
    features: ['text', 'label'],
    num_rows: 80442
})

In [21]:
dataset[0]

{'text': '做父母一定要有劉墉這樣的心態，不斷地學習，不斷地進步，不斷地給自己補充新鮮血液，讓自己保持一顆年輕的心。我想，這是他能很好的和孩子溝通的一個重要因素。讀劉墉的文章，總能讓我看到一個快樂的平易近人的父親，他始終站在和孩子同樣的高度，給孩子創造著一個充滿愛和自由的生活環境。很喜歡劉墉在字裡行間流露出的做父母的那種小狡黠，讓人總是忍俊不禁，父母和子女之間有時候也是一種戰鬥，武力爭鬥過於低級了，智力較量才更有趣味。所以，做父母的得加把勁了，老思想老觀念注定會一敗塗地，生命不息，學習不止。家庭教育，真的是樂在其中。',
 'label': 1}

In [22]:
dataset.to_pandas().head(5)

                                                text  label
0  做父母一定要有劉墉這樣的心態，不斷地學習，不斷地進步，不斷地給自己補充新鮮血液，讓自己保持一...      1
1  作者真有英國人嚴謹的風格，提出觀點、進行論述論證，儘管本人對物理學瞭解不深，但是仍然能感受到...      1
2  作者長篇大論借用詳細報告數據處理工作和計算結果支持其新觀點。為什麼荷蘭曾經縣有歐洲最高的生產...      1
3  作者在戰幾時之前用了〞擁抱〞令人叫絕．日本如果沒有戰敗，就有會有美軍的佔領，沒胡官僚主義的延...      1
4  作者在少年時即喜閱讀，能看出他精讀了無數經典，因而他有一個龐大的內心世界。他的作品最難能可貴...      1

# Load Tokenizer

In [23]:

# model_id = "google/gemma-3-1b"
# model_id = "Qwen/Qwen2.5-0.5B"
model_id = "Qwen/Qwen2.5-0.5B-instruct"

In [24]:
tokenizer = AutoTokenizer.from_pretrained(model_id)

In [25]:
# 必須在Huggingface註冊，取得API token才能下載模型
#access_token = "???"
#tokenizer = AutoTokenizer.from_pretrained(model_id, token=access_token)

# Tokenzie text

In [26]:
def tokenize_function(example):
    return tokenizer(
        example["text"], 
        #padding="max_length", 
        max_length=512,
        truncation=True, 
    )

#tokenized_dataset = dataset
tokenized_dataset = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/80442 [00:00<?, ? examples/s]

In [27]:
tokenized_dataset

Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 80442
})

In [28]:
# tokenized_dataset[0]

# Split dataset for training and testing

# Split dataset: Train, Test (Val) 

Training set: 訓練資料集 -->給模型讀進去訓練

Test set: 測試資料集 -->驗證或測試模型的準確度

Split dataset into 90% for training and 10% for testing

In [29]:
tokenized_dataset = tokenized_dataset.train_test_split(test_size=0.05, seed=1234)
train_data = tokenized_dataset["train"]
test_data = tokenized_dataset["test"]

In [30]:
train_data

Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 76419
})

In [31]:
print(test_data)

Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 4023
})

In [32]:
train_data[0]

{'text': '不滿意，色差太大！做工一般！！',
 'label': 0,
 'input_ids': [16530,
  101496,
  36589,
  3837,
  38035,
  99572,
  102791,
  6313,
  115238,
  100141,
  31251],
 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

#  定義Model

這裡的做法有簡單的版本也有複雜的版本

簡單版:


        model = AutoModelForSequenceClassification.from_pretrained(
            model_id,  # 模型名稱
            num_labels=len(categories),  # Number of output labels
        )


複雜版:

In [33]:
from transformers import Qwen2Model, Trainer, TrainingArguments, AutoTokenizer, AutoModel
from torch import nn
from transformers.modeling_outputs import SequenceClassifierOutput
import os

In [ ]:
import torch
import os
import torch.nn.functional as F
from torch import nn

class QwenForClassifier(nn.Module):
    def __init__(self, base_model, hidden_size, num_labels):
        super(QwenForClassifier, self).__init__()
        # 凍結 base model 的參數
        self.base_model = base_model
        
        for param in self.base_model.parameters():
            param.requires_grad = False
            
        # 注意力池化機制
        self.attention_pooler = nn.Sequential(
            nn.Linear(hidden_size, 128),
            nn.Tanh(),
            nn.Linear(128, 1)
        )
        
        # 多層融合權重 (最後4層)
        self.layer_weights = nn.Parameter(torch.ones(4) / 4)
        
        # 增強型分類器
        self.classifier = nn.Sequential(
            nn.Linear(hidden_size, 256),
            nn.LayerNorm(256),
            nn.GELU(),
            nn.Dropout(0.2),
            
            nn.Linear(256, 128),
            nn.LayerNorm(128),
            nn.GELU(),
            nn.Dropout(0.1),
            
            nn.Linear(128, num_labels)
        )
        
        # 保存配置
        self.config = base_model.config
        self.config.num_labels = num_labels
    
    def forward(self, input_ids, attention_mask=None, labels=None):
        # 獲取所有隱藏層狀態
        outputs = self.base_model(
            input_ids=input_ids, 
            attention_mask=attention_mask,
            output_hidden_states=True
        )
        
        # 獲取最後4層隱藏狀態
        hidden_states = outputs.hidden_states
        if hidden_states is None:
            # 如果模型沒有返回hidden_states，使用last_hidden_state
            last_hidden = outputs.last_hidden_state
            sequence_output = last_hidden
        else:
            # 融合最後4層 (或可用層數)
            last_layers = hidden_states[-4:] if len(hidden_states) >= 4 else hidden_states[1:]
            layer_weights = F.softmax(self.layer_weights[:len(last_layers)], dim=0)
            
            # 加權融合多層特徵
            sequence_output = torch.zeros_like(last_layers[0])
            for i, layer in enumerate(last_layers):
                sequence_output += layer_weights[i].unsqueeze(-1).unsqueeze(-1) * layer
        
        # 注意力池化
        attention_scores = self.attention_pooler(sequence_output)
        attention_probs = F.softmax(attention_scores, dim=1)
        context_vector = torch.matmul(attention_probs.transpose(-1, -2), sequence_output).squeeze(1)
        
        # 也計算平均池化向量
        mean_pooled = torch.mean(sequence_output, dim=1)
        
        # 結合注意力池化和平均池化 (殘差連接)
        combined_repr = context_vector + mean_pooled
            
        # 分類預測
        logits = self.classifier(combined_repr)
        
        # 計算損失
        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            loss = loss_fct(logits, labels)
            
        return {"loss": loss, "logits": logits}
    
    def save_model(self, output_dir=None):
        """保存分類器權重和配置"""
        os.makedirs(output_dir, exist_ok=True)
        
        # 保存分類器權重
        classifier_path = os.path.join(output_dir, "classifier_weights.pt")
        model_dict = {
            'classifier': self.classifier.state_dict(),
            'attention_pooler': self.attention_pooler.state_dict(),
            'layer_weights': self.layer_weights,
            'config': {
                'num_labels': self.config.num_labels,
                'hidden_size': self.config.hidden_size
            }
        }
        torch.save(model_dict, classifier_path)
        print(f"已保存分類器權重至 {classifier_path}")
    
    def load_model(self, model_dir, device=None):
        """載入分類器權重"""
        if device is None:
            device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
            
        classifier_path = os.path.join(model_dir, "classifier_weights.pt")
        if os.path.exists(classifier_path):
            model_dict = torch.load(classifier_path, map_location=device, weights_only=True)
            
            # 載入各組件
            self.classifier.load_state_dict(model_dict['classifier'])
            self.attention_pooler.load_state_dict(model_dict['attention_pooler'])
            self.layer_weights.data = model_dict['layer_weights'].to(device)
            
            print(f"已載入分類器權重: {classifier_path}")
            return True
        else:
            print(f"警告: 找不到分類器權重檔案 {classifier_path}")
            return False

## 初始化模型


        分類任務：兩者都可用，但 AutoModel 更輕量
        生成功能：只有 AutoModelForCausalLM 支持
        內存使用：AutoModelForCausalLM 通常較大，因為包含了完整的語言模型頭
        在 Qwen2 情感分類模型中，使用 AutoModelForCausalLM 更為靈活，因為它既可以進行分類，也保留了原始的文本生成功能。



        # AutoModelForCausalLM 輸出
        outputs = base_model(input_ids, attention_mask)
        # 輸出包含：
        # - loss: (可選) 語言模型損失
        # - logits: 張量，形狀為 [batch_size, sequence_length, vocab_size]
        # - past_key_values: (可選) 用於加速解碼的過去狀態
        # - hidden_states: (可選) 所有隱藏層狀態的元組
        # - attentions: (可選) 注意力權重的元組


        # AutoModel 輸出
        outputs = base_model(input_ids, attention_mask)
        # 輸出包含：
        # - last_hidden_state: 張量，形狀為 [batch_size, sequence_length, hidden_size]
        # - hidden_states: (可選) 所有隱藏層狀態的元組
        # - attentions: (可選) 注意力權重的元組

In [36]:
len(categories)

2

In [37]:
# 在外部先載入base_model預訓練權重(不包含分類層)
full_model = AutoModelForCausalLM.from_pretrained(model_id)
#
hidden_size = full_model.config.hidden_size
model = QwenForClassifier(full_model.model, hidden_size, num_labels= len(categories))

# 移動到指定設備
model = model.to(device)

In [38]:
full_model.model

Qwen2Model(
  (embed_tokens): Embedding(151936, 896)
  (layers): ModuleList(
    (0-23): 24 x Qwen2DecoderLayer(
      (self_attn): Qwen2SdpaAttention(
        (q_proj): Linear(in_features=896, out_features=896, bias=True)
        (k_proj): Linear(in_features=896, out_features=128, bias=True)
        (v_proj): Linear(in_features=896, out_features=128, bias=True)
        (o_proj): Linear(in_features=896, out_features=896, bias=False)
        (rotary_emb): Qwen2RotaryEmbedding()
      )
      (mlp): Qwen2MLP(
        (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
        (up_proj): Linear(in_features=896, out_features=4864, bias=False)
        (down_proj): Linear(in_features=4864, out_features=896, bias=False)
        (act_fn): SiLU()
      )
      (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
    )
  )
  (norm): Qwen2RMSNorm((896,), eps=1e-06)
  (rotary_emb): Qwen2RotaryEmbedding()
)

In [39]:
full_model.base_model

Qwen2Model(
  (embed_tokens): Embedding(151936, 896)
  (layers): ModuleList(
    (0-23): 24 x Qwen2DecoderLayer(
      (self_attn): Qwen2SdpaAttention(
        (q_proj): Linear(in_features=896, out_features=896, bias=True)
        (k_proj): Linear(in_features=896, out_features=128, bias=True)
        (v_proj): Linear(in_features=896, out_features=128, bias=True)
        (o_proj): Linear(in_features=896, out_features=896, bias=False)
        (rotary_emb): Qwen2RotaryEmbedding()
      )
      (mlp): Qwen2MLP(
        (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
        (up_proj): Linear(in_features=896, out_features=4864, bias=False)
        (down_proj): Linear(in_features=4864, out_features=896, bias=False)
        (act_fn): SiLU()
      )
      (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
    )
  )
  (norm): Qwen2RMSNorm((896,), eps=1e-06)
  (rotary_emb): Qwen2RotaryEmbedding()
)

## 看看base_model與model有何不同?

model內部有: 一個base_model+輸出分類層。它被拼接為分類器，可以做兩個類別的分類

base_model仍舊是GPT自回歸模型

但是在記憶體，兩者是共享同一份base_model權重，model有多一個分類器的輸出層的部分

In [40]:
full_model

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2SdpaAttention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
          (rotary_emb): Qwen2RotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=896, out_features=151936, bias=False)
)

In [41]:
model

QwenForClassifier(
  (base_model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2SdpaAttention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
          (rotary_emb): Qwen2RotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (attention_pooler): Sequential(
    (0): Linear(in_features=896, out_features=128, bias=True)
    (1): Tanh()
    (2): Linear(in_features=128, out_features=1, bias=True)
  )
  (classifier): Sequential(
    (0): Linear(in_features=896, out_features=256, bias=True)
    (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (2): GELU(approximate='none')
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=256, out_features=128, bias=True)
    (5): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (6): GELU(approximate='none')
    (7): Dropout(p=0.1, inplace=False)
    (8): Linear(in_features=128, out_features=2, bias=True)
  )
)

In [42]:
# 這與model是一樣的模型??
model.base_model

Qwen2Model(
  (embed_tokens): Embedding(151936, 896)
  (layers): ModuleList(
    (0-23): 24 x Qwen2DecoderLayer(
      (self_attn): Qwen2SdpaAttention(
        (q_proj): Linear(in_features=896, out_features=896, bias=True)
        (k_proj): Linear(in_features=896, out_features=128, bias=True)
        (v_proj): Linear(in_features=896, out_features=128, bias=True)
        (o_proj): Linear(in_features=896, out_features=896, bias=False)
        (rotary_emb): Qwen2RotaryEmbedding()
      )
      (mlp): Qwen2MLP(
        (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
        (up_proj): Linear(in_features=896, out_features=4864, bias=False)
        (down_proj): Linear(in_features=4864, out_features=896, bias=False)
        (act_fn): SiLU()
      )
      (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
    )
  )
  (norm): Qwen2RMSNorm((896,), eps=1e-06)
  (rotary_emb): Qwen2RotaryEmbedding()
)

# 模型怎麼用?

尚未訓練的模型 (classifier的數據都是0)

In [43]:

# Function to make predictions
def predict_sentiment(text, model, tokenizer, device):
    # Tokenize the input text
    inputs = tokenizer(
        text,
        max_length=512,
        truncation=True,
        return_tensors="pt"
    ).to(device)
    
    # Get model predictions
    with torch.no_grad():
        outputs = model(**inputs)
    
    # Extract logits and apply softmax to get probabilities
    # logits = outputs.logits
    logits = outputs["logits"]  # 取出 logits
    
    
    probabilities = torch.nn.functional.softmax(logits, dim=-1)
    
    # Get the predicted class (0: negative, 1: positive)
    predicted_class = torch.argmax(probabilities, dim=-1).item()
    
    # Get the class name using id_to_label
    predicted_label = id_to_label[predicted_class]
    
    # Get the confidence score
    confidence = probabilities[0][predicted_class].item()
    
    return {
        "text": text,
        "sentiment": predicted_label,
        "confidence": round(confidence,2),
        "probabilities": {
            id_to_label[i]: round(prob.item(),2) for i, prob in enumerate(probabilities[0])
        }
    }

In [44]:
text = "今天天氣真好，我很開心"
predict_sentiment(text, model, tokenizer, device)

{'text': '今天天氣真好，我很開心',
 'sentiment': '正面',
 'confidence': 0.6,
 'probabilities': {'負面': 0.4, '正面': 0.6}}

In [45]:
text = "這個產品品質差，服務更糟糕"
predict_sentiment(text, model, tokenizer, device)

{'text': '這個產品品質差，服務更糟糕',
 'sentiment': '正面',
 'confidence': 0.6,
 'probabilities': {'負面': 0.4, '正面': 0.6}}

In [46]:
text = "這家餐廳的食物美味，環境也很舒適"
predict_sentiment(text, model, tokenizer, device)

{'text': '這家餐廳的食物美味，環境也很舒適',
 'sentiment': '正面',
 'confidence': 0.53,
 'probabilities': {'負面': 0.47, '正面': 0.53}}

## 模型每個參數層都是Trainable

In [47]:
def print_model_details(model):
    print("\n" + "="*80)
    print("MODEL ARCHITECTURE WITH TRAINABILITY STATUS")
    print("="*80)
    
    trainable_params = 0
    non_trainable_params = 0
    
    # Print each layer with details
    for idx, (name, layer) in enumerate(model.named_modules(), 1):
        if not list(layer.named_children()):  # Only print leaf nodes (actual layers)
            param_count = sum(p.numel() for p in layer.parameters())
            status = "TRAINABLE" if any(p.requires_grad for p in layer.parameters()) else "NON-TRAINABLE"
            
            print(f"\nLayer #{idx:02d}")
            print(f"├─ Name: {name}")
            print(f"├─ Type: {layer.__class__.__name__}")
            print(f"├─ Details: {layer}")
            print(f"├─ Parameters: {param_count:,}")
            print(f"└─ Status: {status}")
            
            if status == "TRAINABLE":
                trainable_params += param_count
            else:
                non_trainable_params += param_count
    
    total_params = trainable_params + non_trainable_params
    trainable_percentage = (trainable_params / total_params) * 100 if total_params > 0 else 0
    
    print("\n" + "="*80)
    print(f"Total Trainable Parameters: {trainable_params:,}")
    print(f"Total Non-Trainable Parameters: {non_trainable_params:,}")
    print(f"Total Parameters: {total_params:,}")
    print(f"Trainable Parameters Percentage: {trainable_percentage:.2f}%")
    print("="*80)

In [48]:
print_model_details(model)

================================================================================
MODEL ARCHITECTURE WITH TRAINABILITY STATUS
================================================================================

Layer #03
├─ Name: base_model.embed_tokens
├─ Type: Embedding
├─ Details: Embedding(151936, 896)
├─ Parameters: 136,134,656
└─ Status: NON-TRAINABLE

Layer #07
├─ Name: base_model.layers.0.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #08
├─ Name: base_model.layers.0.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #09
├─ Name: base_model.layers.0.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #10
├─ Name: base_model.layers.0.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #11
├─ Name: base_model.layers.0.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #13
├─ Name: base_model.layers.0.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #14
├─ Name: base_model.layers.0.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #15
├─ Name: base_model.layers.0.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #16
├─ Name: base_model.layers.0.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #17
├─ Name: base_model.layers.0.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #18
├─ Name: base_model.layers.0.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #21
├─ Name: base_model.layers.1.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #22
├─ Name: base_model.layers.1.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #23
├─ Name: base_model.layers.1.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #24
├─ Name: base_model.layers.1.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #25
├─ Name: base_model.layers.1.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #27
├─ Name: base_model.layers.1.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #28
├─ Name: base_model.layers.1.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #29
├─ Name: base_model.layers.1.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #30
├─ Name: base_model.layers.1.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #31
├─ Name: base_model.layers.1.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #32
├─ Name: base_model.layers.1.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #35
├─ Name: base_model.layers.2.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #36
├─ Name: base_model.layers.2.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #37
├─ Name: base_model.layers.2.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #38
├─ Name: base_model.layers.2.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #39
├─ Name: base_model.layers.2.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #41
├─ Name: base_model.layers.2.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #42
├─ Name: base_model.layers.2.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #43
├─ Name: base_model.layers.2.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #44
├─ Name: base_model.layers.2.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #45
├─ Name: base_model.layers.2.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #46
├─ Name: base_model.layers.2.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #49
├─ Name: base_model.layers.3.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #50
├─ Name: base_model.layers.3.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #51
├─ Name: base_model.layers.3.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #52
├─ Name: base_model.layers.3.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #53
├─ Name: base_model.layers.3.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #55
├─ Name: base_model.layers.3.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #56
├─ Name: base_model.layers.3.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #57
├─ Name: base_model.layers.3.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #58
├─ Name: base_model.layers.3.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #59
├─ Name: base_model.layers.3.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #60
├─ Name: base_model.layers.3.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #63
├─ Name: base_model.layers.4.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #64
├─ Name: base_model.layers.4.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #65
├─ Name: base_model.layers.4.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #66
├─ Name: base_model.layers.4.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #67
├─ Name: base_model.layers.4.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #69
├─ Name: base_model.layers.4.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #70
├─ Name: base_model.layers.4.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #71
├─ Name: base_model.layers.4.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #72
├─ Name: base_model.layers.4.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #73
├─ Name: base_model.layers.4.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #74
├─ Name: base_model.layers.4.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #77
├─ Name: base_model.layers.5.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #78
├─ Name: base_model.layers.5.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #79
├─ Name: base_model.layers.5.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #80
├─ Name: base_model.layers.5.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #81
├─ Name: base_model.layers.5.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #83
├─ Name: base_model.layers.5.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #84
├─ Name: base_model.layers.5.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #85
├─ Name: base_model.layers.5.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #86
├─ Name: base_model.layers.5.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #87
├─ Name: base_model.layers.5.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #88
├─ Name: base_model.layers.5.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #91
├─ Name: base_model.layers.6.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #92
├─ Name: base_model.layers.6.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #93
├─ Name: base_model.layers.6.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #94
├─ Name: base_model.layers.6.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #95
├─ Name: base_model.layers.6.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #97
├─ Name: base_model.layers.6.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #98
├─ Name: base_model.layers.6.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #99
├─ Name: base_model.layers.6.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #100
├─ Name: base_model.layers.6.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #101
├─ Name: base_model.layers.6.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #102
├─ Name: base_model.layers.6.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #105
├─ Name: base_model.layers.7.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #106
├─ Name: base_model.layers.7.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #107
├─ Name: base_model.layers.7.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #108
├─ Name: base_model.layers.7.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #109
├─ Name: base_model.layers.7.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #111
├─ Name: base_model.layers.7.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #112
├─ Name: base_model.layers.7.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #113
├─ Name: base_model.layers.7.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #114
├─ Name: base_model.layers.7.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #115
├─ Name: base_model.layers.7.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #116
├─ Name: base_model.layers.7.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #119
├─ Name: base_model.layers.8.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #120
├─ Name: base_model.layers.8.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #121
├─ Name: base_model.layers.8.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #122
├─ Name: base_model.layers.8.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #123
├─ Name: base_model.layers.8.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #125
├─ Name: base_model.layers.8.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #126
├─ Name: base_model.layers.8.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #127
├─ Name: base_model.layers.8.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #128
├─ Name: base_model.layers.8.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #129
├─ Name: base_model.layers.8.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #130
├─ Name: base_model.layers.8.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #133
├─ Name: base_model.layers.9.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #134
├─ Name: base_model.layers.9.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #135
├─ Name: base_model.layers.9.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #136
├─ Name: base_model.layers.9.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #137
├─ Name: base_model.layers.9.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #139
├─ Name: base_model.layers.9.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #140
├─ Name: base_model.layers.9.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #141
├─ Name: base_model.layers.9.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #142
├─ Name: base_model.layers.9.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #143
├─ Name: base_model.layers.9.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #144
├─ Name: base_model.layers.9.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #147
├─ Name: base_model.layers.10.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #148

In [49]:
# 檢查原始參數是否可訓練
# print("Classifier weight requires_grad:", model.classifier.weight.requires_grad)

## 模型主體固定參數，只有極少數參數是Trainable

In [50]:
#model.print_trainable_parameters()

In [51]:
def print_trainable_parameters(model):
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    all_params = sum(p.numel() for p in model.parameters())
    print(f"trainable params: {trainable_params:,d} || all params: {all_params:,d} || trainable%: {100 * trainable_params / all_params:.2f}%")

In [52]:
print_trainable_parameters(model)

trainable params: 378,503 || all params: 494,411,271 || trainable%: 0.08%

In [53]:
print_model_details(model)

================================================================================
MODEL ARCHITECTURE WITH TRAINABILITY STATUS
================================================================================

Layer #03
├─ Name: base_model.embed_tokens
├─ Type: Embedding
├─ Details: Embedding(151936, 896)
├─ Parameters: 136,134,656
└─ Status: NON-TRAINABLE

Layer #07
├─ Name: base_model.layers.0.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #08
├─ Name: base_model.layers.0.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #09
├─ Name: base_model.layers.0.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #10
├─ Name: base_model.layers.0.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #11
├─ Name: base_model.layers.0.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #13
├─ Name: base_model.layers.0.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #14
├─ Name: base_model.layers.0.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #15
├─ Name: base_model.layers.0.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #16
├─ Name: base_model.layers.0.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #17
├─ Name: base_model.layers.0.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #18
├─ Name: base_model.layers.0.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #21
├─ Name: base_model.layers.1.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #22
├─ Name: base_model.layers.1.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #23
├─ Name: base_model.layers.1.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #24
├─ Name: base_model.layers.1.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #25
├─ Name: base_model.layers.1.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #27
├─ Name: base_model.layers.1.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #28
├─ Name: base_model.layers.1.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #29
├─ Name: base_model.layers.1.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #30
├─ Name: base_model.layers.1.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #31
├─ Name: base_model.layers.1.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #32
├─ Name: base_model.layers.1.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #35
├─ Name: base_model.layers.2.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #36
├─ Name: base_model.layers.2.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #37
├─ Name: base_model.layers.2.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #38
├─ Name: base_model.layers.2.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #39
├─ Name: base_model.layers.2.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #41
├─ Name: base_model.layers.2.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #42
├─ Name: base_model.layers.2.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #43
├─ Name: base_model.layers.2.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #44
├─ Name: base_model.layers.2.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #45
├─ Name: base_model.layers.2.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #46
├─ Name: base_model.layers.2.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #49
├─ Name: base_model.layers.3.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #50
├─ Name: base_model.layers.3.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #51
├─ Name: base_model.layers.3.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #52
├─ Name: base_model.layers.3.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #53
├─ Name: base_model.layers.3.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #55
├─ Name: base_model.layers.3.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #56
├─ Name: base_model.layers.3.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #57
├─ Name: base_model.layers.3.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #58
├─ Name: base_model.layers.3.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #59
├─ Name: base_model.layers.3.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #60
├─ Name: base_model.layers.3.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #63
├─ Name: base_model.layers.4.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #64
├─ Name: base_model.layers.4.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #65
├─ Name: base_model.layers.4.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #66
├─ Name: base_model.layers.4.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #67
├─ Name: base_model.layers.4.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #69
├─ Name: base_model.layers.4.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #70
├─ Name: base_model.layers.4.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #71
├─ Name: base_model.layers.4.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #72
├─ Name: base_model.layers.4.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #73
├─ Name: base_model.layers.4.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #74
├─ Name: base_model.layers.4.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #77
├─ Name: base_model.layers.5.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #78
├─ Name: base_model.layers.5.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #79
├─ Name: base_model.layers.5.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #80
├─ Name: base_model.layers.5.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #81
├─ Name: base_model.layers.5.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #83
├─ Name: base_model.layers.5.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #84
├─ Name: base_model.layers.5.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #85
├─ Name: base_model.layers.5.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #86
├─ Name: base_model.layers.5.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #87
├─ Name: base_model.layers.5.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #88
├─ Name: base_model.layers.5.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #91
├─ Name: base_model.layers.6.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #92
├─ Name: base_model.layers.6.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #93
├─ Name: base_model.layers.6.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #94
├─ Name: base_model.layers.6.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #95
├─ Name: base_model.layers.6.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #97
├─ Name: base_model.layers.6.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #98
├─ Name: base_model.layers.6.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #99
├─ Name: base_model.layers.6.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #100
├─ Name: base_model.layers.6.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #101
├─ Name: base_model.layers.6.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #102
├─ Name: base_model.layers.6.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #105
├─ Name: base_model.layers.7.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #106
├─ Name: base_model.layers.7.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #107
├─ Name: base_model.layers.7.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #108
├─ Name: base_model.layers.7.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #109
├─ Name: base_model.layers.7.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #111
├─ Name: base_model.layers.7.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #112
├─ Name: base_model.layers.7.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #113
├─ Name: base_model.layers.7.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #114
├─ Name: base_model.layers.7.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #115
├─ Name: base_model.layers.7.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #116
├─ Name: base_model.layers.7.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #119
├─ Name: base_model.layers.8.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #120
├─ Name: base_model.layers.8.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #121
├─ Name: base_model.layers.8.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #122
├─ Name: base_model.layers.8.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #123
├─ Name: base_model.layers.8.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #125
├─ Name: base_model.layers.8.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #126
├─ Name: base_model.layers.8.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #127
├─ Name: base_model.layers.8.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #128
├─ Name: base_model.layers.8.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #129
├─ Name: base_model.layers.8.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #130
├─ Name: base_model.layers.8.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #133
├─ Name: base_model.layers.9.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #134
├─ Name: base_model.layers.9.self_attn.k_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #135
├─ Name: base_model.layers.9.self_attn.v_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=128, bias=True)
├─ Parameters: 114,816
└─ Status: NON-TRAINABLE

Layer #136
├─ Name: base_model.layers.9.self_attn.o_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=False)
├─ Parameters: 802,816
└─ Status: NON-TRAINABLE

Layer #137
├─ Name: base_model.layers.9.self_attn.rotary_emb
├─ Type: Qwen2RotaryEmbedding
├─ Details: Qwen2RotaryEmbedding()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #139
├─ Name: base_model.layers.9.mlp.gate_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #140
├─ Name: base_model.layers.9.mlp.up_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=4864, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #141
├─ Name: base_model.layers.9.mlp.down_proj
├─ Type: Linear
├─ Details: Linear(in_features=4864, out_features=896, bias=False)
├─ Parameters: 4,358,144
└─ Status: NON-TRAINABLE

Layer #142
├─ Name: base_model.layers.9.mlp.act_fn
├─ Type: SiLU
├─ Details: SiLU()
├─ Parameters: 0
└─ Status: NON-TRAINABLE

Layer #143
├─ Name: base_model.layers.9.input_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #144
├─ Name: base_model.layers.9.post_attention_layernorm
├─ Type: Qwen2RMSNorm
├─ Details: Qwen2RMSNorm((896,), eps=1e-06)
├─ Parameters: 896
└─ Status: NON-TRAINABLE

Layer #147
├─ Name: base_model.layers.10.self_attn.q_proj
├─ Type: Linear
├─ Details: Linear(in_features=896, out_features=896, bias=True)
├─ Parameters: 803,712
└─ Status: NON-TRAINABLE

Layer #148

## Use EOS token as padding

In [54]:
tokenizer.pad_token

'<|endoftext|>'

In [55]:
tokenizer.eos_token

'<|im_end|>'

In [56]:
model.pad_token_id = tokenizer.eos_token_id  # Use EOS token as padding

# Train

In [ ]:
      
class CustomTrainer(Trainer):
    def save_model(self, output_dir=None, _internal_call=False):
        """保存分類器權重和配置"""
        # 使用預設output_dir如果未指定
        output_dir = output_dir if output_dir is not None else self.args.output_dir
        os.makedirs(output_dir, exist_ok=True)
        
        # 保存分類器權重
        classifier_path = os.path.join(output_dir, "classifier_weights.pt")
        model_dict = {
            'classifier': self.model.classifier.state_dict(),
            'attention_pooler': self.model.attention_pooler.state_dict(), 
            'layer_weights': self.model.layer_weights,
            'config': {
                'num_labels': self.model.config.num_labels,
                'hidden_size': self.model.config.hidden_size
            }
        }
        
        # Save model config (required by HF Trainer)
        if hasattr(self.model, "config"):
            self.model.config.save_pretrained(output_dir)
        
        torch.save(model_dict, classifier_path)
        print(f"已保存分類器權重至 {classifier_path}")
        
        # 保存訓練狀態
        super().save_state()
        
        return output_dir

In [58]:
#metric = evaluate.combine(["accuracy", "f1", "precision", "recall"])
#metric = evaluate.combine(["accuracy"])
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)  # Convert probabilities to predicted labels
    metric = evaluate.load('accuracy')
    return metric.compute(predictions=predictions, references=labels)

In [ ]:
# requries several GB of GPU memory
training_args = TrainingArguments(
    output_dir="checkpoints_v4",  # Output directory for checkpoints
    learning_rate=5e-5,  # Learning rate for the optimizer
    weight_decay=0.01,  # Weight decay for regularization
    warmup_steps=500,
    seed=101,
    
    per_device_train_batch_size=26,  # Batch size per device
    per_device_eval_batch_size=3,  # Batch size per device for evaluation 
    
    num_train_epochs=5,  # Number of training epochs
    
    eval_strategy='steps',  # Evaluate after each epoch
    save_strategy="steps",  # Save model checkpoints after each epoch
    
    #load_best_model_at_end=True,  # Load the best model based on the chosen metric
    save_total_limit=2,
    push_to_hub=False,  # Disable pushing the model to the Hugging Face Hub 
    report_to="none",  # Disable logging to Weight&Bias
    #fp16=True, # 是否用此精度訓練Whether to use fp16 16-bit (mixed) precision training instead of 32-bit training.
    #bf16=True, # for 新型GPU 才能設定bf16
    logging_steps=1000,
)

In [60]:
trainer = CustomTrainer(
    model=model,  # The LoRA-adapted model
    #tokenizer=tokenizer,  # Tokenizer for the model
    processing_class=tokenizer,  # Tokenizer for the model
    
    train_dataset=train_data,  # Training dataset
    eval_dataset=test_data,  # Evaluation dataset
    args=training_args,  # Training arguments
    compute_metrics=compute_metrics,  # Function to calculate evaluation metrics
)

## Resume training from the last checkpoint if available

接續訓練

訓練後，手動載入之前訓練的分類器權重

In [ ]:

# checkpoint_path = "./checkpoints_v3/checkpoint-3167"
# model_path = "trained_classifier_v3"
# model.load_model(checkpoint_path)

## Let's train the model

In [62]:
%%time
model.config.use_cache = False  # Disable cache for faster training
trainer.train()
# trainer.train(resume_from_checkpoint=True) # Resume training from a checkpoint
#trainer.train(resume_from_checkpoint="./checkpoints_v1/checkpoint-19002")

  0%|          | 0/63685 [00:00<?, ?it/s]

Saved checkpoint classifier weights to checkpoints_v4\checkpoint-500\classifier_weights.pt
{'loss': 0.4608, 'grad_norm': 18.343847274780273, 'learning_rate': 1.9685954306351575e-05, 'epoch': 0.08}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2910600006580353, 'eval_accuracy': 0.8841660452398707, 'eval_runtime': 79.765, 'eval_samples_per_second': 50.436, 'eval_steps_per_second': 50.436, 'epoch': 0.08}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-1000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-1500\classifier_weights.pt
{'loss': 0.296, 'grad_norm': 8.61012077331543, 'learning_rate': 1.937190861270315e-05, 'epoch': 0.16}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.28874146938323975, 'eval_accuracy': 0.9025602783992046, 'eval_runtime': 70.4577, 'eval_samples_per_second': 57.098, 'eval_steps_per_second': 57.098, 'epoch': 0.16}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-2000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-2500\classifier_weights.pt
{'loss': 0.3063, 'grad_norm': 0.31581076979637146, 'learning_rate': 1.9057862919054724e-05, 'epoch': 0.24}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.28799575567245483, 'eval_accuracy': 0.9065374098931146, 'eval_runtime': 69.7269, 'eval_samples_per_second': 57.696, 'eval_steps_per_second': 57.696, 'epoch': 0.24}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-3000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-3500\classifier_weights.pt
{'loss': 0.3015, 'grad_norm': 3.852447509765625, 'learning_rate': 1.8743817225406297e-05, 'epoch': 0.31}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.3041049838066101, 'eval_accuracy': 0.9072831220482227, 'eval_runtime': 70.8214, 'eval_samples_per_second': 56.805, 'eval_steps_per_second': 56.805, 'epoch': 0.31}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-4000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-4500\classifier_weights.pt
{'loss': 0.3072, 'grad_norm': 1.6728307008743286, 'learning_rate': 1.842977153175787e-05, 'epoch': 0.39}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2940720319747925, 'eval_accuracy': 0.9120059656972409, 'eval_runtime': 71.4934, 'eval_samples_per_second': 56.271, 'eval_steps_per_second': 56.271, 'epoch': 0.39}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-5000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-5500\classifier_weights.pt
{'loss': 0.3155, 'grad_norm': 0.5128428936004639, 'learning_rate': 1.8115725838109447e-05, 'epoch': 0.47}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.29405730962753296, 'eval_accuracy': 0.9177230922197365, 'eval_runtime': 70.0337, 'eval_samples_per_second': 57.444, 'eval_steps_per_second': 57.444, 'epoch': 0.47}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-6000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-6500\classifier_weights.pt
{'loss': 0.3057, 'grad_norm': 29.301143646240234, 'learning_rate': 1.780168014446102e-05, 'epoch': 0.55}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2872559428215027, 'eval_accuracy': 0.9192145165299528, 'eval_runtime': 69.1817, 'eval_samples_per_second': 58.151, 'eval_steps_per_second': 58.151, 'epoch': 0.55}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-7000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-7500\classifier_weights.pt
{'loss': 0.309, 'grad_norm': 2.2051167488098145, 'learning_rate': 1.7487634450812593e-05, 'epoch': 0.63}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2940937578678131, 'eval_accuracy': 0.9184688043748447, 'eval_runtime': 68.8516, 'eval_samples_per_second': 58.43, 'eval_steps_per_second': 58.43, 'epoch': 0.63}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-8000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-8500\classifier_weights.pt
{'loss': 0.327, 'grad_norm': 0.2219666689634323, 'learning_rate': 1.717358875716417e-05, 'epoch': 0.71}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.29416000843048096, 'eval_accuracy': 0.9162316679095203, 'eval_runtime': 70.755, 'eval_samples_per_second': 56.858, 'eval_steps_per_second': 56.858, 'epoch': 0.71}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-9000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-9500\classifier_weights.pt
{'loss': 0.3086, 'grad_norm': 8.260422706604004, 'learning_rate': 1.6859543063515742e-05, 'epoch': 0.79}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2901947796344757, 'eval_accuracy': 0.9209545115585384, 'eval_runtime': 67.3611, 'eval_samples_per_second': 59.723, 'eval_steps_per_second': 59.723, 'epoch': 0.79}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-10000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-10500\classifier_weights.pt
{'loss': 0.2989, 'grad_norm': 13.166007041931152, 'learning_rate': 1.6545497369867315e-05, 'epoch': 0.86}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2807350158691406, 'eval_accuracy': 0.9219487944320159, 'eval_runtime': 68.803, 'eval_samples_per_second': 58.471, 'eval_steps_per_second': 58.471, 'epoch': 0.86}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-11000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-11500\classifier_weights.pt
{'loss': 0.2955, 'grad_norm': 9.170133590698242, 'learning_rate': 1.6231451676218892e-05, 'epoch': 0.94}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.28812116384506226, 'eval_accuracy': 0.9234402187422321, 'eval_runtime': 70.1023, 'eval_samples_per_second': 57.388, 'eval_steps_per_second': 57.388, 'epoch': 0.94}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-12000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-12500\classifier_weights.pt
{'loss': 0.3053, 'grad_norm': 15.482834815979004, 'learning_rate': 1.5917405982570465e-05, 'epoch': 1.02}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2838881313800812, 'eval_accuracy': 0.9236887894606015, 'eval_runtime': 70.7096, 'eval_samples_per_second': 56.895, 'eval_steps_per_second': 56.895, 'epoch': 1.02}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-13000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-13500\classifier_weights.pt
{'loss': 0.2833, 'grad_norm': 45.86884307861328, 'learning_rate': 1.560336028892204e-05, 'epoch': 1.1}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.29315826296806335, 'eval_accuracy': 0.9239373601789709, 'eval_runtime': 68.459, 'eval_samples_per_second': 58.765, 'eval_steps_per_second': 58.765, 'epoch': 1.1}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-14000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-14500\classifier_weights.pt
{'loss': 0.31, 'grad_norm': 38.090843200683594, 'learning_rate': 1.5289314595273615e-05, 'epoch': 1.18}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.28202229738235474, 'eval_accuracy': 0.9236887894606015, 'eval_runtime': 68.9083, 'eval_samples_per_second': 58.382, 'eval_steps_per_second': 58.382, 'epoch': 1.18}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-15000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-15500\classifier_weights.pt
{'loss': 0.3136, 'grad_norm': 0.14571425318717957, 'learning_rate': 1.497526890162519e-05, 'epoch': 1.26}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27472326159477234, 'eval_accuracy': 0.9256773552075566, 'eval_runtime': 70.5181, 'eval_samples_per_second': 57.049, 'eval_steps_per_second': 57.049, 'epoch': 1.26}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-16000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-16500\classifier_weights.pt
{'loss': 0.2919, 'grad_norm': 5.793835639953613, 'learning_rate': 1.4661223207976762e-05, 'epoch': 1.33}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27941152453422546, 'eval_accuracy': 0.9271687795177728, 'eval_runtime': 69.5733, 'eval_samples_per_second': 57.824, 'eval_steps_per_second': 57.824, 'epoch': 1.33}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-17000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-17500\classifier_weights.pt
{'loss': 0.2937, 'grad_norm': 11.760358810424805, 'learning_rate': 1.4347177514328337e-05, 'epoch': 1.41}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27444520592689514, 'eval_accuracy': 0.9281630623912503, 'eval_runtime': 70.4086, 'eval_samples_per_second': 57.138, 'eval_steps_per_second': 57.138, 'epoch': 1.41}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-18000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-18500\classifier_weights.pt
{'loss': 0.289, 'grad_norm': 1.055022120475769, 'learning_rate': 1.403313182067991e-05, 'epoch': 1.49}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2708047926425934, 'eval_accuracy': 0.926671638081034, 'eval_runtime': 70.0355, 'eval_samples_per_second': 57.442, 'eval_steps_per_second': 57.442, 'epoch': 1.49}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-19000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-19500\classifier_weights.pt
{'loss': 0.2872, 'grad_norm': 0.2700498104095459, 'learning_rate': 1.3719086127031485e-05, 'epoch': 1.57}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.276593416929245, 'eval_accuracy': 0.9264230673626647, 'eval_runtime': 68.7177, 'eval_samples_per_second': 58.544, 'eval_steps_per_second': 58.544, 'epoch': 1.57}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-20000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-20500\classifier_weights.pt
{'loss': 0.2869, 'grad_norm': 0.08594918996095657, 'learning_rate': 1.3405040433383058e-05, 'epoch': 1.65}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.29186058044433594, 'eval_accuracy': 0.9239373601789709, 'eval_runtime': 69.0381, 'eval_samples_per_second': 58.272, 'eval_steps_per_second': 58.272, 'epoch': 1.65}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-21000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-21500\classifier_weights.pt
{'loss': 0.2962, 'grad_norm': 58.73473358154297, 'learning_rate': 1.3090994739734633e-05, 'epoch': 1.73}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.26886290311813354, 'eval_accuracy': 0.9286602038279891, 'eval_runtime': 69.6765, 'eval_samples_per_second': 57.738, 'eval_steps_per_second': 57.738, 'epoch': 1.73}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-22000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-22500\classifier_weights.pt
{'loss': 0.2662, 'grad_norm': 1.5426124334335327, 'learning_rate': 1.2776949046086207e-05, 'epoch': 1.81}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2844911217689514, 'eval_accuracy': 0.926671638081034, 'eval_runtime': 70.2956, 'eval_samples_per_second': 57.23, 'eval_steps_per_second': 57.23, 'epoch': 1.81}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-23000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-23500\classifier_weights.pt
{'loss': 0.3113, 'grad_norm': 18.844518661499023, 'learning_rate': 1.246290335243778e-05, 'epoch': 1.88}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2815795838832855, 'eval_accuracy': 0.9244345016157096, 'eval_runtime': 68.1893, 'eval_samples_per_second': 58.997, 'eval_steps_per_second': 58.997, 'epoch': 1.88}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-24000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-24500\classifier_weights.pt
{'loss': 0.2897, 'grad_norm': 1.2693936824798584, 'learning_rate': 1.2148857658789355e-05, 'epoch': 1.96}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.280698299407959, 'eval_accuracy': 0.9296544867014666, 'eval_runtime': 69.1398, 'eval_samples_per_second': 58.186, 'eval_steps_per_second': 58.186, 'epoch': 1.96}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-25000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-25500\classifier_weights.pt
{'loss': 0.2861, 'grad_norm': 33.06058883666992, 'learning_rate': 1.1834811965140928e-05, 'epoch': 2.04}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27526798844337463, 'eval_accuracy': 0.9276659209545116, 'eval_runtime': 69.1018, 'eval_samples_per_second': 58.218, 'eval_steps_per_second': 58.218, 'epoch': 2.04}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-26000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-26500\classifier_weights.pt
{'loss': 0.2948, 'grad_norm': 0.09252454340457916, 'learning_rate': 1.1520766271492503e-05, 'epoch': 2.12}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2801552414894104, 'eval_accuracy': 0.9291573452647278, 'eval_runtime': 68.8922, 'eval_samples_per_second': 58.396, 'eval_steps_per_second': 58.396, 'epoch': 2.12}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-27000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-27500\classifier_weights.pt
{'loss': 0.2743, 'grad_norm': 12.146191596984863, 'learning_rate': 1.1206720577844076e-05, 'epoch': 2.2}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2919725775718689, 'eval_accuracy': 0.9264230673626647, 'eval_runtime': 135.6903, 'eval_samples_per_second': 29.648, 'eval_steps_per_second': 29.648, 'epoch': 2.2}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-28000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-28500\classifier_weights.pt
{'loss': 0.282, 'grad_norm': 42.313602447509766, 'learning_rate': 1.0892674884195651e-05, 'epoch': 2.28}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.26897403597831726, 'eval_accuracy': 0.9276659209545116, 'eval_runtime': 86.478, 'eval_samples_per_second': 46.52, 'eval_steps_per_second': 46.52, 'epoch': 2.28}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-29000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-29500\classifier_weights.pt
{'loss': 0.283, 'grad_norm': 13.30517864227295, 'learning_rate': 1.0578629190547226e-05, 'epoch': 2.36}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.26428166031837463, 'eval_accuracy': 0.9284116331096197, 'eval_runtime': 66.5074, 'eval_samples_per_second': 60.49, 'eval_steps_per_second': 60.49, 'epoch': 2.36}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-30000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-30500\classifier_weights.pt
{'loss': 0.2651, 'grad_norm': 0.08382086455821991, 'learning_rate': 1.0264583496898799e-05, 'epoch': 2.43}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2763022482395172, 'eval_accuracy': 0.9284116331096197, 'eval_runtime': 67.6609, 'eval_samples_per_second': 59.458, 'eval_steps_per_second': 59.458, 'epoch': 2.43}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-31000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-31500\classifier_weights.pt
{'loss': 0.2736, 'grad_norm': 0.08806030452251434, 'learning_rate': 9.950537803250373e-06, 'epoch': 2.51}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27505239844322205, 'eval_accuracy': 0.9294059159830972, 'eval_runtime': 88.2167, 'eval_samples_per_second': 45.604, 'eval_steps_per_second': 45.604, 'epoch': 2.51}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-32000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-32500\classifier_weights.pt
{'loss': 0.2808, 'grad_norm': 60.54993438720703, 'learning_rate': 9.636492109601948e-06, 'epoch': 2.59}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27964112162590027, 'eval_accuracy': 0.926671638081034, 'eval_runtime': 131.9086, 'eval_samples_per_second': 30.498, 'eval_steps_per_second': 30.498, 'epoch': 2.59}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-33000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-33500\classifier_weights.pt
{'loss': 0.2782, 'grad_norm': 34.906436920166016, 'learning_rate': 9.322446415953523e-06, 'epoch': 2.67}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2723170518875122, 'eval_accuracy': 0.9311459110116829, 'eval_runtime': 127.9459, 'eval_samples_per_second': 31.443, 'eval_steps_per_second': 31.443, 'epoch': 2.67}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-34000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-34500\classifier_weights.pt
{'loss': 0.2898, 'grad_norm': 20.212724685668945, 'learning_rate': 9.008400722305096e-06, 'epoch': 2.75}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2711534798145294, 'eval_accuracy': 0.9291573452647278, 'eval_runtime': 128.52, 'eval_samples_per_second': 31.303, 'eval_steps_per_second': 31.303, 'epoch': 2.75}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-35000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-35500\classifier_weights.pt
{'loss': 0.2959, 'grad_norm': 43.31317901611328, 'learning_rate': 8.69435502865667e-06, 'epoch': 2.83}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27021121978759766, 'eval_accuracy': 0.9301516281382053, 'eval_runtime': 127.9081, 'eval_samples_per_second': 31.452, 'eval_steps_per_second': 31.452, 'epoch': 2.83}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-36000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-36500\classifier_weights.pt
{'loss': 0.2765, 'grad_norm': 0.11963970214128494, 'learning_rate': 8.380309335008244e-06, 'epoch': 2.9}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2710108458995819, 'eval_accuracy': 0.9308973402933135, 'eval_runtime': 129.0118, 'eval_samples_per_second': 31.183, 'eval_steps_per_second': 31.183, 'epoch': 2.9}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-37000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-37500\classifier_weights.pt
{'loss': 0.2662, 'grad_norm': 0.21727217733860016, 'learning_rate': 8.066263641359819e-06, 'epoch': 2.98}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2696925401687622, 'eval_accuracy': 0.930648769574944, 'eval_runtime': 131.0149, 'eval_samples_per_second': 30.706, 'eval_steps_per_second': 30.706, 'epoch': 2.98}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-38000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-38500\classifier_weights.pt
{'loss': 0.2725, 'grad_norm': 1.475920557975769, 'learning_rate': 7.752217947711392e-06, 'epoch': 3.06}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27265045046806335, 'eval_accuracy': 0.9289087745463585, 'eval_runtime': 127.388, 'eval_samples_per_second': 31.581, 'eval_steps_per_second': 31.581, 'epoch': 3.06}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-39000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-39500\classifier_weights.pt
{'loss': 0.2618, 'grad_norm': 17.22598648071289, 'learning_rate': 7.4381722540629665e-06, 'epoch': 3.14}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2784310281276703, 'eval_accuracy': 0.9276659209545116, 'eval_runtime': 95.5845, 'eval_samples_per_second': 42.088, 'eval_steps_per_second': 42.088, 'epoch': 3.14}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-40000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-40500\classifier_weights.pt
{'loss': 0.2724, 'grad_norm': 0.5255399942398071, 'learning_rate': 7.12412656041454e-06, 'epoch': 3.22}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2875082194805145, 'eval_accuracy': 0.9276659209545116, 'eval_runtime': 129.3758, 'eval_samples_per_second': 31.095, 'eval_steps_per_second': 31.095, 'epoch': 3.22}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-41000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-41500\classifier_weights.pt
{'loss': 0.2837, 'grad_norm': 10.175849914550781, 'learning_rate': 6.810080866766116e-06, 'epoch': 3.3}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2854343056678772, 'eval_accuracy': 0.9276659209545116, 'eval_runtime': 132.3785, 'eval_samples_per_second': 30.39, 'eval_steps_per_second': 30.39, 'epoch': 3.3}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-42000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-42500\classifier_weights.pt
{'loss': 0.2642, 'grad_norm': 68.31334686279297, 'learning_rate': 6.49603517311769e-06, 'epoch': 3.38}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.28169894218444824, 'eval_accuracy': 0.9294059159830972, 'eval_runtime': 128.6101, 'eval_samples_per_second': 31.281, 'eval_steps_per_second': 31.281, 'epoch': 3.38}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-43000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-43500\classifier_weights.pt
{'loss': 0.2521, 'grad_norm': 8.763825416564941, 'learning_rate': 6.181989479469264e-06, 'epoch': 3.45}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2798781096935272, 'eval_accuracy': 0.930648769574944, 'eval_runtime': 131.4114, 'eval_samples_per_second': 30.614, 'eval_steps_per_second': 30.614, 'epoch': 3.45}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-44000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-44500\classifier_weights.pt
{'loss': 0.2829, 'grad_norm': 19.87236213684082, 'learning_rate': 5.867943785820838e-06, 'epoch': 3.53}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2783549129962921, 'eval_accuracy': 0.9311459110116829, 'eval_runtime': 129.304, 'eval_samples_per_second': 31.113, 'eval_steps_per_second': 31.113, 'epoch': 3.53}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-45000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-45500\classifier_weights.pt
{'loss': 0.2943, 'grad_norm': 5.468142032623291, 'learning_rate': 5.553898092172412e-06, 'epoch': 3.61}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27318060398101807, 'eval_accuracy': 0.9316430524484216, 'eval_runtime': 128.4482, 'eval_samples_per_second': 31.32, 'eval_steps_per_second': 31.32, 'epoch': 3.61}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-46000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-46500\classifier_weights.pt
{'loss': 0.2756, 'grad_norm': 0.8341482877731323, 'learning_rate': 5.2398523985239855e-06, 'epoch': 3.69}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.286668598651886, 'eval_accuracy': 0.926671638081034, 'eval_runtime': 129.8789, 'eval_samples_per_second': 30.975, 'eval_steps_per_second': 30.975, 'epoch': 3.69}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-47000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-47500\classifier_weights.pt
{'loss': 0.3082, 'grad_norm': 41.5838737487793, 'learning_rate': 4.925806704875559e-06, 'epoch': 3.77}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2649371325969696, 'eval_accuracy': 0.9323887646035297, 'eval_runtime': 127.1639, 'eval_samples_per_second': 31.636, 'eval_steps_per_second': 31.636, 'epoch': 3.77}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-48000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-48500\classifier_weights.pt
{'loss': 0.2736, 'grad_norm': 0.17811717092990875, 'learning_rate': 4.611761011227134e-06, 'epoch': 3.85}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27172622084617615, 'eval_accuracy': 0.9316430524484216, 'eval_runtime': 131.2223, 'eval_samples_per_second': 30.658, 'eval_steps_per_second': 30.658, 'epoch': 3.85}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-49000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-49500\classifier_weights.pt
{'loss': 0.2642, 'grad_norm': 2.363492012023926, 'learning_rate': 4.297715317578708e-06, 'epoch': 3.93}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2754945158958435, 'eval_accuracy': 0.930648769574944, 'eval_runtime': 127.6819, 'eval_samples_per_second': 31.508, 'eval_steps_per_second': 31.508, 'epoch': 3.93}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-50000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-50500\classifier_weights.pt
{'loss': 0.2594, 'grad_norm': 0.345004677772522, 'learning_rate': 3.983669623930283e-06, 'epoch': 4.0}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.28433331847190857, 'eval_accuracy': 0.9301516281382053, 'eval_runtime': 131.9353, 'eval_samples_per_second': 30.492, 'eval_steps_per_second': 30.492, 'epoch': 4.0}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-51000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-51500\classifier_weights.pt
{'loss': 0.2656, 'grad_norm': 0.2842141091823578, 'learning_rate': 3.6696239302818563e-06, 'epoch': 4.08}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27343475818634033, 'eval_accuracy': 0.9301516281382053, 'eval_runtime': 127.8405, 'eval_samples_per_second': 31.469, 'eval_steps_per_second': 31.469, 'epoch': 4.08}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-52000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-52500\classifier_weights.pt
{'loss': 0.2784, 'grad_norm': 0.13248850405216217, 'learning_rate': 3.3555782366334307e-06, 'epoch': 4.16}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27562618255615234, 'eval_accuracy': 0.9308973402933135, 'eval_runtime': 130.4892, 'eval_samples_per_second': 30.83, 'eval_steps_per_second': 30.83, 'epoch': 4.16}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-53000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-53500\classifier_weights.pt
{'loss': 0.2633, 'grad_norm': 20.39910888671875, 'learning_rate': 3.0415325429850046e-06, 'epoch': 4.24}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27606484293937683, 'eval_accuracy': 0.9281630623912503, 'eval_runtime': 129.276, 'eval_samples_per_second': 31.119, 'eval_steps_per_second': 31.119, 'epoch': 4.24}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-54000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-54500\classifier_weights.pt
{'loss': 0.283, 'grad_norm': 0.09856466948986053, 'learning_rate': 2.7274868493365785e-06, 'epoch': 4.32}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.26912423968315125, 'eval_accuracy': 0.9311459110116829, 'eval_runtime': 128.3715, 'eval_samples_per_second': 31.339, 'eval_steps_per_second': 31.339, 'epoch': 4.32}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-55000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-55500\classifier_weights.pt
{'loss': 0.2524, 'grad_norm': 0.2043904960155487, 'learning_rate': 2.413441155688153e-06, 'epoch': 4.4}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27334344387054443, 'eval_accuracy': 0.9313944817300522, 'eval_runtime': 130.7202, 'eval_samples_per_second': 30.776, 'eval_steps_per_second': 30.776, 'epoch': 4.4}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-56000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-56500\classifier_weights.pt
{'loss': 0.2503, 'grad_norm': 3.189560890197754, 'learning_rate': 2.099395462039727e-06, 'epoch': 4.48}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2786867618560791, 'eval_accuracy': 0.9304001988565747, 'eval_runtime': 72.7376, 'eval_samples_per_second': 55.308, 'eval_steps_per_second': 55.308, 'epoch': 4.48}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-57000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-57500\classifier_weights.pt
{'loss': 0.2804, 'grad_norm': 0.22956883907318115, 'learning_rate': 1.785349768391301e-06, 'epoch': 4.55}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27487775683403015, 'eval_accuracy': 0.9308973402933135, 'eval_runtime': 70.8458, 'eval_samples_per_second': 56.785, 'eval_steps_per_second': 56.785, 'epoch': 4.55}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-58000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-58500\classifier_weights.pt
{'loss': 0.255, 'grad_norm': 0.13664110004901886, 'learning_rate': 1.4713040747428754e-06, 'epoch': 4.63}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2742777466773987, 'eval_accuracy': 0.930648769574944, 'eval_runtime': 69.2276, 'eval_samples_per_second': 58.113, 'eval_steps_per_second': 58.113, 'epoch': 4.63}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-59000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-59500\classifier_weights.pt
{'loss': 0.2624, 'grad_norm': 0.11229503899812698, 'learning_rate': 1.1572583810944493e-06, 'epoch': 4.71}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2740297317504883, 'eval_accuracy': 0.9311459110116829, 'eval_runtime': 68.3068, 'eval_samples_per_second': 58.896, 'eval_steps_per_second': 58.896, 'epoch': 4.71}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-60000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-60500\classifier_weights.pt
{'loss': 0.2647, 'grad_norm': 0.0686878114938736, 'learning_rate': 8.432126874460235e-07, 'epoch': 4.79}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2748365104198456, 'eval_accuracy': 0.9311459110116829, 'eval_runtime': 67.6803, 'eval_samples_per_second': 59.441, 'eval_steps_per_second': 59.441, 'epoch': 4.79}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-61000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-61500\classifier_weights.pt
{'loss': 0.277, 'grad_norm': 10.775510787963867, 'learning_rate': 5.291669937975976e-07, 'epoch': 4.87}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.27217984199523926, 'eval_accuracy': 0.9316430524484216, 'eval_runtime': 71.1728, 'eval_samples_per_second': 56.524, 'eval_steps_per_second': 56.524, 'epoch': 4.87}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-62000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-62500\classifier_weights.pt
{'loss': 0.2899, 'grad_norm': 4.636594295501709, 'learning_rate': 2.151213001491717e-07, 'epoch': 4.95}

  0%|          | 0/4023 [00:00<?, ?it/s]

{'eval_loss': 0.2733895480632782, 'eval_accuracy': 0.930648769574944, 'eval_runtime': 68.5292, 'eval_samples_per_second': 58.705, 'eval_steps_per_second': 58.705, 'epoch': 4.95}
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-63000\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-63500\classifier_weights.pt
Saved checkpoint classifier weights to checkpoints_v4\checkpoint-63685\classifier_weights.pt
{'train_runtime': 9009.4264, 'train_samples_per_second': 42.411, 'train_steps_per_second': 7.069, 'train_loss': 0.2868387020279102, 'epoch': 5.0}
CPU times: total: 2h 22min 12s
Wall time: 2h 30min 9s

TrainOutput(global_step=63685, training_loss=0.2868387020279102, metrics={'train_runtime': 9009.4264, 'train_samples_per_second': 42.411, 'train_steps_per_second': 7.069, 'total_flos': 0.0, 'train_loss': 0.2868387020279102, 'epoch': 5.0})

# Make a test

In [63]:
text = "今天天氣真好，我很開心"
predict_sentiment(text, model, tokenizer, device)

{'text': '今天天氣真好，我很開心',
 'sentiment': '正面',
 'confidence': 1.0,
 'probabilities': {'負面': 0.0, '正面': 1.0}}

In [64]:
text = "這個產品品質差，服務更糟糕"
predict_sentiment(text, model, tokenizer, device)

{'text': '這個產品品質差，服務更糟糕',
 'sentiment': '負面',
 'confidence': 1.0,
 'probabilities': {'負面': 1.0, '正面': 0.0}}

# Save Model

In [65]:
#存lora_model
# model_path = "trained_lora_model_v1"
# trainer.model.save_pretrained(model_path)

In [66]:
# 這樣存檔 - 只會儲存分類器權重和設定
# model_path = "trained_classifier_v4"
# trainer.save_model(model_path)
# model.save_pretrained(model_path)

In [67]:
# 這樣存檔 - 只會儲存分類器權重和設定
model_path = "trained_classifier_v4"
model.save_model(model_path)
# model.save_pretrained(model_path)

已保存分類器權重至 trained_classifier_v4\classifier_weights.pt

# Evaluate the model

In [68]:
def predict(input_text):
    inputs = tokenizer(input_text, return_tensors="pt").to(device)  # Convert to PyTorch tensors and move to GPU (if available)
    with torch.no_grad():
        #outputs = model(**inputs).logits  # Get the model's output logits
        outputs = model(**inputs)['logits']  # Get the model's output logits
        y_prob = torch.sigmoid(outputs).tolist()[0]  # Apply sigmoid activation and convert to list
    return np.round(y_prob, 2)  # Round the predicted probability to 2 decimal places

In [69]:
def inference(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(device)
    with torch.no_grad():
        outputs = model(**inputs)
    probs = torch.softmax(outputs['logits'], dim=1)
    #probs = torch.softmax(outputs.logits, dim=1)
    return probs.argmax().item()

In [70]:
df_test = pd.DataFrame(data=test_data)

In [71]:
df_test

,text,label,input_ids,attention_mask
0,顏色比想像的要深得多……感謝快遞員，每次都非常好,1,"[119283, 38035, 56006, 111176, 9370, 30534, 99...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,虧了，前一天買的108，第二天看就成99了…這也太,0,"[83164, 100, 34187, 3837, 115982, 102810, 9370...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,太大的遊戲有點卡 其他的都很好 看電視特別爽,1,"[99222, 99750, 110256, 114863, 99603, 34369, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
3,是正品哦，套裝系列的，買得很划算，用了小樣，不怎麼好拍照，真的很划算。,1,"[20412, 116470, 104170, 3837, 99619, 105290, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,一個涼菜十塊錢，就退了七塊五，打電話過去，說那邊很忙，五分鐘以後回過來電話，也沒信了！太沒誠...,0,"[104061, 118178, 99800, 94498, 111145, 102666,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...,...,...
4018,非常差穿一回不想穿二回,0,"[99491, 99572, 99621, 14777, 18397, 104359, 99...","[1, 1, 1, 1, 1, 1, 1, 1, 1]"
4019,收到的火龍果是爛的，上面寫的是冷鏈收到卻是爛的,0,"[104381, 9370, 79599, 106430, 27773, 20412, 75...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4020,歐式簡約裝潢，有飄窗，可惜周圍全是樓，大床是2張小床拼成的，可以看出小床很小，羽絨被、枕頭，...,1,"[112311, 28330, 103271, 104894, 105290, 121501...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4021,包裝的很結實，一直信賴沙宣，信賴京東。看保質期都到2020年，很好。,1,"[67279, 105290, 9370, 99165, 100331, 99862, 38...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4022,白天沒有熱水，洗手間里竟然還有螞蟻在爬，很小的淋浴房，沒有浴缸，沒有電梯。早餐簡單的難以想象...,0,"[106772, 104106, 105104, 52510, 3837, 111287, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [72]:
input_text='''立法院今天發布人事通報，總務處長周傑調任參事室參事並代理總務處長，引發外界聯想立法院長韓國瑜出手進行人事調整。周傑今天受訪表示，正常調動，謝謝關心。
部分媒體報導，質疑立法院總務處長人事異動，是否與先前立法院立委辦公室傳出有裝潢費昂貴、不合理等情形，或是日前立法院司法及法制委員會有委員提議要更改格局，而周傑回應「建議要更動是否可在會期中研議規畫，休會時再改」，令國民黨立法院黨團總召傅崐萁不以為然有關。'''
predict(input_text)

array([0.13, 0.85])

In [73]:
input_text = "我不高興"
inference(input_text)

0

In [86]:
%%time
df_test['prediction'] = df_test['text'].map(predict)
df_test['y_pred'] = df_test['prediction'].apply(lambda x: np.argmax(x, axis=0)) 

# 
# df_test['prediction'] = df_test['text'].map(inference)

CPU times: total: 1min 2s
Wall time: 1min 5s

In [87]:
accuracy = (df_test['y_pred'] == df_test['label']).mean()
print(f"Model Accuracy on Test Data: {accuracy:.4f}")
df_test.head()

Model Accuracy on Test Data: 0.9306

,text,label,input_ids,attention_mask,prediction,y_pred
0,顏色比想像的要深得多……感謝快遞員，每次都非常好,1,"[119283, 38035, 56006, 111176, 9370, 30534, 99...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0.06, 0.92]",1
1,虧了，前一天買的108，第二天看就成99了…這也太,0,"[83164, 100, 34187, 3837, 115982, 102810, 9370...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0.95, 0.07]",0
2,太大的遊戲有點卡 其他的都很好 看電視特別爽,1,"[99222, 99750, 110256, 114863, 99603, 34369, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[0.06, 0.88]",1
3,是正品哦，套裝系列的，買得很划算，用了小樣，不怎麼好拍照，真的很划算。,1,"[20412, 116470, 104170, 3837, 99619, 105290, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0.04, 0.95]",1
4,一個涼菜十塊錢，就退了七塊五，打電話過去，說那邊很忙，五分鐘以後回過來電話，也沒信了！太沒誠...,0,"[104061, 118178, 99800, 94498, 111145, 102666,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0.96, 0.06]",0

In [89]:
cm = metrics.confusion_matrix(df_test['label'], df_test['y_pred'])
cm

array([[1962,  104],
       [ 175, 1782]], dtype=int64)

In [90]:
print(metrics.classification_report(df_test['label'], df_test['y_pred']))

              precision    recall  f1-score   support

           0       0.92      0.95      0.93      2066
           1       0.94      0.91      0.93      1957

    accuracy                           0.93      4023
   macro avg       0.93      0.93      0.93      4023
weighted avg       0.93      0.93      0.93      4023

In [79]:
metrics.precision_score(df_test['label'], df_test['y_pred'], average='micro')

0.9281630623912503

In [80]:
metrics.precision_score(df_test['label'], df_test['y_pred'], average='macro')

0.9291980777462081

In [81]:
metrics.recall_score(df_test['label'], df_test['y_pred'], average='micro')

0.9281630623912503

In [82]:
metrics.recall_score(df_test['label'], df_test['y_pred'], average='macro')

0.9275643667011118

# Load model

In [ ]:
# 在外部先載入base_model預訓練權重(不包含分類層)
# full_model = AutoModelForCausalLM.from_pretrained(model_id)
#
model_path = "trained_classifier_v4"
# model_path = "checkpoints_v3\checkpoint-4145"
hidden_size = full_model.config.hidden_size
model = QwenForClassifier(full_model.model, hidden_size, num_labels= len(categories))

model.load_model(model_path, device=device)

# 移動到指定設備
model = model.to(device)

已載入分類器權重: trained_classifier_v3\classifier_weights.pt

In [ ]:
text = "這個產品品質差，服務更糟糕"
predict_sentiment(text, model, tokenizer, device)

{'text': '這個產品品質差，服務更糟糕',
 'sentiment': '正面',
 'confidence': 0.55,
 'probabilities': {'負面': 0.45, '正面': 0.55}}

In [ ]:
full_model

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2SdpaAttention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
          (rotary_emb): Qwen2RotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=896, out_features=151936, bias=False)
)

# Text generation fro full_model

In [ ]:
from IPython.display import Markdown

In [ ]:
def generate_text(input_prompt):
    
    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": input_prompt}
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    model_inputs = tokenizer([text], return_tensors="pt").to(device)

    prompt_length = model_inputs['input_ids'].shape[1]

    generated_ids = full_model.generate(
        model_inputs.input_ids,
        max_new_tokens=512,
        pad_token_id=tokenizer.eos_token_id
    )
    response = tokenizer.decode(generated_ids[0][prompt_length:], skip_special_tokens=True)
    return response

In [ ]:
text="給出三個保持健康的提示。"
result = generate_text(text)
Markdown(result)

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

1. 保持充足的睡眠：良好的睡眠对于身体和心理健康至关重要，建议成年人每晚至少睡7-9小时。

2. 均衡饮食：摄取均衡的营养，包括足够的蛋白质、碳水化合物、脂肪、维生素和矿物质。避免过多摄入加工食品和高糖食品。

3. 定期锻炼：定期进行有氧运动和力量训练可以帮助增强心肺功能，提高免疫力，并减轻压力。建议每周至少进行150分钟的中等强度运动或75分钟的高强度运动。

In [ ]:
%%time
text="我們如何減少空氣污染？請給幾項重要的建議。"
result = generate_text(text)
Markdown(result)

CPU times: total: 2.92 s
Wall time: 2.99 s

1. 設計和建造低排放建築物，使用可再生能源。
2. 運用更高效的交通工具，例如公車、電力車、公共交通工具等。
3. 改進能源消費方式，如使用节能电器和灯具。
4. 提高能效的產品和技術，以降低能源消耗。
5. 篩選和回收廢棄物，減少垃圾填埋和焚烧。
6. 限制工业废气排放，採用高效能的工業設備和技術。
7. 增加綠色能源的使用比例，提高能源效率。
8. 推廣低碳生活方式，如少用一次性塑料制品、節約用水用电等。
9. 加強環境保護法律和政策，促進企業遵守环保要求。
10. 加强環境教育和宣傳，提高公民的環境意識。